"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.TOD_ANIMATION_LAST_SECOND =
		exports.TOD_CAMERA_SETTING_NAME =
		exports.TOD_MAX_ADJUST_DAY =
		exports.TOD_MIN_ADJUST_MINUTE =
		exports.TOD_CIRCLE_ANGLE =
		exports.TOD_RATE_RATIO =
		exports.TOD_TICK_INTERVAL_MILLIONSECOND =
		exports.TOD_TICK_INTERVAL_SECOND =
		exports.TOD_SAVE_CD_SECONDS =
		exports.TOD_SAVE_CD_MINUTE =
		exports.TOD_MILLIONSECOND_PER_DAY =
		exports.TOD_SECOND_PER_DAY =
		exports.TOD_SECOND_PER_HOUR =
		exports.TOD_MINUTE_PER_DAY =
		exports.TOD_HOUR_PER_DAY =
		exports.TOD_MINUTE_PER_HOUR =
		exports.TOD_SECOND_PER_MINUTE =
		exports.TOD_MILLIONSECOND_PER_SECOND =
			void 0),
	(exports.TOD_MILLIONSECOND_PER_SECOND = 1e3),
	(exports.TOD_SECOND_PER_MINUTE = 60),
	(exports.TOD_MINUTE_PER_HOUR = 60),
	(exports.TOD_HOUR_PER_DAY = 24),
	(exports.TOD_MINUTE_PER_DAY =
		exports.TOD_MINUTE_PER_HOUR * exports.TOD_HOUR_PER_DAY),
	(exports.TOD_SECOND_PER_HOUR =
		exports.TOD_SECOND_PER_MINUTE * exports.TOD_MINUTE_PER_HOUR),
	(exports.TOD_SECOND_PER_DAY =
		exports.TOD_HOUR_PER_DAY *
		exports.TOD_MINUTE_PER_HOUR *
		exports.TOD_SECOND_PER_MINUTE),
	(exports.TOD_MILLIONSECOND_PER_DAY =
		exports.TOD_SECOND_PER_DAY * exports.TOD_MILLIONSECOND_PER_SECOND),
	(exports.TOD_SAVE_CD_MINUTE = 2),
	(exports.TOD_SAVE_CD_SECONDS =
		exports.TOD_SAVE_CD_MINUTE * exports.TOD_SECOND_PER_MINUTE),
	(exports.TOD_TICK_INTERVAL_SECOND = 0),
	(exports.TOD_TICK_INTERVAL_MILLIONSECOND =
		exports.TOD_MILLIONSECOND_PER_SECOND * exports.TOD_TICK_INTERVAL_SECOND),
	(exports.TOD_RATE_RATIO = 1e4),
	(exports.TOD_CIRCLE_ANGLE = 360),
	(exports.TOD_MIN_ADJUST_MINUTE = 30),
	(exports.TOD_MAX_ADJUST_DAY = 2),
	(exports.TOD_CAMERA_SETTING_NAME = "1032"),
	(exports.TOD_ANIMATION_LAST_SECOND = 2);
