"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.tsBaseRoleConfig = void 0),
	(exports.tsBaseRoleConfig = {
		AnimRunSpeed: 400,
		AnimSprintSpeed: 700,
		MinRunStopSpeed: 100,
		MaxRunStopSpeed: 150,
		SmoothCharacterRotationSpeed: 60,
		FlyingGravity: 15,
		FlyingFriction: 0.025,
		FlyingDeceleration: 0.07,
		FlyingAccelerator: 20,
		FlyingMaxSpeed: 550,
		FlyingMaxFallingSpeed: 220,
		QteBornPositionCheckHeight: 300,
		QteBornPositionCheckLength: 600,
		CheckLockEffectRate: 0.33333,
		HeadStateRange: 1e3,
		WalkStopSpeedLimit: 0,
	});
