"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.UE_OTHER_COMPONENT_TICK_PRIORITY =
		exports.UE_SKELETAL_TICK_PRIORITY =
		exports.MOVEMENT_SYNC_TICK_PRIORITY =
		exports.GAIT_TICK_PRIORITY =
		exports.MOVE_TICK_PRIORITY =
		exports.CLIMB_TICK_PRIORITY =
		exports.SLIDE_TICK_PRIORITY =
		exports.SPLINE_MOVE_TICK_PRIORITY =
		exports.INPUT_TICK_PRIORITY =
		exports.ACTOR_TICK_PRIORITY =
		exports.UE_ACTOR_TICK_PRIOTITY =
		exports.UE_MOVE_TICK_PRIORITY =
			void 0),
	(exports.UE_MOVE_TICK_PRIORITY = 1e3),
	(exports.UE_ACTOR_TICK_PRIOTITY = 900),
	(exports.ACTOR_TICK_PRIORITY = 100),
	(exports.INPUT_TICK_PRIORITY = 99),
	(exports.SPLINE_MOVE_TICK_PRIORITY = 98),
	(exports.SLIDE_TICK_PRIORITY = 91),
	(exports.CLIMB_TICK_PRIORITY = 90),
	(exports.MOVE_TICK_PRIORITY = 80),
	(exports.GAIT_TICK_PRIORITY = 70),
	(exports.MOVEMENT_SYNC_TICK_PRIORITY = 60),
	(exports.UE_SKELETAL_TICK_PRIORITY = 50),
	(exports.UE_OTHER_COMPONENT_TICK_PRIORITY = 1);
