"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.CUSTOM_MOVEMENTMODE_SKI =
		exports.CUSTOM_MOVEMENTMODE_SOAR =
		exports.CUSTOM_MOVEMENTMODE_LEISURE =
		exports.CUSTOM_MOVEMENTMODE_UP_TO_WALK_ON_WATER =
		exports.CUSTOM_MOVEMENTMODE_SLIDE =
		exports.CUSTOM_MOVEMENTMODE_PENDULUM =
		exports.CUSTOM_MOVEMENTMODE_GLIDE =
		exports.CUSTOM_MOVEMENTMODE_SWIM =
		exports.CUSTOM_MOVEMENTMODE_CLIMB =
			void 0),
	(exports.CUSTOM_MOVEMENTMODE_CLIMB = 0),
	(exports.CUSTOM_MOVEMENTMODE_SWIM = 1),
	(exports.CUSTOM_MOVEMENTMODE_GLIDE = 2),
	(exports.CUSTOM_MOVEMENTMODE_PENDULUM = 3),
	(exports.CUSTOM_MOVEMENTMODE_SLIDE = 4),
	(exports.CUSTOM_MOVEMENTMODE_UP_TO_WALK_ON_WATER = 5),
	(exports.CUSTOM_MOVEMENTMODE_LEISURE = 6),
	(exports.CUSTOM_MOVEMENTMODE_SOAR = 7),
	(exports.CUSTOM_MOVEMENTMODE_SKI = 8);
