"use strict";
var EEventName;
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.EEventName = void 0),
	(function (e) {
		(e[(e.SetEntityCreatureDataRelation = 0)] =
			"SetEntityCreatureDataRelation"),
			(e[(e.KeyClick = 1)] = "KeyClick"),
			(e[(e.UiSceneLoaded = 2)] = "UiSceneLoaded"),
			(e[(e.UiSceneStartLoad = 3)] = "UiSceneStartLoad"),
			(e[(e.OpenView = 4)] = "OpenView"),
			(e[(e.StackPreOpenView = 5)] = "StackPreOpenView"),
			(e[(e.StackOpenView = 6)] = "StackOpenView"),
			(e[(e.StackCloseView = 7)] = "StackCloseView"),
			(e[(e.OpenViewBegined = 8)] = "OpenViewBegined"),
			(e[(e.OpenViewFail = 9)] = "OpenViewFail"),
			(e[(e.CreateViewInstance = 10)] = "CreateViewInstance"),
			(e[(e.OnViewLoadCompleted = 11)] = "OnViewLoadCompleted"),
			(e[(e.OnViewDone = 12)] = "OnViewDone"),
			(e[(e.OnViewHidden = 13)] = "OnViewHidden"),
			(e[(e.CloseView = 14)] = "CloseView"),
			(e[(e.OpenTabView = 15)] = "OpenTabView"),
			(e[(e.TriggerUiTimeDilation = 16)] = "TriggerUiTimeDilation"),
			(e[(e.CloseTabView = 17)] = "CloseTabView"),
			(e[(e.ChangeChildView = 18)] = "ChangeChildView"),
			(e[(e.UiManagerInit = 19)] = "UiManagerInit"),
			(e[(e.UiManagerDestroy = 20)] = "UiManagerDestroy"),
			(e[(e.HotKeyInput = 21)] = "HotKeyInput"),
			(e[(e.ViewHotKeyInputPress = 22)] = "ViewHotKeyInputPress"),
			(e[(e.ViewHotKeyInputRelease = 23)] = "ViewHotKeyInputRelease"),
			(e[(e.ResetNormalAction = 24)] = "ResetNormalAction"),
			(e[(e.UnBlockCharacterAction = 25)] = "UnBlockCharacterAction"),
			(e[(e.ResetSystemAction = 26)] = "ResetSystemAction"),
			(e[(e.OnReduceDamageViewDepth = 27)] = "OnReduceDamageViewDepth"),
			(e[(e.LoginSuccess = 28)] = "LoginSuccess"),
			(e[(e.EnterGameSuccess = 29)] = "EnterGameSuccess"),
			(e[(e.LoginStatusChange = 30)] = "LoginStatusChange"),
			(e[(e.LoginRequestResult = 31)] = "LoginRequestResult"),
			(e[(e.SdkLoginResult = 32)] = "SdkLoginResult"),
			(e[(e.OnGetLoginPlayerInfo = 33)] = "OnGetLoginPlayerInfo"),
			(e[(e.OnSelectServerItem = 34)] = "OnSelectServerItem"),
			(e[(e.OnConfirmServerItem = 35)] = "OnConfirmServerItem"),
			(e[(e.SendHeartbeat = 36)] = "SendHeartbeat"),
			(e[(e.SdkInitDone = 37)] = "SdkInitDone"),
			(e[(e.TimeValidError = 38)] = "TimeValidError"),
			(e[(e.CharQteActive = 39)] = "CharQteActive"),
			(e[(e.CharQteConsume = 40)] = "CharQteConsume"),
			(e[(e.CharInQteChanged = 41)] = "CharInQteChanged"),
			(e[(e.CharExecuteMultiQte = 42)] = "CharExecuteMultiQte"),
			(e[(e.CharHitLocal = 43)] = "CharHitLocal"),
			(e[(e.CharHitRemote = 44)] = "CharHitRemote"),
			(e[(e.CharBeHitLocal = 45)] = "CharBeHitLocal"),
			(e[(e.CharHitIncludingVision = 46)] = "CharHitIncludingVision"),
			(e[(e.CharBeHitRemote = 47)] = "CharBeHitRemote"),
			(e[(e.CharLimitDodge = 48)] = "CharLimitDodge"),
			(e[(e.CharBeHitAnim = 49)] = "CharBeHitAnim"),
			(e[(e.CharBeHitTimeScale = 50)] = "CharBeHitTimeScale"),
			(e[(e.CharShieldChange = 51)] = "CharShieldChange"),
			(e[(e.CharAnimBreakPoint = 52)] = "CharAnimBreakPoint"),
			(e[(e.CharBeforeSkillWithTarget = 53)] = "CharBeforeSkillWithTarget"),
			(e[(e.CharUseSkill = 54)] = "CharUseSkill"),
			(e[(e.OnSkillEnd = 55)] = "OnSkillEnd"),
			(e[(e.OnMultiSkillIdChanged = 56)] = "OnMultiSkillIdChanged"),
			(e[(e.OnMultiSkillEnable = 57)] = "OnMultiSkillEnable"),
			(e[(e.CharSwitchControl = 58)] = "CharSwitchControl"),
			(e[(e.CharInputPress = 59)] = "CharInputPress"),
			(e[(e.CharDeleteSkill = 60)] = "CharDeleteSkill"),
			(e[(e.CharResetSkill = 61)] = "CharResetSkill"),
			(e[(e.CharInterruptSkill = 62)] = "CharInterruptSkill"),
			(e[(e.CharSkillCountChanged = 63)] = "CharSkillCountChanged"),
			(e[(e.CharSkillRemainCdChanged = 64)] = "CharSkillRemainCdChanged"),
			(e[(e.CharSkillCdPauseStateChanged = 65)] =
				"CharSkillCdPauseStateChanged"),
			(e[(e.CharClearSkill = 66)] = "CharClearSkill"),
			(e[(e.CharDamage = 67)] = "CharDamage"),
			(e[(e.CharBeDamage = 68)] = "CharBeDamage"),
			(e[(e.FormationPanelUIShowRoleHeal = 69)] =
				"FormationPanelUIShowRoleHeal"),
			(e[(e.CharPartDamage = 70)] = "CharPartDamage"),
			(e[(e.CharClimbStartExit = 71)] = "CharClimbStartExit"),
			(e[(e.CharActivateClimbInput = 72)] = "CharActivateClimbInput"),
			(e[(e.CharClimbJumpCheck = 73)] = "CharClimbJumpCheck"),
			(e[(e.CustomMoveSwim = 74)] = "CustomMoveSwim"),
			(e[(e.CustomMoveSlide = 75)] = "CustomMoveSlide"),
			(e[(e.CustomMoveSki = 76)] = "CustomMoveSki"),
			(e[(e.CustomMoveWalkOnWater = 77)] = "CustomMoveWalkOnWater"),
			(e[(e.CustomMoveClimb = 78)] = "CustomMoveClimb"),
			(e[(e.CustomMoveGlide = 79)] = "CustomMoveGlide"),
			(e[(e.CustomMovePendulum = 80)] = "CustomMovePendulum"),
			(e[(e.CustomMoveCatapult = 81)] = "CustomMoveCatapult"),
			(e[(e.CustomMoveSoar = 82)] = "CustomMoveSoar"),
			(e[(e.CharTurnBegin = 83)] = "CharTurnBegin"),
			(e[(e.CharTurnEnd = 84)] = "CharTurnEnd"),
			(e[(e.CharMovementModeChanged = 85)] = "CharMovementModeChanged"),
			(e[(e.CharActivate = 86)] = "CharActivate"),
			(e[(e.CharOnAttrChanged = 87)] = "CharOnAttrChanged"),
			(e[(e.CharOnRoleDead = 88)] = "CharOnRoleDead"),
			(e[(e.CharOnRoleDeadTargetSelf = 89)] = "CharOnRoleDeadTargetSelf"),
			(e[(e.CharOnRoleDrown = 90)] = "CharOnRoleDrown"),
			(e[(e.CharOnRoleDrownInjure = 91)] = "CharOnRoleDrownInjure"),
			(e[(e.CharOnEnergyChanged = 92)] = "CharOnEnergyChanged"),
			(e[(e.CharOnHealthChanged = 93)] = "CharOnHealthChanged"),
			(e[(e.CharOnHealthMaxChanged = 94)] = "CharOnHealthMaxChanged"),
			(e[(e.CharOnElementEnergyChanged = 95)] = "CharOnElementEnergyChanged"),
			(e[(e.CharOnUnifiedMoveStateChanged = 96)] =
				"CharOnUnifiedMoveStateChanged"),
			(e[(e.CharOnPositionStateChanged = 97)] = "CharOnPositionStateChanged"),
			(e[(e.CharOnDirectionStateChanged = 98)] = "CharOnDirectionStateChanged"),
			(e[(e.CharOnPositionSubStateChanged = 99)] =
				"CharOnPositionSubStateChanged"),
			(e[(e.CharSwimStrengthChanged = 100)] = "CharSwimStrengthChanged"),
			(e[(e.RoleOnStateInherit = 101)] = "RoleOnStateInherit"),
			(e[(e.CharOnEndPlay = 102)] = "CharOnEndPlay"),
			(e[(e.CharOnBuffAddUITexture = 103)] = "CharOnBuffAddUITexture"),
			(e[(e.CharOnBuffAddUIPrefab = 104)] = "CharOnBuffAddUIPrefab"),
			(e[(e.CharOnBuffAddUIDamage = 105)] = "CharOnBuffAddUIDamage"),
			(e[(e.CharOnAnimNotifyStateDurationChange = 106)] =
				"CharOnAnimNotifyStateDurationChange"),
			(e[(e.CharOnLand = 107)] = "CharOnLand"),
			(e[(e.CharPossessed = 108)] = "CharPossessed"),
			(e[(e.CharUnpossessed = 109)] = "CharUnpossessed"),
			(e[(e.CharChangeMeshAnim = 110)] = "CharChangeMeshAnim"),
			(e[(e.CharRecordOperate = 111)] = "CharRecordOperate"),
			(e[(e.OnPlayerDead = 112)] = "OnPlayerDead"),
			(e[(e.OnOtherPlayerDead = 113)] = "OnOtherPlayerDead"),
			(e[(e.OnCharDeathLogicBegin = 114)] = "OnCharDeathLogicBegin"),
			(e[(e.CharRecordTeamDeath = 115)] = "CharRecordTeamDeath"),
			(e[(e.CharOnSetNewBeHit = 116)] = "CharOnSetNewBeHit"),
			(e[(e.OnBattleStateChanged = 117)] = "OnBattleStateChanged"),
			(e[(e.OnChangeWalkOrRun = 118)] = "OnChangeWalkOrRun"),
			(e[(e.CharOnRevive = 119)] = "CharOnRevive"),
			(e[(e.OnRevive = 120)] = "OnRevive"),
			(e[(e.AllRevive = 121)] = "AllRevive"),
			(e[(e.PlayerRevive = 122)] = "PlayerRevive"),
			(e[(e.CharOnFallInjure = 123)] = "CharOnFallInjure"),
			(e[(e.ChangeAiTeamLevel = 124)] = "ChangeAiTeamLevel"),
			(e[(e.AiHateAddOrRemove = 125)] = "AiHateAddOrRemove"),
			(e[(e.AiInFight = 126)] = "AiInFight"),
			(e[(e.AiHateTargetChanged = 127)] = "AiHateTargetChanged"),
			(e[(e.AiTauntAddOrRemove = 128)] = "AiTauntAddOrRemove"),
			(e[(e.AiTaskWanderForResetEnd = 129)] = "AiTaskWanderForResetEnd"),
			(e[(e.OnRunBehaviorTree = 130)] = "OnRunBehaviorTree"),
			(e[(e.OnAiEnable = 131)] = "OnAiEnable"),
			(e[(e.OnAiDisable = 132)] = "OnAiDisable"),
			(e[(e.CloseItemTips = 133)] = "CloseItemTips"),
			(e[(e.CreateRoleForwardAnimEnd = 134)] = "CreateRoleForwardAnimEnd"),
			(e[(e.CreateRoleShowInputName = 135)] = "CreateRoleShowInputName"),
			(e[(e.GuideFinish = 136)] = "GuideFinish"),
			(e[(e.GuideGroupOpening = 137)] = "GuideGroupOpening"),
			(e[(e.GuideGroupFinished = 138)] = "GuideGroupFinished"),
			(e[(e.GuideGroupBreak = 139)] = "GuideGroupBreak"),
			(e[(e.GuideGroupRest = 140)] = "GuideGroupRest"),
			(e[(e.GuideFocusNeedUiTabView = 141)] = "GuideFocusNeedUiTabView"),
			(e[(e.FinishGuideStepByEvent = 142)] = "FinishGuideStepByEvent"),
			(e[(e.GuideTouchIdInject = 143)] = "GuideTouchIdInject"),
			(e[(e.OnRefreshRoleHp = 144)] = "OnRefreshRoleHp"),
			(e[(e.BeforeLoadMap = 145)] = "BeforeLoadMap"),
			(e[(e.BeforeTravelMap = 146)] = "BeforeTravelMap"),
			(e[(e.EndTravelMap = 147)] = "EndTravelMap"),
			(e[(e.OnEnterTransitionMap = 148)] = "OnEnterTransitionMap"),
			(e[(e.AfterLoadMap = 149)] = "AfterLoadMap"),
			(e[(e.ClearWorld = 150)] = "ClearWorld"),
			(e[(e.WorldDone = 151)] = "WorldDone"),
			(e[(e.WorldDoneAndCloseLoading = 152)] = "WorldDoneAndCloseLoading"),
			(e[(e.ChangeMode = 153)] = "ChangeMode"),
			(e[(e.ChangeModeFinish = 154)] = "ChangeModeFinish"),
			(e[(e.ChangePerformanceLimitMode = 155)] = "ChangePerformanceLimitMode"),
			(e[(e.PauseGame = 156)] = "PauseGame"),
			(e[(e.OnChangeRole = 157)] = "OnChangeRole"),
			(e[(e.OnOtherChangeRole = 158)] = "OnOtherChangeRole"),
			(e[(e.OnChangeRoleCoolDownChanged = 159)] =
				"OnChangeRoleCoolDownChanged"),
			(e[(e.OnRoleGoDown = 160)] = "OnRoleGoDown"),
			(e[(e.OnRoleGoDownFinish = 161)] = "OnRoleGoDownFinish"),
			(e[(e.OnClearFollowData = 162)] = "OnClearFollowData"),
			(e[(e.InitArea = 163)] = "InitArea"),
			(e[(e.ChangeArea = 164)] = "ChangeArea"),
			(e[(e.UpdateAreaView = 165)] = "UpdateAreaView"),
			(e[(e.CreateEntity = 166)] = "CreateEntity"),
			(e[(e.CreateEntityFail = 167)] = "CreateEntityFail"),
			(e[(e.AddEntity = 168)] = "AddEntity"),
			(e[(e.FixBornLocation = 169)] = "FixBornLocation"),
			(e[(e.CharBornFinished = 170)] = "CharBornFinished"),
			(e[(e.PreloadEntityFinished = 171)] = "PreloadEntityFinished"),
			(e[(e.DelayRemoveEntityFinished = 172)] = "DelayRemoveEntityFinished"),
			(e[(e.RemoveEntity = 173)] = "RemoveEntity"),
			(e[(e.EntityOnLandedPush = 174)] = "EntityOnLandedPush"),
			(e[(e.SpawnBoss = 175)] = "SpawnBoss"),
			(e[(e.OnUpdateSceneTeam = 176)] = "OnUpdateSceneTeam"),
			(e[(e.OnRefreshItem = 177)] = "OnRefreshItem"),
			(e[(e.OnRemoveItem = 178)] = "OnRemoveItem"),
			(e[(e.OnItemDecompose = 179)] = "OnItemDecompose"),
			(e[(e.OnItemLock = 180)] = "OnItemLock"),
			(e[(e.OnGetReward = 181)] = "OnGetReward"),
			(e[(e.OnReceivePlayerVar = 182)] = "OnReceivePlayerVar"),
			(e[(e.OpenItemInfo = 183)] = "OpenItemInfo"),
			(e[(e.CloseItemInfo = 184)] = "CloseItemInfo"),
			(e[(e.BoughtItem = 185)] = "BoughtItem"),
			(e[(e.ShopUpdate = 186)] = "ShopUpdate"),
			(e[(e.OnShopInfoResponded = 187)] = "OnShopInfoResponded"),
			(e[(e.OnGoodUnlock = 188)] = "OnGoodUnlock"),
			(e[(e.SelectedMail = 189)] = "SelectedMail"),
			(e[(e.PickingAttachment = 190)] = "PickingAttachment"),
			(e[(e.DeletingMail = 191)] = "DeletingMail"),
			(e[(e.DeletingMailPassively = 192)] = "DeletingMailPassively"),
			(e[(e.AddingNewMail = 193)] = "AddingNewMail"),
			(e[(e.SwitchUnfinishedFlag = 194)] = "SwitchUnfinishedFlag"),
			(e[(e.CloseMailView = 195)] = "CloseMailView"),
			(e[(e.OnlyCloseMailContentView = 196)] = "OnlyCloseMailContentView"),
			(e[(e.BulletCreate = 197)] = "BulletCreate"),
			(e[(e.BulletDestroy = 198)] = "BulletDestroy"),
			(e[(e.BulletHit = 199)] = "BulletHit"),
			(e[(e.BulletRebound = 200)] = "BulletRebound"),
			(e[(e.BulletHitSpecialCharacter = 201)] = "BulletHitSpecialCharacter"),
			(e[(e.ScenePlayerChanged = 202)] = "ScenePlayerChanged"),
			(e[(e.ScenePlayerLocationChanged = 203)] = "ScenePlayerLocationChanged"),
			(e[(e.ScenePlayerLeaveScene = 204)] = "ScenePlayerLeaveScene"),
			(e[(e.ScenePlayerMarkItemStateChange = 205)] =
				"ScenePlayerMarkItemStateChange"),
			(e[(e.MatchTeamFlagChange = 206)] = "MatchTeamFlagChange"),
			(e[(e.LoadingViewProgressSequenceEnd = 207)] =
				"LoadingViewProgressSequenceEnd"),
			(e[(e.DestroyAllUiCameraAnimationHandles = 208)] =
				"DestroyAllUiCameraAnimationHandles"),
			(e[(e.RoleSelectionListUpdate = 209)] = "RoleSelectionListUpdate"),
			(e[(e.SelectRole = 210)] = "SelectRole"),
			(e[(e.SelectSkill = 211)] = "SelectSkill"),
			(e[(e.SelectLevelUpItemCount = 212)] = "SelectLevelUpItemCount"),
			(e[(e.SelectLevelUpItem = 213)] = "SelectLevelUpItem"),
			(e[(e.RoleInfoUpdate = 214)] = "RoleInfoUpdate"),
			(e[(e.RoleRefreshAttribute = 215)] = "RoleRefreshAttribute"),
			(e[(e.RoleSkillLevelUp = 216)] = "RoleSkillLevelUp"),
			(e[(e.RoleLevelUp = 217)] = "RoleLevelUp"),
			(e[(e.RoleLevelUpReceiveItem = 218)] = "RoleLevelUpReceiveItem"),
			(e[(e.RoleBreakUp = 219)] = "RoleBreakUp"),
			(e[(e.ActiveRole = 220)] = "ActiveRole"),
			(e[(e.RoleResonUplevel = 221)] = "RoleResonUplevel"),
			(e[(e.RoleResonActive = 222)] = "RoleResonActive"),
			(e[(e.RoleResonAnimationSuccess = 223)] = "RoleResonAnimationSuccess"),
			(e[(e.RoleResonPlayAnimation = 224)] = "RoleResonPlayAnimation"),
			(e[(e.CloseRoleView = 225)] = "CloseRoleView"),
			(e[(e.SelectedResonanceTab = 226)] = "SelectedResonanceTab"),
			(e[(e.UnSelectedResonanceTab = 227)] = "UnSelectedResonanceTab"),
			(e[(e.SwitchRootTabState = 228)] = "SwitchRootTabState"),
			(e[(e.RoleRefreshName = 229)] = "RoleRefreshName"),
			(e[(e.RoleSystemChangeRole = 230)] = "RoleSystemChangeRole"),
			(e[(e.OnSelectedRoleChanged = 231)] = "OnSelectedRoleChanged"),
			(e[(e.ChangeResonance = 232)] = "ChangeResonance"),
			(e[(e.OnRoleInternalViewEnter = 233)] = "OnRoleInternalViewEnter"),
			(e[(e.OnRoleInternalViewQuit = 234)] = "OnRoleInternalViewQuit"),
			(e[(e.AttributeComponentEvent = 235)] = "AttributeComponentEvent"),
			(e[(e.UpdateRoleLevelUpViewData = 236)] = "UpdateRoleLevelUpViewData"),
			(e[(e.UpdateRoleResonanceDetailView = 237)] =
				"UpdateRoleResonanceDetailView"),
			(e[(e.UpdateRoleSkillView = 238)] = "UpdateRoleSkillView"),
			(e[(e.UpdateRoleSkillLevelUpView = 239)] = "UpdateRoleSkillLevelUpView"),
			(e[(e.RefreshSkillTreeInfoTabView = 240)] =
				"RefreshSkillTreeInfoTabView"),
			(e[(e.SkillTreeRefresh = 241)] = "SkillTreeRefresh"),
			(e[(e.RefreshSkillTreeLeftSkillPoint = 242)] =
				"RefreshSkillTreeLeftSkillPoint"),
			(e[(e.SkillTreeReset = 243)] = "SkillTreeReset"),
			(e[(e.SkillTreeClickEmpty = 244)] = "SkillTreeClickEmpty"),
			(e[(e.SkillTreeNodeActive = 245)] = "SkillTreeNodeActive"),
			(e[(e.SkillTreeNodeLevelUp = 246)] = "SkillTreeNodeLevelUp"),
			(e[(e.UpdateSkillTreeInfoView = 247)] = "UpdateSkillTreeInfoView"),
			(e[(e.OnSkillTreeNodeToggleClick = 248)] = "OnSkillTreeNodeToggleClick"),
			(e[(e.UpdateRoleFavorData = 249)] = "UpdateRoleFavorData"),
			(e[(e.UnLockRoleFavorItem = 250)] = "UnLockRoleFavorItem"),
			(e[(e.RoleFavorExpChange = 251)] = "RoleFavorExpChange"),
			(e[(e.UpdateRoleFavorHintView = 252)] = "UpdateRoleFavorHintView"),
			(e[(e.RefreshFunctionOpenView = 253)] = "RefreshFunctionOpenView"),
			(e[(e.RoleFindFixHook = 254)] = "RoleFindFixHook"),
			(e[(e.UpdateRoleBreachView = 255)] = "UpdateRoleBreachView"),
			(e[(e.OnClickSkillLevelUp = 256)] = "OnClickSkillLevelUp"),
			(e[(e.OnClickSkillActive = 257)] = "OnClickSkillActive"),
			(e[(e.OnEnterOrExitUltraSkill = 258)] = "OnEnterOrExitUltraSkill"),
			(e[(e.WeaponLevelUp = 259)] = "WeaponLevelUp"),
			(e[(e.WeaponLevelUpReceiveItem = 260)] = "WeaponLevelUpReceiveItem"),
			(e[(e.WeaponCanGoBreach = 261)] = "WeaponCanGoBreach"),
			(e[(e.WeaponItemClick = 262)] = "WeaponItemClick"),
			(e[(e.WeaponEmptyClick = 263)] = "WeaponEmptyClick"),
			(e[(e.WeaponSortClick = 264)] = "WeaponSortClick"),
			(e[(e.WeaponMaterialPropClick = 265)] = "WeaponMaterialPropClick"),
			(e[(e.EquipWeapon = 266)] = "EquipWeapon"),
			(e[(e.ContrastWeapon = 267)] = "ContrastWeapon"),
			(e[(e.WeaponResonanceSuccess = 268)] = "WeaponResonanceSuccess"),
			(e[(e.ReConnectBegin = 269)] = "ReConnectBegin"),
			(e[(e.ReConnectFail = 270)] = "ReConnectFail"),
			(e[(e.CanNotReConnect = 271)] = "CanNotReConnect"),
			(e[(e.ReConnectSuccess = 272)] = "ReConnectSuccess"),
			(e[(e.BackLoginView = 273)] = "BackLoginView"),
			(e[(e.LogOut = 274)] = "LogOut"),
			(e[(e.ExitGamePush = 275)] = "ExitGamePush"),
			(e[(e.NetWorkMaskRpcAdd = 276)] = "NetWorkMaskRpcAdd"),
			(e[(e.NetWorkMaskRpcRemove = 277)] = "NetWorkMaskRpcRemove"),
			(e[(e.OnAimStateChanged = 278)] = "OnAimStateChanged"),
			(e[(e.OnPhantomInputDataUpdate = 279)] = "OnPhantomInputDataUpdate"),
			(e[(e.OpenDragonPoolView = 280)] = "OpenDragonPoolView"),
			(e[(e.UpdateDragonPoolView = 281)] = "UpdateDragonPoolView"),
			(e[(e.LoadMapTileFinish = 282)] = "LoadMapTileFinish"),
			(e[(e.MapOpenAreaChange = 283)] = "MapOpenAreaChange"),
			(e[(e.MapOpenAreaFullUpdate = 284)] = "MapOpenAreaFullUpdate"),
			(e[(e.WorldMapSecondaryUiClosed = 285)] = "WorldMapSecondaryUiClosed"),
			(e[(e.WorldMapSecondaryUiOpened = 286)] = "WorldMapSecondaryUiOpened"),
			(e[(e.BlackScreenFadeOnPlotToWorldMap = 287)] =
				"BlackScreenFadeOnPlotToWorldMap"),
			(e[(e.MarkMenuClickItem = 288)] = "MarkMenuClickItem"),
			(e[(e.RefreshMenuSetting = 289)] = "RefreshMenuSetting"),
			(e[(e.ModelReady = 290)] = "ModelReady"),
			(e[(e.MapReplaceMarkResponse = 291)] = "MapReplaceMarkResponse"),
			(e[(e.CreateMapMark = 292)] = "CreateMapMark"),
			(e[(e.RemoveMapMark = 293)] = "RemoveMapMark"),
			(e[(e.TrackMapMark = 294)] = "TrackMapMark"),
			(e[(e.UnlockTeleport = 295)] = "UnlockTeleport"),
			(e[(e.TrackMark = 296)] = "TrackMark"),
			(e[(e.UnTrackMark = 297)] = "UnTrackMark"),
			(e[(e.ClearTrackMark = 298)] = "ClearTrackMark"),
			(e[(e.MarkForceVisibleChanged = 299)] = "MarkForceVisibleChanged"),
			(e[(e.UpdateTrackTarget = 300)] = "UpdateTrackTarget"),
			(e[(e.SetTrackMarkOccupied = 301)] = "SetTrackMarkOccupied"),
			(e[(e.TeleportComplete = 302)] = "TeleportComplete"),
			(e[(e.TeleportStart = 303)] = "TeleportStart"),
			(e[(e.TeleportStartEntity = 304)] = "TeleportStartEntity"),
			(e[(e.OnEnterDailyQuestNotifyRange = 305)] =
				"OnEnterDailyQuestNotifyRange"),
			(e[(e.OnEnterNearbyTrackRange = 306)] = "OnEnterNearbyTrackRange"),
			(e[(e.OnLeaveNearbyTrackRange = 307)] = "OnLeaveNearbyTrackRange"),
			(e[(e.RemoveNearbyTrack = 308)] = "RemoveNearbyTrack"),
			(e[(e.UpdateNearbyTrackTag = 309)] = "UpdateNearbyTrackTag"),
			(e[(e.OnUpdateNearbyEnable = 310)] = "OnUpdateNearbyEnable"),
			(e[(e.WorldMapViewOpened = 311)] = "WorldMapViewOpened"),
			(e[(e.WorldMapPointerDown = 312)] = "WorldMapPointerDown"),
			(e[(e.WorldMapPointerDrag = 313)] = "WorldMapPointerDrag"),
			(e[(e.WorldMapJoystickMoveForward = 314)] =
				"WorldMapJoystickMoveForward"),
			(e[(e.WorldMapJoystickMoveRight = 315)] = "WorldMapJoystickMoveRight"),
			(e[(e.WorldMapJoystickFocusPlayer = 316)] =
				"WorldMapJoystickFocusPlayer"),
			(e[(e.WorldMapDragInertia = 317)] = "WorldMapDragInertia"),
			(e[(e.WorldMapPointerUp = 318)] = "WorldMapPointerUp"),
			(e[(e.WorldMapFingerExpandClose = 319)] = "WorldMapFingerExpandClose"),
			(e[(e.WorldMapWheelAxisInput = 320)] = "WorldMapWheelAxisInput"),
			(e[(e.WorldMapHandleTriggerAxisInput = 321)] =
				"WorldMapHandleTriggerAxisInput"),
			(e[(e.WorldMapScaleChanged = 322)] = "WorldMapScaleChanged"),
			(e[(e.WorldMapPositionChanged = 323)] = "WorldMapPositionChanged"),
			(e[(e.TaskRangeTrackStateChange = 324)] = "TaskRangeTrackStateChange"),
			(e[(e.RangeTrackStateChanged = 325)] = "RangeTrackStateChanged"),
			(e[(e.GetAreaProgress = 326)] = "GetAreaProgress"),
			(e[(e.PlaySoundTrackEffect = 327)] = "PlaySoundTrackEffect"),
			(e[(e.UpdatePlotSubtitle = 328)] = "UpdatePlotSubtitle"),
			(e[(e.ShowPlotSubtitleOptions = 329)] = "ShowPlotSubtitleOptions"),
			(e[(e.UpdatePlotCenterText = 330)] = "UpdatePlotCenterText"),
			(e[(e.UpdatePortraitVisible = 331)] = "UpdatePortraitVisible"),
			(e[(e.OnStartFlow = 332)] = "OnStartFlow"),
			(e[(e.PlotNetworkStart = 333)] = "PlotNetworkStart"),
			(e[(e.PlotNetworkEnd = 334)] = "PlotNetworkEnd"),
			(e[(e.PlotConfigChanged = 335)] = "PlotConfigChanged"),
			(e[(e.PlotDoingTextShow = 336)] = "PlotDoingTextShow"),
			(e[(e.ClearPlotSubtitle = 337)] = "ClearPlotSubtitle"),
			(e[(e.HidePlotUi = 338)] = "HidePlotUi"),
			(e[(e.PlotInteractViewOpen = 339)] = "PlotInteractViewOpen"),
			(e[(e.TriggerPlotInteraction = 340)] = "TriggerPlotInteraction"),
			(e[(e.TriggerBlackSequence = 341)] = "TriggerBlackSequence"),
			(e[(e.OnBlackFadeScreenStart = 342)] = "OnBlackFadeScreenStart"),
			(e[(e.OnBlackFadeScreenFinish = 343)] = "OnBlackFadeScreenFinish"),
			(e[(e.EnableSkipPlot = 344)] = "EnableSkipPlot"),
			(e[(e.PlotSequencePlay = 345)] = "PlotSequencePlay"),
			(e[(e.HangPlotViewHud = 346)] = "HangPlotViewHud"),
			(e[(e.UpdatePlotUiParam = 347)] = "UpdatePlotUiParam"),
			(e[(e.PlotViewChange = 348)] = "PlotViewChange"),
			(e[(e.PlotViewBgFadePhoto = 349)] = "PlotViewBgFadePhoto"),
			(e[(e.PlotViewBgFadeBlackScreen = 350)] = "PlotViewBgFadeBlackScreen"),
			(e[(e.PlotStartShowTalk = 351)] = "PlotStartShowTalk"),
			(e[(e.PlotEndShowTalk = 352)] = "PlotEndShowTalk"),
			(e[(e.PrewarFormationChanged = 353)] = "PrewarFormationChanged"),
			(e[(e.PrewarReadyChanged = 354)] = "PrewarReadyChanged"),
			(e[(e.DissolvePrewar = 355)] = "DissolvePrewar"),
			(e[(e.SceneStepGroupChanged = 356)] = "SceneStepGroupChanged"),
			(e[(e.InstanceStepChanged = 357)] = "InstanceStepChanged"),
			(e[(e.InstanceEnterCountChanged = 358)] = "InstanceEnterCountChanged"),
			(e[(e.InstanceEntranceUnlock = 359)] = "InstanceEntranceUnlock"),
			(e[(e.EnterInstanceDungeon = 360)] = "EnterInstanceDungeon"),
			(e[(e.LeaveInstanceDungeon = 361)] = "LeaveInstanceDungeon"),
			(e[(e.DungeonGuideChange = 362)] = "DungeonGuideChange"),
			(e[(e.LeaveInstanceDungeonConfirm = 363)] =
				"LeaveInstanceDungeonConfirm"),
			(e[(e.OpenOnlineInstanceDeath = 364)] = "OpenOnlineInstanceDeath"),
			(e[(e.OnDungeonFinish = 365)] = "OnDungeonFinish"),
			(e[(e.OnRefreshEditBattleRoleSlotData = 366)] =
				"OnRefreshEditBattleRoleSlotData"),
			(e[(e.OnRefreshEditBattleRoleReady = 367)] =
				"OnRefreshEditBattleRoleReady"),
			(e[(e.EntityVisionSkillChanged = 368)] = "EntityVisionSkillChanged"),
			(e[(e.GetAllVisionSkill = 369)] = "GetAllVisionSkill"),
			(e[(e.VisionSkillUp = 370)] = "VisionSkillUp"),
			(e[(e.ExploreVisionSkill = 371)] = "ExploreVisionSkill"),
			(e[(e.VisionMorphBegin = 372)] = "VisionMorphBegin"),
			(e[(e.VisionMorphEnd = 373)] = "VisionMorphEnd"),
			(e[(e.VisionMorphInterrupt = 374)] = "VisionMorphInterrupt"),
			(e[(e.AddExploreVisionSkill = 375)] = "AddExploreVisionSkill"),
			(e[(e.ChangeVisionSkillByTab = 376)] = "ChangeVisionSkillByTab"),
			(e[(e.ChangeVisionSimplyState = 377)] = "ChangeVisionSimplyState"),
			(e[(e.VisionSkinViewClose = 378)] = "VisionSkinViewClose"),
			(e[(e.ChangeCalabashCollectSimplyState = 379)] =
				"ChangeCalabashCollectSimplyState"),
			(e[(e.SelectedPhantom = 380)] = "SelectedPhantom"),
			(e[(e.CheckNewUnlock = 381)] = "CheckNewUnlock"),
			(e[(e.PhantomEquip = 382)] = "PhantomEquip"),
			(e[(e.PhantomEquipError = 383)] = "PhantomEquipError"),
			(e[(e.VisionFilterMonster = 384)] = "VisionFilterMonster"),
			(e[(e.OnRolePropUpdate = 385)] = "OnRolePropUpdate"),
			(e[(e.RefreshVisionIntensifyViewBackBtnState = 386)] =
				"RefreshVisionIntensifyViewBackBtnState"),
			(e[(e.OnClickVisionIntensifyItemJump = 387)] =
				"OnClickVisionIntensifyItemJump"),
			(e[(e.VisionIntensifyTabOpen = 388)] = "VisionIntensifyTabOpen"),
			(e[(e.PhantomPersonalSkillActive = 389)] = "PhantomPersonalSkillActive"),
			(e[(e.PhantomEquipWithSourceAndTargetPos = 390)] =
				"PhantomEquipWithSourceAndTargetPos"),
			(e[(e.PhantomCostInsufficient = 391)] = "PhantomCostInsufficient"),
			(e[(e.PhantomExpPreviewChange = 392)] = "PhantomExpPreviewChange"),
			(e[(e.PhantomLevelUp = 393)] = "PhantomLevelUp"),
			(e[(e.PhantomLevelUpWithId = 394)] = "PhantomLevelUpWithId"),
			(e[(e.PhantomLevelUpReceiveItem = 395)] = "PhantomLevelUpReceiveItem"),
			(e[(e.CloseSubPhantomView = 396)] = "CloseSubPhantomView"),
			(e[(e.PhantomBreach = 397)] = "PhantomBreach"),
			(e[(e.PhantomBreachPreview = 398)] = "PhantomBreachPreview"),
			(e[(e.PhantomDecomposePreview = 399)] = "PhantomDecomposePreview"),
			(e[(e.PhantomDecompose = 400)] = "PhantomDecompose"),
			(e[(e.PhantomMaxLevelSkip = 401)] = "PhantomMaxLevelSkip"),
			(e[(e.HideDelFettersText = 402)] = "HideDelFettersText"),
			(e[(e.PhantomRecommendResponse = 403)] = "PhantomRecommendResponse"),
			(e[(e.ClosePhantomSkillTips = 404)] = "ClosePhantomSkillTips"),
			(e[(e.OnPhantomItemUpdate = 405)] = "OnPhantomItemUpdate"),
			(e[(e.OnPhantomSlotUpdate = 406)] = "OnPhantomSlotUpdate"),
			(e[(e.OnVisionIdentify = 407)] = "OnVisionIdentify"),
			(e[(e.OnVisionIdentifyWithId = 408)] = "OnVisionIdentifyWithId"),
			(e[(e.OnVisionIdentifyDoAnimation = 409)] =
				"OnVisionIdentifyDoAnimation"),
			(e[(e.RefreshVisionIdentifyRedPoint = 410)] =
				"RefreshVisionIdentifyRedPoint"),
			(e[(e.RefreshVisionEquipRedPoint = 411)] = "RefreshVisionEquipRedPoint"),
			(e[(e.JumpToCalabashCollect = 412)] = "JumpToCalabashCollect"),
			(e[(e.JumpToPhantomBattleFettersTabView = 413)] =
				"JumpToPhantomBattleFettersTabView"),
			(e[(e.OnVisionSkinEquip = 414)] = "OnVisionSkinEquip"),
			(e[(e.RedDotRefreshCalabash = 415)] = "RedDotRefreshCalabash"),
			(e[(e.HasCalabashExp = 416)] = "HasCalabashExp"),
			(e[(e.CloseUpgradeCalabashView = 417)] = "CloseUpgradeCalabashView"),
			(e[(e.CloseCalabashExpAddView = 418)] = "CloseCalabashExpAddView"),
			(e[(e.ShowCalabashControllerView = 419)] = "ShowCalabashControllerView"),
			(e[(e.GetCalabashRewardSuccess = 420)] = "GetCalabashRewardSuccess"),
			(e[(e.ShowCalabashUnlockItemTips = 421)] = "ShowCalabashUnlockItemTips"),
			(e[(e.GetCalabashReward = 422)] = "GetCalabashReward"),
			(e[(e.CalabashLevelUpdate = 423)] = "CalabashLevelUpdate"),
			(e[(e.CalabashEnterInternalView = 424)] = "CalabashEnterInternalView"),
			(e[(e.CalabashQuitInternalView = 425)] = "CalabashQuitInternalView"),
			(e[(e.OnVisionRecoveryResult = 426)] = "OnVisionRecoveryResult"),
			(e[(e.OnRefreshCalabashTabShowState = 427)] =
				"OnRefreshCalabashTabShowState"),
			(e[(e.OnSetPartStateVisible = 428)] = "OnSetPartStateVisible"),
			(e[(e.OnPlatformChanged = 429)] = "OnPlatformChanged"),
			(e[(e.ShowHUD = 430)] = "ShowHUD"),
			(e[(e.HideHUD = 431)] = "HideHUD"),
			(e[(e.OnGetPlayerBasicInfo = 432)] = "OnGetPlayerBasicInfo"),
			(e[(e.OnLoadedNewFlagConfig = 433)] = "OnLoadedNewFlagConfig"),
			(e[(e.OnPlayerLevelChanged = 434)] = "OnPlayerLevelChanged"),
			(e[(e.OnPlayerExpChanged = 435)] = "OnPlayerExpChanged"),
			(e[(e.OnLevelUpLevelRefresh = 436)] = "OnLevelUpLevelRefresh"),
			(e[(e.OnLevelUpExpRefresh = 437)] = "OnLevelUpExpRefresh"),
			(e[(e.OnLevelUpShowLevelOnly = 438)] = "OnLevelUpShowLevelOnly"),
			(e[(e.SelectFilterMultiple = 439)] = "SelectFilterMultiple"),
			(e[(e.SelectFilterSingle = 440)] = "SelectFilterSingle"),
			(e[(e.SelectSort = 441)] = "SelectSort"),
			(e[(e.OnSceneItemHit = 442)] = "OnSceneItemHit"),
			(e[(e.OnSceneItemHitByHitData = 443)] = "OnSceneItemHitByHitData"),
			(e[(e.OnSceneItemEntityHit = 444)] = "OnSceneItemEntityHit"),
			(e[(e.OnSceneItemEntityHitAlways = 445)] = "OnSceneItemEntityHitAlways"),
			(e[(e.OnAnySceneItemEntityHit = 446)] = "OnAnySceneItemEntityHit"),
			(e[(e.OnAnySceneItemDurabilityChange = 447)] =
				"OnAnySceneItemDurabilityChange"),
			(e[(e.OnSceneItemDurabilityChange = 448)] =
				"OnSceneItemDurabilityChange"),
			(e[(e.UpdateSceneItemState = 449)] = "UpdateSceneItemState"),
			(e[(e.OnSceneItemDestroy = 450)] = "OnSceneItemDestroy"),
			(e[(e.OnSceneItemStateChange = 451)] = "OnSceneItemStateChange"),
			(e[(e.OnSceneItemStatePreChange = 452)] = "OnSceneItemStatePreChange"),
			(e[(e.OnSceneItemStatePrechangeInSequence = 453)] =
				"OnSceneItemStatePrechangeInSequence"),
			(e[(e.OnEntityConcealedChange = 454)] = "OnEntityConcealedChange"),
			(e[(e.OnTimeTrackControlUpdate = 455)] = "OnTimeTrackControlUpdate"),
			(e[(e.OnSceneInteractionLoadCompleted = 456)] =
				"OnSceneInteractionLoadCompleted"),
			(e[(e.OnSceneItemVisionCaptureAdd = 457)] =
				"OnSceneItemVisionCaptureAdd"),
			(e[(e.OnSceneItemVisionCaptureRemove = 458)] =
				"OnSceneItemVisionCaptureRemove"),
			(e[(e.OnInputDistributeTagChanged = 459)] =
				"OnInputDistributeTagChanged"),
			(e[(e.ForceReleaseInput = 460)] = "ForceReleaseInput"),
			(e[(e.OnFormationPlayLevelUp = 461)] = "OnFormationPlayLevelUp"),
			(e[(e.OnFormationPlayRevive = 462)] = "OnFormationPlayRevive"),
			(e[(e.OnItemUse = 463)] = "OnItemUse"),
			(e[(e.OnSpecialItemUse = 464)] = "OnSpecialItemUse"),
			(e[(e.OnGameplayTagChanged = 465)] = "OnGameplayTagChanged"),
			(e[(e.OnLevelTagChanged = 466)] = "OnLevelTagChanged"),
			(e[(e.OnGlobalGameplayTagChanged = 467)] = "OnGlobalGameplayTagChanged"),
			(e[(e.LevelEventTriggerExit = 468)] = "LevelEventTriggerExit"),
			(e[(e.OnLevelPlayStateChange = 469)] = "OnLevelPlayStateChange"),
			(e[(e.TodTimeChange = 470)] = "TodTimeChange"),
			(e[(e.DayStateChange = 471)] = "DayStateChange"),
			(e[(e.CrossDay = 472)] = "CrossDay"),
			(e[(e.ClickTimeItem = 473)] = "ClickTimeItem"),
			(e[(e.OnSelectTimeItem = 474)] = "OnSelectTimeItem"),
			(e[(e.AdjustTime = 475)] = "AdjustTime"),
			(e[(e.AdjustTimeInAnim = 476)] = "AdjustTimeInAnim"),
			(e[(e.PowerShopReady = 477)] = "PowerShopReady"),
			(e[(e.OnPowerChanged = 478)] = "OnPowerChanged"),
			(e[(e.OnPowerCountDownChanged = 479)] = "OnPowerCountDownChanged"),
			(e[(e.OnGamePlayCdChanged = 480)] = "OnGamePlayCdChanged"),
			(e[(e.InsertFloatTips = 481)] = "InsertFloatTips"),
			(e[(e.OriginWorldLevelUp = 482)] = "OriginWorldLevelUp"),
			(e[(e.CurWorldLevelChange = 483)] = "CurWorldLevelChange"),
			(e[(e.WorldLevelUpViewRefresh = 484)] = "WorldLevelUpViewRefresh"),
			(e[(e.OnShowMouseCursor = 485)] = "OnShowMouseCursor"),
			(e[(e.RefreshCursor = 486)] = "RefreshCursor"),
			(e[(e.InputDistribute = 487)] = "InputDistribute"),
			(e[(e.OnRefreshJoinTeamRole = 488)] = "OnRefreshJoinTeamRole"),
			(e[(e.LoadLguiEventSystemActor = 489)] = "LoadLguiEventSystemActor"),
			(e[(e.DestroyLguiEventSystemActor = 490)] =
				"DestroyLguiEventSystemActor"),
			(e[(e.OnUseBuffItem = 491)] = "OnUseBuffItem"),
			(e[(e.UpdateQuestDetails = 492)] = "UpdateQuestDetails"),
			(e[(e.UpdateRoleQuestDetails = 493)] = "UpdateRoleQuestDetails"),
			(e[(e.QuestUpdateInfoAdd = 494)] = "QuestUpdateInfoAdd"),
			(e[(e.AddInteractOptionByAction = 495)] = "AddInteractOptionByAction"),
			(e[(e.RemoveInteractOptionByAction = 496)] =
				"RemoveInteractOptionByAction"),
			(e[(e.OnQuestStateChange = 497)] = "OnQuestStateChange"),
			(e[(e.OnQuestRedDotStateChange = 498)] = "OnQuestRedDotStateChange"),
			(e[(e.OnQuestFinishProtocolEnd = 499)] = "OnQuestFinishProtocolEnd"),
			(e[(e.OnRoleQuestAccept = 500)] = "OnRoleQuestAccept"),
			(e[(e.OnRoleQuestPointChange = 501)] = "OnRoleQuestPointChange"),
			(e[(e.OnRoleQuestNewUnlock = 502)] = "OnRoleQuestNewUnlock"),
			(e[(e.OnAddNewQuest = 503)] = "OnAddNewQuest"),
			(e[(e.OnNavigationQuest = 504)] = "OnNavigationQuest"),
			(e[(e.ActivityQuestCountdownEnd = 505)] = "ActivityQuestCountdownEnd"),
			(e[(e.GeneralLogicTreeWakeUp = 506)] = "GeneralLogicTreeWakeUp"),
			(e[(e.OnLogicTreeNodeStatusChange = 507)] =
				"OnLogicTreeNodeStatusChange"),
			(e[(e.OnLogicTreeChildQuestNodeStatusChange = 508)] =
				"OnLogicTreeChildQuestNodeStatusChange"),
			(e[(e.OnLogicTreeNodeProgressChange = 509)] =
				"OnLogicTreeNodeProgressChange"),
			(e[(e.GeneralLogicTreeTimerInfoChanged = 510)] =
				"GeneralLogicTreeTimerInfoChanged"),
			(e[(e.OnLogicTreeTrackUpdate = 511)] = "OnLogicTreeTrackUpdate"),
			(e[(e.CurTrackQuestUnTrackedCheck = 512)] =
				"CurTrackQuestUnTrackedCheck"),
			(e[(e.OnLogicTreeTimerTick = 513)] = "OnLogicTreeTimerTick"),
			(e[(e.GeneralLogicTreeStartShowTrackText = 514)] =
				"GeneralLogicTreeStartShowTrackText"),
			(e[(e.GeneralLogicTreeUpdateShowTrackText = 515)] =
				"GeneralLogicTreeUpdateShowTrackText"),
			(e[(e.GeneralLogicTreeEndShowTrackText = 516)] =
				"GeneralLogicTreeEndShowTrackText"),
			(e[(e.GeneralLogicTreeRemove = 517)] = "GeneralLogicTreeRemove"),
			(e[(e.GeneralLogicTreeSuspend = 518)] = "GeneralLogicTreeSuspend"),
			(e[(e.GeneralLogicTreeCancelSuspend = 519)] =
				"GeneralLogicTreeCancelSuspend"),
			(e[(e.GeneralLogicTreeRemovePrepareRollbackNode = 520)] =
				"GeneralLogicTreeRemovePrepareRollbackNode"),
			(e[(e.GeneralLogicTreeRollbackWaitingUpdate = 521)] =
				"GeneralLogicTreeRollbackWaitingUpdate"),
			(e[(e.GeneralLogicTreeEntityInteractFinished = 522)] =
				"GeneralLogicTreeEntityInteractFinished"),
			(e[(e.GeneralLogicTreeEntityKilled = 523)] =
				"GeneralLogicTreeEntityKilled"),
			(e[(e.GeneralLogicTreeAddTag = 524)] = "GeneralLogicTreeAddTag"),
			(e[(e.GeneralLogicTreeRemoveTag = 525)] = "GeneralLogicTreeRemoveTag"),
			(e[(e.GeneralLogicTreeViewForceRefresh = 526)] =
				"GeneralLogicTreeViewForceRefresh"),
			(e[(e.GeneralLogicTreeApplyExpressionOccupation = 527)] =
				"GeneralLogicTreeApplyExpressionOccupation"),
			(e[(e.GeneralLogicTreeReleaseExpressionOccupation = 528)] =
				"GeneralLogicTreeReleaseExpressionOccupation"),
			(e[(e.MissionPanelProcessEnd = 529)] = "MissionPanelProcessEnd"),
			(e[(e.QuestUpdateTipsClickTrack = 530)] = "QuestUpdateTipsClickTrack"),
			(e[(e.MissionPanelOut = 531)] = "MissionPanelOut"),
			(e[(e.MissionUpdate = 532)] = "MissionUpdate"),
			(e[(e.MissionUpdateAnimEnd = 533)] = "MissionUpdateAnimEnd"),
			(e[(e.MissionPanelStepTitleAnimStart = 534)] =
				"MissionPanelStepTitleAnimStart"),
			(e[(e.MissionPanelStepTitleAnimEnd = 535)] =
				"MissionPanelStepTitleAnimEnd"),
			(e[(e.ParkourFinished = 536)] = "ParkourFinished"),
			(e[(e.OnOpenDebugCommand = 537)] = "OnOpenDebugCommand"),
			(e[(e.ResetToBattleView = 538)] = "ResetToBattleView"),
			(e[(e.ResetModuleByResetToBattleView = 539)] =
				"ResetModuleByResetToBattleView"),
			(e[(e.ExitNormalQueueState = 540)] = "ExitNormalQueueState"),
			(e[(e.OnStartLoadingState = 541)] = "OnStartLoadingState"),
			(e[(e.OnFinishLoadingState = 542)] = "OnFinishLoadingState"),
			(e[(e.OnOpenLoadingView = 543)] = "OnOpenLoadingView"),
			(e[(e.OnCloseLoadingView = 544)] = "OnCloseLoadingView"),
			(e[(e.OnLoadingNetDataDone = 545)] = "OnLoadingNetDataDone"),
			(e[(e.PlayUiComponentCloseTween = 546)] = "PlayUiComponentCloseTween"),
			(e[(e.ChangeUiComponentMarkId = 547)] = "ChangeUiComponentMarkId"),
			(e[(e.ChangeConfigValue = 548)] = "ChangeConfigValue"),
			(e[(e.OnMenuDataEnableChanged = 549)] = "OnMenuDataEnableChanged"),
			(e[(e.RestartFlag = 550)] = "RestartFlag"),
			(e[(e.SettingFrameRateChanged = 551)] = "SettingFrameRateChanged"),
			(e[(e.TextLanguageChange = 552)] = "TextLanguageChange"),
			(e[(e.ConfigLoadChange = 553)] = "ConfigLoadChange"),
			(e[(e.SneakResult = 554)] = "SneakResult"),
			(e[(e.SneakMonsterStart = 555)] = "SneakMonsterStart"),
			(e[(e.SneakMonsterStop = 556)] = "SneakMonsterStop"),
			(e[(e.ChannelReset = 557)] = "ChannelReset"),
			(e[(e.OnShareResult = 558)] = "OnShareResult"),
			(e[(e.OnFirstShare = 559)] = "OnFirstShare"),
			(e[(e.ShowVideo = 560)] = "ShowVideo"),
			(e[(e.VideoStart = 561)] = "VideoStart"),
			(e[(e.PlayVideo = 562)] = "PlayVideo"),
			(e[(e.ScanTrackedStart = 563)] = "ScanTrackedStart"),
			(e[(e.ScanTrackedEnd = 564)] = "ScanTrackedEnd"),
			(e[(e.OnScanStart = 565)] = "OnScanStart"),
			(e[(e.RedDotStart = 566)] = "RedDotStart"),
			(e[(e.RedDotRefreshItemData = 567)] = "RedDotRefreshItemData"),
			(e[(e.RedDotRoleConfigList = 568)] = "RedDotRoleConfigList"),
			(e[(e.RedDotRefreshPhantomEquip = 569)] = "RedDotRefreshPhantomEquip"),
			(e[(e.RedDotRoleChange = 570)] = "RedDotRoleChange"),
			(e[(e.RedDotUnLockPhantom = 571)] = "RedDotUnLockPhantom"),
			(e[(e.RedDotNewTutorial = 572)] = "RedDotNewTutorial"),
			(e[(e.RedDotNewTutorialType = 573)] = "RedDotNewTutorialType"),
			(e[(e.RedDotAdventureManualUpdate = 574)] =
				"RedDotAdventureManualUpdate"),
			(e[(e.RedDotSilentFirstAward = 575)] = "RedDotSilentFirstAward"),
			(e[(e.RedDotSilentFirstAwardCategory = 576)] =
				"RedDotSilentFirstAwardCategory"),
			(e[(e.RedDotSilentFirstAwardResult = 577)] =
				"RedDotSilentFirstAwardResult"),
			(e[(e.RedDotCreateRole = 578)] = "RedDotCreateRole"),
			(e[(e.SilentTipsRefresh = 579)] = "SilentTipsRefresh"),
			(e[(e.OnRefreshElementBallData = 580)] = "OnRefreshElementBallData"),
			(e[(e.ShootTargetStateChanged = 581)] = "ShootTargetStateChanged"),
			(e[(e.InteractNavigation = 582)] = "InteractNavigation"),
			(e[(e.InteractionViewUpdate = 583)] = "InteractionViewUpdate"),
			(e[(e.HideInteractView = 584)] = "HideInteractView"),
			(e[(e.SceneItemInteractionEvent = 585)] = "SceneItemInteractionEvent"),
			(e[(e.OnFunctionOpenSet = 586)] = "OnFunctionOpenSet"),
			(e[(e.OnFunctionOpenUpdate = 587)] = "OnFunctionOpenUpdate"),
			(e[(e.OnFunctionOpenUpdateNotify = 588)] = "OnFunctionOpenUpdateNotify"),
			(e[(e.OnConcertoResponseOpen = 589)] = "OnConcertoResponseOpen"),
			(e[(e.OnFirstOpenShopChanged = 590)] = "OnFirstOpenShopChanged"),
			(e[(e.OnSetHeadStateVisible = 591)] = "OnSetHeadStateVisible"),
			(e[(e.OnSetBossStateVisible = 592)] = "OnSetBossStateVisible"),
			(e[(e.SdkKick = 593)] = "SdkKick"),
			(e[(e.SdkPostWebViewRedPointRefresh = 594)] =
				"SdkPostWebViewRedPointRefresh"),
			(e[(e.SdkCustomerRedPointRefresh = 595)] = "SdkCustomerRedPointRefresh"),
			(e[(e.UpdateFriendViewShow = 596)] = "UpdateFriendViewShow"),
			(e[(e.UpdateRecentlyTeamDataEvent = 597)] =
				"UpdateRecentlyTeamDataEvent"),
			(e[(e.OnRemoveFriend = 598)] = "OnRemoveFriend"),
			(e[(e.FriendApplicationListUpdate = 599)] =
				"FriendApplicationListUpdate"),
			(e[(e.UpdateBlackListShow = 600)] = "UpdateBlackListShow"),
			(e[(e.SearchPlayerInfo = 601)] = "SearchPlayerInfo"),
			(e[(e.FriendRemarkLengthLimit = 602)] = "FriendRemarkLengthLimit"),
			(e[(e.FriendRemarkContainsDirtyWord = 603)] =
				"FriendRemarkContainsDirtyWord"),
			(e[(e.RefreshFriendApplicationRedDot = 604)] =
				"RefreshFriendApplicationRedDot"),
			(e[(e.LoadTestFriendsByGm = 605)] = "LoadTestFriendsByGm"),
			(e[(e.ApplicationHandled = 606)] = "ApplicationHandled"),
			(e[(e.ApplicationSent = 607)] = "ApplicationSent"),
			(e[(e.OnGetFriendInitData = 608)] = "OnGetFriendInitData"),
			(e[(e.OnNavigationViewUiCreated = 609)] = "OnNavigationViewUiCreated"),
			(e[(e.OnUiNavigationViewSetActive = 610)] =
				"OnUiNavigationViewSetActive"),
			(e[(e.InputControllerChange = 611)] = "InputControllerChange"),
			(e[(e.PointerInputTypeChange = 612)] = "PointerInputTypeChange"),
			(e[(e.ChangeScrollBarPosition = 613)] = "ChangeScrollBarPosition"),
			(e[(e.OnSelectChatFriend = 614)] = "OnSelectChatFriend"),
			(e[(e.OnCreatePrivateChatRoom = 615)] = "OnCreatePrivateChatRoom"),
			(e[(e.OnJoinChatRoom = 616)] = "OnJoinChatRoom"),
			(e[(e.OnAddChatContent = 617)] = "OnAddChatContent"),
			(e[(e.OnRefreshChatRedDot = 618)] = "OnRefreshChatRedDot"),
			(e[(e.OnRefreshChatRoomRedDot = 619)] = "OnRefreshChatRoomRedDot"),
			(e[(e.OnAddHistoryChatContentCompleted = 620)] =
				"OnAddHistoryChatContentCompleted"),
			(e[(e.OnPushChatRowData = 621)] = "OnPushChatRowData"),
			(e[(e.OnPopChatRowData = 622)] = "OnPopChatRowData"),
			(e[(e.OnRefreshChatRowData = 623)] = "OnRefreshChatRowData"),
			(e[(e.OnAddMutePlayer = 624)] = "OnAddMutePlayer"),
			(e[(e.OnRemoveMutePlayer = 625)] = "OnRemoveMutePlayer"),
			(e[(e.OnRemovePrivateChatRoom = 626)] = "OnRemovePrivateChatRoom"),
			(e[(e.OnClosePrivateChatRoom = 627)] = "OnClosePrivateChatRoom"),
			(e[(e.OnOpenChatRoom = 628)] = "OnOpenChatRoom"),
			(e[(e.OnSelectExpression = 629)] = "OnSelectExpression"),
			(e[(e.OnServerAttributeChange = 630)] = "OnServerAttributeChange"),
			(e[(e.OnPayItemSuccess = 631)] = "OnPayItemSuccess"),
			(e[(e.RefreshPayItemList = 632)] = "RefreshPayItemList"),
			(e[(e.RefreshPayGiftList = 633)] = "RefreshPayGiftList"),
			(e[(e.OnPlayerCurrencyChange = 634)] = "OnPlayerCurrencyChange"),
			(e[(e.OnRefreshPermissionsSetting = 635)] =
				"OnRefreshPermissionsSetting"),
			(e[(e.OnRefreshApply = 636)] = "OnRefreshApply"),
			(e[(e.OnSearchWorld = 637)] = "OnSearchWorld"),
			(e[(e.OnRefreshWorldList = 638)] = "OnRefreshWorldList"),
			(e[(e.OnRefreshOnlineTeamList = 639)] = "OnRefreshOnlineTeamList"),
			(e[(e.OnWorldTeamPlayerInfoChanged = 640)] =
				"OnWorldTeamPlayerInfoChanged"),
			(e[(e.OnRefreshPlayerPing = 641)] = "OnRefreshPlayerPing"),
			(e[(e.OnRefreshPlayerUiState = 642)] = "OnRefreshPlayerUiState"),
			(e[(e.SwitchPayShopTabItem = 643)] = "SwitchPayShopTabItem"),
			(e[(e.PayShopGoodsBuy = 644)] = "PayShopGoodsBuy"),
			(e[(e.GoodsRefreshDiscountTime = 645)] = "GoodsRefreshDiscountTime"),
			(e[(e.SwitchPayShopView = 646)] = "SwitchPayShopView"),
			(e[(e.RefreshPayShop = 647)] = "RefreshPayShop"),
			(e[(e.RefreshAllPayShop = 648)] = "RefreshAllPayShop"),
			(e[(e.RefreshGoods = 649)] = "RefreshGoods"),
			(e[(e.ShopVersionCodeChange = 650)] = "ShopVersionCodeChange"),
			(e[(e.GoodsSoldOut = 651)] = "GoodsSoldOut"),
			(e[(e.RefreshGoodsList = 652)] = "RefreshGoodsList"),
			(e[(e.UnLockGoods = 653)] = "UnLockGoods"),
			(e[(e.DiscountShopTimerRefresh = 654)] = "DiscountShopTimerRefresh"),
			(e[(e.OnOpenGachaChanged = 655)] = "OnOpenGachaChanged"),
			(e[(e.RefreshGachaMainView = 656)] = "RefreshGachaMainView"),
			(e[(e.GachaPoolSelectResponse = 657)] = "GachaPoolSelectResponse"),
			(e[(e.GachaResponse = 658)] = "GachaResponse"),
			(e[(e.GachaHistoryResponse = 659)] = "GachaHistoryResponse"),
			(e[(e.CloseGachaSceneView = 660)] = "CloseGachaSceneView"),
			(e[(e.EndGachaScene = 661)] = "EndGachaScene"),
			(e[(e.GachaClick = 662)] = "GachaClick"),
			(e[(e.GachaSelectionViewRefresh = 663)] = "GachaSelectionViewRefresh"),
			(e[(e.AfterCloseGachaScene = 664)] = "AfterCloseGachaScene"),
			(e[(e.PlaySequenceEventByStringParam = 665)] =
				"PlaySequenceEventByStringParam"),
			(e[(e.GachaInteractFinish = 666)] = "GachaInteractFinish"),
			(e[(e.ItemExChangeResponse = 667)] = "ItemExChangeResponse"),
			(e[(e.ItemHintVisibilityChange = 668)] = "ItemHintVisibilityChange"),
			(e[(e.ShowAnimalsHeadInfo = 669)] = "ShowAnimalsHeadInfo"),
			(e[(e.OnAnimalDying = 670)] = "OnAnimalDying"),
			(e[(e.OnSkillButtonDataRefresh = 671)] = "OnSkillButtonDataRefresh"),
			(e[(e.OnSkillButtonDataClear = 672)] = "OnSkillButtonDataClear"),
			(e[(e.OnSkillButtonIndexRefresh = 673)] = "OnSkillButtonIndexRefresh"),
			(e[(e.OnSkillButtonEnableRefresh = 674)] = "OnSkillButtonEnableRefresh"),
			(e[(e.OnSkillButtonVisibleRefresh = 675)] =
				"OnSkillButtonVisibleRefresh"),
			(e[(e.OnSkillButtonSkillIdRefresh = 676)] =
				"OnSkillButtonSkillIdRefresh"),
			(e[(e.OnSkillButtonDynamicEffectRefresh = 677)] =
				"OnSkillButtonDynamicEffectRefresh"),
			(e[(e.OnSkillButtonCdRefresh = 678)] = "OnSkillButtonCdRefresh"),
			(e[(e.OnSkillButtonAttributeRefresh = 679)] =
				"OnSkillButtonAttributeRefresh"),
			(e[(e.OnSkillButtonIconPathRefresh = 680)] =
				"OnSkillButtonIconPathRefresh"),
			(e[(e.OnBehaviorButtonVisibleRefresh = 681)] =
				"OnBehaviorButtonVisibleRefresh"),
			(e[(e.OnInputChangeForCond = 682)] = "OnInputChangeForCond"),
			(e[(e.OnGetNewItem = 683)] = "OnGetNewItem"),
			(e[(e.OnElementFusion = 684)] = "OnElementFusion"),
			(e[(e.OnChangeSelectedExploreId = 685)] = "OnChangeSelectedExploreId"),
			(e[(e.OnRouletteViewVisibleChanged = 686)] =
				"OnRouletteViewVisibleChanged"),
			(e[(e.OnRouletteItemSelect = 687)] = "OnRouletteItemSelect"),
			(e[(e.OnRouletteItemUnlock = 688)] = "OnRouletteItemUnlock"),
			(e[(e.OnRouletteSaveDataChange = 689)] = "OnRouletteSaveDataChange"),
			(e[(e.OnAggroAdd = 690)] = "OnAggroAdd"),
			(e[(e.OnAggroRemoved = 691)] = "OnAggroRemoved"),
			(e[(e.OnBossFight = 692)] = "OnBossFight"),
			(e[(e.OnSkillTagChanged = 693)] = "OnSkillTagChanged"),
			(e[(e.OnMatchingChange = 694)] = "OnMatchingChange"),
			(e[(e.OnMatchingBegin = 695)] = "OnMatchingBegin"),
			(e[(e.OnEnterTeam = 696)] = "OnEnterTeam"),
			(e[(e.OnLeaveTeam = 697)] = "OnLeaveTeam"),
			(e[(e.OnEnterOnlineWorld = 698)] = "OnEnterOnlineWorld"),
			(e[(e.OnLeaveOnlineWorld = 699)] = "OnLeaveOnlineWorld"),
			(e[(e.OnlineDisableStateChange = 700)] = "OnlineDisableStateChange"),
			(e[(e.PlayerChallengeStateChange = 701)] = "PlayerChallengeStateChange"),
			(e[(e.OnTriggerVolumeExit = 702)] = "OnTriggerVolumeExit"),
			(e[(e.RefreshAcquireView = 703)] = "RefreshAcquireView"),
			(e[(e.OnResonanceMaterialChange = 704)] = "OnResonanceMaterialChange"),
			(e[(e.OnAddMaterialController = 705)] = "OnAddMaterialController"),
			(e[(e.OnRemoveMaterialController = 706)] = "OnRemoveMaterialController"),
			(e[(e.OnAddMaterialControllerGroup = 707)] =
				"OnAddMaterialControllerGroup"),
			(e[(e.OnRemoveMaterialControllerGroup = 708)] =
				"OnRemoveMaterialControllerGroup"),
			(e[(e.WeatherChange = 709)] = "WeatherChange"),
			(e[(e.OnManipulateSwitchToNewTarget = 710)] =
				"OnManipulateSwitchToNewTarget"),
			(e[(e.OnManipulateStartChanting = 711)] = "OnManipulateStartChanting"),
			(e[(e.OnManipulateCancelChanting = 712)] = "OnManipulateCancelChanting"),
			(e[(e.OnManipulateCompleteChanting = 713)] =
				"OnManipulateCompleteChanting"),
			(e[(e.HiddenManipulateUI = 714)] = "HiddenManipulateUI"),
			(e[(e.ManipulateStartLockCastTarget = 715)] =
				"ManipulateStartLockCastTarget"),
			(e[(e.ManipulateEndLockCastTarget = 716)] =
				"ManipulateEndLockCastTarget"),
			(e[(e.OnManipulatableSceneItemPosInFoundation = 717)] =
				"OnManipulatableSceneItemPosInFoundation"),
			(e[(e.AddSubCameraTag = 718)] = "AddSubCameraTag"),
			(e[(e.RemoveSubCameraTag = 719)] = "RemoveSubCameraTag"),
			(e[(e.AddExtraHoldingTags = 720)] = "AddExtraHoldingTags"),
			(e[(e.RemoveExtraHoldingTags = 721)] = "RemoveExtraHoldingTags"),
			(e[(e.HideJigsawBaseHint = 722)] = "HideJigsawBaseHint"),
			(e[(e.OnModifyJigsawItemPutIndex = 723)] = "OnModifyJigsawItemPutIndex"),
			(e[(e.OnManipulatableItemStateModified = 724)] =
				"OnManipulatableItemStateModified"),
			(e[(e.OnManipulatedItemPosReset = 725)] = "OnManipulatedItemPosReset"),
			(e[(e.SetCameraAimVisible = 726)] = "SetCameraAimVisible"),
			(e[(e.ClickDisplayItem = 727)] = "ClickDisplayItem"),
			(e[(e.OnSelectItemAdd = 728)] = "OnSelectItemAdd"),
			(e[(e.DetectSuccess = 729)] = "DetectSuccess"),
			(e[(e.AdventureTaskStateChange = 730)] = "AdventureTaskStateChange"),
			(e[(e.ChapterRewardReceived = 731)] = "ChapterRewardReceived"),
			(e[(e.SilentRewardReceived = 732)] = "SilentRewardReceived"),
			(e[(e.AdventureHelpBtn = 733)] = "AdventureHelpBtn"),
			(e[(e.NewSoundAreaRefreshReward = 734)] = "NewSoundAreaRefreshReward"),
			(e[(e.DailyActivityTaskUpdate = 735)] = "DailyActivityTaskUpdate"),
			(e[(e.DailyActivityRefresh = 736)] = "DailyActivityRefresh"),
			(e[(e.DailyActivityValueChange = 737)] = "DailyActivityValueChange"),
			(e[(e.DailyActivityRewardTake = 738)] = "DailyActivityRewardTake"),
			(e[(e.RefreshActivityRewardPopUp = 739)] = "RefreshActivityRewardPopUp"),
			(e[(e.DailyActivityCountDownUpdate = 740)] =
				"DailyActivityCountDownUpdate"),
			(e[(e.DailyUpdateNotify = 741)] = "DailyUpdateNotify"),
			(e[(e.DailyActivityStateNotify = 742)] = "DailyActivityStateNotify"),
			(e[(e.DailyTaskAreaItemClick = 743)] = "DailyTaskAreaItemClick"),
			(e[(e.DailyTaskInfluenceItemClick = 744)] =
				"DailyTaskInfluenceItemClick"),
			(e[(e.DailyTaskUnlockAreaChange = 745)] = "DailyTaskUnlockAreaChange"),
			(e[(e.DailyTaskStateChange = 746)] = "DailyTaskStateChange"),
			(e[(e.DailyTaskChange = 747)] = "DailyTaskChange"),
			(e[(e.DailyTaskTendencyChange = 748)] = "DailyTaskTendencyChange"),
			(e[(e.OnAddCommonItem = 749)] = "OnAddCommonItem"),
			(e[(e.OnAddCommonItemList = 750)] = "OnAddCommonItemList"),
			(e[(e.OnAddCommonItemNotify = 751)] = "OnAddCommonItemNotify"),
			(e[(e.OnResponseCommonItem = 752)] = "OnResponseCommonItem"),
			(e[(e.OnRemoveCommonItem = 753)] = "OnRemoveCommonItem"),
			(e[(e.OnCommonItemCountRefresh = 754)] = "OnCommonItemCountRefresh"),
			(e[(e.OnCommonItemCountAnyChange = 755)] = "OnCommonItemCountAnyChange"),
			(e[(e.OnAddWeaponItem = 756)] = "OnAddWeaponItem"),
			(e[(e.OnAddWeaponItemList = 757)] = "OnAddWeaponItemList"),
			(e[(e.OnResponseWeaponItem = 758)] = "OnResponseWeaponItem"),
			(e[(e.OnResponseWeaponAll = 759)] = "OnResponseWeaponAll"),
			(e[(e.OnRemoveWeaponItem = 760)] = "OnRemoveWeaponItem"),
			(e[(e.OnWeaponFunctionValueRefresh = 761)] =
				"OnWeaponFunctionValueRefresh"),
			(e[(e.OnAddPhantomItem = 762)] = "OnAddPhantomItem"),
			(e[(e.OnAddPhantomItemList = 763)] = "OnAddPhantomItemList"),
			(e[(e.OnResponsePhantomItem = 764)] = "OnResponsePhantomItem"),
			(e[(e.OnEquipPhantomItem = 765)] = "OnEquipPhantomItem"),
			(e[(e.OnRemovePhantomItem = 766)] = "OnRemovePhantomItem"),
			(e[(e.OnPhantomFunctionValueRefresh = 767)] =
				"OnPhantomFunctionValueRefresh"),
			(e[(e.OnAddFavorItem = 768)] = "OnAddFavorItem"),
			(e[(e.NotifyInvalidItem = 769)] = "NotifyInvalidItem"),
			(e[(e.EnterPresentationInitRange = 770)] = "EnterPresentationInitRange"),
			(e[(e.EnterLogicRange = 771)] = "EnterLogicRange"),
			(e[(e.LeaveLogicRange = 772)] = "LeaveLogicRange"),
			(e[(e.PlayerSenseTargetEnter = 773)] = "PlayerSenseTargetEnter"),
			(e[(e.PlayerSenseTargetLeave = 774)] = "PlayerSenseTargetLeave"),
			(e[(e.OnAiSenseEntityEnter = 775)] = "OnAiSenseEntityEnter"),
			(e[(e.OnAiSenseEntityLeave = 776)] = "OnAiSenseEntityLeave"),
			(e[(e.OnInteractStateChange = 777)] = "OnInteractStateChange"),
			(e[(e.OnGuideRangeEnter = 778)] = "OnGuideRangeEnter"),
			(e[(e.SwitchCookType = 779)] = "SwitchCookType"),
			(e[(e.UpdateFormula = 780)] = "UpdateFormula"),
			(e[(e.UpdateCookerInfo = 781)] = "UpdateCookerInfo"),
			(e[(e.UpgradeCookerLevel = 782)] = "UpgradeCookerLevel"),
			(e[(e.GetCookData = 783)] = "GetCookData"),
			(e[(e.OpenProcessedStudy = 784)] = "OpenProcessedStudy"),
			(e[(e.CloseProcessedStudy = 785)] = "CloseProcessedStudy"),
			(e[(e.OpenCook = 786)] = "OpenCook"),
			(e[(e.OpenCookLevel = 787)] = "OpenCookLevel"),
			(e[(e.OpenCookRole = 788)] = "OpenCookRole"),
			(e[(e.CloseCookRole = 789)] = "CloseCookRole"),
			(e[(e.CookSuccess = 790)] = "CookSuccess"),
			(e[(e.CookFail = 791)] = "CookFail"),
			(e[(e.MachiningSuccess = 792)] = "MachiningSuccess"),
			(e[(e.MachiningStudyFail = 793)] = "MachiningStudyFail"),
			(e[(e.FixSuccess = 794)] = "FixSuccess"),
			(e[(e.OpenSelected = 795)] = "OpenSelected"),
			(e[(e.CloseSelected = 796)] = "CloseSelected"),
			(e[(e.OnAddCommonEffect = 797)] = "OnAddCommonEffect"),
			(e[(e.ReceiveMonthCardDataEvent = 798)] = "ReceiveMonthCardDataEvent"),
			(e[(e.OnClickSingleTimeTowerStageBtn = 799)] =
				"OnClickSingleTimeTowerStageBtn");
		(e[(e.OnClickSingleTimeTowerTeamBtn = 800)] =
			"OnClickSingleTimeTowerTeamBtn"),
			(e[(e.OnClickSingleTimeTowerTeamRoleBtn = 801)] =
				"OnClickSingleTimeTowerTeamRoleBtn"),
			(e[(e.OnClickSingleTimeTowerStageDetailBtn = 802)] =
				"OnClickSingleTimeTowerStageDetailBtn"),
			(e[(e.OnClickSingleTimeTowerMonsterBtn = 803)] =
				"OnClickSingleTimeTowerMonsterBtn"),
			(e[(e.OnClickSingleTimeTowerDetailSwitchBtn = 804)] =
				"OnClickSingleTimeTowerDetailSwitchBtn"),
			(e[(e.OnInstResultNotify = 805)] = "OnInstResultNotify"),
			(e[(e.OnTowerChallengeChangeTeamNotify = 806)] =
				"OnTowerChallengeChangeTeamNotify"),
			(e[(e.OnTowerRewardReceived = 807)] = "OnTowerRewardReceived"),
			(e[(e.RedDotTowerReward = 808)] = "RedDotTowerReward"),
			(e[(e.RedDotTowerRewardByDifficulties = 809)] =
				"RedDotTowerRewardByDifficulties"),
			(e[(e.OnTowerRefresh = 810)] = "OnTowerRefresh"),
			(e[(e.OnTowerRecordUpdate = 811)] = "OnTowerRecordUpdate"),
			(e[(e.OnShowTowerGuideButton = 812)] = "OnShowTowerGuideButton"),
			(e[(e.OnClickCycleTowerAreaBtn = 813)] = "OnClickCycleTowerAreaBtn"),
			(e[(e.OnResetCycleTowerArea = 814)] = "OnResetCycleTowerArea"),
			(e[(e.OnClickCycleTowerRoleBtn = 815)] = "OnClickCycleTowerRoleBtn"),
			(e[(e.OnClickCycleTowerDetailSwitchBtn = 816)] =
				"OnClickCycleTowerDetailSwitchBtn"),
			(e[(e.OnCycleTowerUpdateSeason = 817)] = "OnCycleTowerUpdateSeason"),
			(e[(e.OnCycleTowerUpdateSeasonNotify = 818)] =
				"OnCycleTowerUpdateSeasonNotify"),
			(e[(e.OnCycleTowerScoreChange = 819)] = "OnCycleTowerScoreChange"),
			(e[(e.OnTowerGuideClose = 820)] = "OnTowerGuideClose"),
			(e[(e.OnTowerRefreshStars = 821)] = "OnTowerRefreshStars"),
			(e[(e.OnReceiveAdviceData = 822)] = "OnReceiveAdviceData"),
			(e[(e.OnCreateAdviceSuccess = 823)] = "OnCreateAdviceSuccess"),
			(e[(e.OnModifyAdviceSuccess = 824)] = "OnModifyAdviceSuccess"),
			(e[(e.OnDeleteAdviceSuccess = 825)] = "OnDeleteAdviceSuccess"),
			(e[(e.OnClickAdviceExpression = 826)] = "OnClickAdviceExpression"),
			(e[(e.OnClickAdviceWord = 827)] = "OnClickAdviceWord"),
			(e[(e.OnChangeAdviceWord = 828)] = "OnChangeAdviceWord"),
			(e[(e.OnClickAdviceSort = 829)] = "OnClickAdviceSort"),
			(e[(e.OnClickAdviceSortWord = 830)] = "OnClickAdviceSortWord"),
			(e[(e.OnClickAdviceMotion = 831)] = "OnClickAdviceMotion"),
			(e[(e.OnChangeAdviceRole = 832)] = "OnChangeAdviceRole"),
			(e[(e.OnClickAdviceSelectItem = 833)] = "OnClickAdviceSelectItem"),
			(e[(e.OnSelectAdviceWord = 834)] = "OnSelectAdviceWord"),
			(e[(e.OnSelectAdviceExpression = 835)] = "OnSelectAdviceExpression"),
			(e[(e.OnAdviceEntityNotify = 836)] = "OnAdviceEntityNotify"),
			(e[(e.OnAdviceVoteNotify = 837)] = "OnAdviceVoteNotify"),
			(e[(e.RefreshAdviceInfoView = 838)] = "RefreshAdviceInfoView"),
			(e[(e.SneakStart = 839)] = "SneakStart"),
			(e[(e.SneakEnd = 840)] = "SneakEnd"),
			(e[(e.AddAlterMark = 841)] = "AddAlterMark"),
			(e[(e.RemoveAlterMark = 842)] = "RemoveAlterMark"),
			(e[(e.OnSneakFoundChange = 843)] = "OnSneakFoundChange"),
			(e[(e.OnChildQuestNodeFinish = 844)] = "OnChildQuestNodeFinish"),
			(e[(e.AddStalkAlertMark = 845)] = "AddStalkAlertMark"),
			(e[(e.RemoveStalkAlertMark = 846)] = "RemoveStalkAlertMark"),
			(e[(e.OnStalkAlert = 847)] = "OnStalkAlert"),
			(e[(e.OnStalkAlertLifted = 848)] = "OnStalkAlertLifted"),
			(e[(e.OnStalkFound = 849)] = "OnStalkFound"),
			(e[(e.OnStalkFailed = 850)] = "OnStalkFailed"),
			(e[(e.AddEavesdropMark = 851)] = "AddEavesdropMark"),
			(e[(e.RemoveEavesdropMark = 852)] = "RemoveEavesdropMark"),
			(e[(e.OnEavesdropFound = 853)] = "OnEavesdropFound"),
			(e[(e.OnAddFullScreenEffect = 854)] = "OnAddFullScreenEffect"),
			(e[(e.OnRemoveFullScreenEffect = 855)] = "OnRemoveFullScreenEffect"),
			(e[(e.OnClearFullScreenEffect = 856)] = "OnClearFullScreenEffect"),
			(e[(e.OnChangeFullScreenNiagaraFloatParameter = 857)] =
				"OnChangeFullScreenNiagaraFloatParameter"),
			(e[(e.OnSceneItemBuffConsumed = 858)] = "OnSceneItemBuffConsumed"),
			(e[(e.OnSceneItemBuffRemoved = 859)] = "OnSceneItemBuffRemoved"),
			(e[(e.OnSceneItemBuffTimeout = 860)] = "OnSceneItemBuffTimeout"),
			(e[(e.OnSceneItemBuffTargetRemoved = 861)] =
				"OnSceneItemBuffTargetRemoved"),
			(e[(e.OnSceneItemBuffConsumerPerformanceComplete = 862)] =
				"OnSceneItemBuffConsumerPerformanceComplete"),
			(e[(e.OnExecuteServerGm = 863)] = "OnExecuteServerGm"),
			(e[(e.SetActiveBattleViewSkill = 864)] = "SetActiveBattleViewSkill"),
			(e[(e.SetEnableStateBattleViewSkill = 865)] =
				"SetEnableStateBattleViewSkill"),
			(e[(e.ActiveBattleView = 866)] = "ActiveBattleView"),
			(e[(e.DisActiveBattleView = 867)] = "DisActiveBattleView"),
			(e[(e.BattleUiCurRoleDataChanged = 868)] = "BattleUiCurRoleDataChanged"),
			(e[(e.BattleUiCurRoleDataChangedNextTick = 869)] =
				"BattleUiCurRoleDataChangedNextTick"),
			(e[(e.BattleUiAllRoleDataChanged = 870)] = "BattleUiAllRoleDataChanged"),
			(e[(e.BattleUiRemoveRoleData = 871)] = "BattleUiRemoveRoleData"),
			(e[(e.BattleUiElementEnergyChanged = 872)] =
				"BattleUiElementEnergyChanged"),
			(e[(e.BattleUiElementHideTagChanged = 873)] =
				"BattleUiElementHideTagChanged"),
			(e[(e.BattleUiDeadTagChanged = 874)] = "BattleUiDeadTagChanged"),
			(e[(e.BattleUiQteEnableTagChanged = 875)] =
				"BattleUiQteEnableTagChanged"),
			(e[(e.BattleUiQteCdTagChanged = 876)] = "BattleUiQteCdTagChanged"),
			(e[(e.BattleUiUseQteTagChanged = 877)] = "BattleUiUseQteTagChanged"),
			(e[(e.BattleUiConcertoEnableTagChanged = 878)] =
				"BattleUiConcertoEnableTagChanged"),
			(e[(e.BattleUiPoisonChanged = 879)] = "BattleUiPoisonChanged"),
			(e[(e.BattleUiHealthChanged = 880)] = "BattleUiHealthChanged"),
			(e[(e.BattleUiShieldChanged = 881)] = "BattleUiShieldChanged"),
			(e[(e.BattleUiLevelChanged = 882)] = "BattleUiLevelChanged"),
			(e[(e.BattleUiFloatTipUpdate = 883)] = "BattleUiFloatTipUpdate"),
			(e[(e.BattleUiPlayAudio = 884)] = "BattleUiPlayAudio"),
			(e[(e.BattleUiExploreModeChanged = 885)] = "BattleUiExploreModeChanged"),
			(e[(e.BattleUiMergeHeadStateVisibleChanged = 886)] =
				"BattleUiMergeHeadStateVisibleChanged"),
			(e[(e.BattleUiMergeHeadStateHealthChanged = 887)] =
				"BattleUiMergeHeadStateHealthChanged"),
			(e[(e.BattleUiEnvironmentKeyChanged = 888)] =
				"BattleUiEnvironmentKeyChanged"),
			(e[(e.BattleUiPressCombineButtonChanged = 889)] =
				"BattleUiPressCombineButtonChanged"),
			(e[(e.BattleUiToggleSilentAreaInfoView = 890)] =
				"BattleUiToggleSilentAreaInfoView"),
			(e[(e.BattleSettlementStateChanged = 891)] =
				"BattleSettlementStateChanged"),
			(e[(e.BattleScoreChanged = 892)] = "BattleScoreChanged"),
			(e[(e.RefreshInfluencePanel = 893)] = "RefreshInfluencePanel"),
			(e[(e.ReceiveReputationReward = 894)] = "ReceiveReputationReward"),
			(e[(e.SearchInfluence = 895)] = "SearchInfluence"),
			(e[(e.RedDotInfluence = 896)] = "RedDotInfluence"),
			(e[(e.BehaviorTreeStartActionSession = 897)] =
				"BehaviorTreeStartActionSession"),
			(e[(e.UiPlayCloseAudio = 898)] = "UiPlayCloseAudio"),
			(e[(e.OnSceneItemLockPropChange = 899)] = "OnSceneItemLockPropChange"),
			(e[(e.OnSpecialItemUpdate = 900)] = "OnSpecialItemUpdate"),
			(e[(e.EquipAndSwitchSpecialItem = 901)] = "EquipAndSwitchSpecialItem"),
			(e[(e.UnEquipSpecialItem = 902)] = "UnEquipSpecialItem"),
			(e[(e.ShowPlayerPosition = 903)] = "ShowPlayerPosition"),
			(e[(e.BattlePassHadEnterUpdate = 904)] = "BattlePassHadEnterUpdate"),
			(e[(e.GetBattlePassRewardEvent = 905)] = "GetBattlePassRewardEvent"),
			(e[(e.ReceiveBattlePassDataEvent = 906)] = "ReceiveBattlePassDataEvent"),
			(e[(e.BattlePassFirstUnlockAnime = 907)] = "BattlePassFirstUnlockAnime"),
			(e[(e.ReceiveBattlePassTaskEvent = 908)] = "ReceiveBattlePassTaskEvent"),
			(e[(e.OnChoseLevelItemEvent = 909)] = "OnChoseLevelItemEvent"),
			(e[(e.OnClickLevelItemEvent = 910)] = "OnClickLevelItemEvent"),
			(e[(e.UpdateBattlePassTaskEvent = 911)] = "UpdateBattlePassTaskEvent"),
			(e[(e.OnBattlePassLevelUpEvent = 912)] = "OnBattlePassLevelUpEvent"),
			(e[(e.OnBattlePassExpireEvent = 913)] = "OnBattlePassExpireEvent"),
			(e[(e.BattlePassMainViewHide = 914)] = "BattlePassMainViewHide"),
			(e[(e.SwitchViewType = 915)] = "SwitchViewType"),
			(e[(e.SwitchComposeType = 916)] = "SwitchComposeType"),
			(e[(e.GetComposeData = 917)] = "GetComposeData"),
			(e[(e.UpgradeComposeLevel = 918)] = "UpgradeComposeLevel"),
			(e[(e.OpenComposeLevel = 919)] = "OpenComposeLevel"),
			(e[(e.OpenCompose = 920)] = "OpenCompose"),
			(e[(e.ComposeSuccess = 921)] = "ComposeSuccess"),
			(e[(e.ComposeFail = 922)] = "ComposeFail"),
			(e[(e.OpenHelpRole = 923)] = "OpenHelpRole"),
			(e[(e.CloseHelpRole = 924)] = "CloseHelpRole"),
			(e[(e.UpdateComposeFormula = 925)] = "UpdateComposeFormula"),
			(e[(e.UpdateComposeInfo = 926)] = "UpdateComposeInfo"),
			(e[(e.UpdateForgingFormula = 927)] = "UpdateForgingFormula"),
			(e[(e.OpenForging = 928)] = "OpenForging"),
			(e[(e.GetForgingData = 929)] = "GetForgingData"),
			(e[(e.ForgingSuccess = 930)] = "ForgingSuccess"),
			(e[(e.ForgingFail = 931)] = "ForgingFail"),
			(e[(e.ChangePlayerInfoId = 932)] = "ChangePlayerInfoId"),
			(e[(e.OnShowGridAnimation = 933)] = "OnShowGridAnimation"),
			(e[(e.OnActivateUiCameraAnimationHandle = 934)] =
				"OnActivateUiCameraAnimationHandle"),
			(e[(e.OnActivateUiCameraAnimationHandleFail = 935)] =
				"OnActivateUiCameraAnimationHandleFail"),
			(e[(e.OnUiBlendInCameraSequenceFinished = 936)] =
				"OnUiBlendInCameraSequenceFinished"),
			(e[(e.RoleHandBookActive = 937)] = "RoleHandBookActive"),
			(e[(e.OnSequenceCameraStatus = 938)] = "OnSequenceCameraStatus"),
			(e[(e.LocalStorageInitPlayerId = 939)] = "LocalStorageInitPlayerId"),
			(e[(e.DynamicInteractServerResponse = 940)] =
				"DynamicInteractServerResponse"),
			(e[(e.UpdateCameraInfo = 941)] = "UpdateCameraInfo"),
			(e[(e.PlayCameraLevelSequence = 942)] = "PlayCameraLevelSequence"),
			(e[(e.CameraModeChanged = 943)] = "CameraModeChanged"),
			(e[(e.CameraViewTargetChanged = 944)] = "CameraViewTargetChanged"),
			(e[(e.FixedCameraRestored = 945)] = "FixedCameraRestored"),
			(e[(e.CameraCharacterChanged = 946)] = "CameraCharacterChanged"),
			(e[(e.OpenTreasureBox = 947)] = "OpenTreasureBox"),
			(e[(e.OnHandBookDataInit = 948)] = "OnHandBookDataInit"),
			(e[(e.OnHandBookDataUpdate = 949)] = "OnHandBookDataUpdate"),
			(e[(e.OnHandBookRedDotUpdate = 950)] = "OnHandBookRedDotUpdate"),
			(e[(e.OnHandBookRead = 951)] = "OnHandBookRead"),
			(e[(e.OnPhantomReadRedDotUpdate = 952)] = "OnPhantomReadRedDotUpdate"),
			(e[(e.OnItemReadRedDotUpdate = 953)] = "OnItemReadRedDotUpdate"),
			(e[(e.OnPhotoSelect = 954)] = "OnPhotoSelect"),
			(e[(e.OnGeographyPhotoSelect = 955)] = "OnGeographyPhotoSelect"),
			(e[(e.OnHandBookPlotNodeRefresh = 956)] = "OnHandBookPlotNodeRefresh"),
			(e[(e.RemoveCreatureDataComponentCache = 957)] =
				"RemoveCreatureDataComponentCache"),
			(e[(e.TravelClearView = 958)] = "TravelClearView"),
			(e[(e.OnPressOrReleaseBehaviorButton = 959)] =
				"OnPressOrReleaseBehaviorButton"),
			(e[(e.SetImageQuality = 960)] = "SetImageQuality"),
			(e[(e.SetDisplayMode = 961)] = "SetDisplayMode"),
			(e[(e.SetResolution = 962)] = "SetResolution"),
			(e[(e.SetNiagaraQuality = 963)] = "SetNiagaraQuality"),
			(e[(e.AfterGameQualitySettingsManagerInitialize = 964)] =
				"AfterGameQualitySettingsManagerInitialize"),
			(e[(e.SetGmIsOpen = 965)] = "SetGmIsOpen"),
			(e[(e.AddToTickList = 966)] = "AddToTickList"),
			(e[(e.HandleNextAction = 967)] = "HandleNextAction"),
			(e[(e.HandleActionFailure = 968)] = "HandleActionFailure"),
			(e[(e.AddGuaranteeAction = 969)] = "AddGuaranteeAction"),
			(e[(e.RemGuaranteeAction = 970)] = "RemGuaranteeAction"),
			(e[(e.ShareGroupCd = 971)] = "ShareGroupCd"),
			(e[(e.AddShareGroupLimitCount = 972)] = "AddShareGroupLimitCount"),
			(e[(e.OnInteractPlotStart = 973)] = "OnInteractPlotStart"),
			(e[(e.OnInteractPlotEnd = 974)] = "OnInteractPlotEnd"),
			(e[(e.OnAchievementDataNotify = 975)] = "OnAchievementDataNotify"),
			(e[(e.OnAchievementDataWithIdNotify = 976)] =
				"OnAchievementDataWithIdNotify"),
			(e[(e.OnAchievementGroupDataNotify = 977)] =
				"OnAchievementGroupDataNotify"),
			(e[(e.OnGetAchievementBaseData = 978)] = "OnGetAchievementBaseData"),
			(e[(e.OnGetAchievementSearchTextChange = 979)] =
				"OnGetAchievementSearchTextChange"),
			(e[(e.OnAchievementGroupChange = 980)] = "OnAchievementGroupChange"),
			(e[(e.RefreshAchievementRedPoint = 981)] = "RefreshAchievementRedPoint"),
			(e[(e.OnActivityUpdate = 982)] = "OnActivityUpdate"),
			(e[(e.OnSelectActivity = 983)] = "OnSelectActivity"),
			(e[(e.RefreshActivityTab = 984)] = "RefreshActivityTab"),
			(e[(e.OnReceiveActivityData = 985)] = "OnReceiveActivityData"),
			(e[(e.SetActivityViewState = 986)] = "SetActivityViewState"),
			(e[(e.SetActivityViewCurrency = 987)] = "SetActivityViewCurrency"),
			(e[(e.OnClickActivityRunChallenge = 988)] =
				"OnClickActivityRunChallenge"),
			(e[(e.OnSelectActivityRunChallengeItem = 989)] =
				"OnSelectActivityRunChallengeItem"),
			(e[(e.RefreshCommonActivityRedDot = 990)] =
				"RefreshCommonActivityRedDot"),
			(e[(e.RefreshRunActivityRedDot = 991)] = "RefreshRunActivityRedDot"),
			(e[(e.OnGetRunActivityReward = 992)] = "OnGetRunActivityReward"),
			(e[(e.OnActivityClose = 993)] = "OnActivityClose"),
			(e[(e.OnActivityOpen = 994)] = "OnActivityOpen"),
			(e[(e.OnActivitySequenceEmitEvent = 995)] =
				"OnActivitySequenceEmitEvent"),
			(e[(e.RefreshCommonActivityRewardPopUpView = 996)] =
				"RefreshCommonActivityRewardPopUpView"),
			(e[(e.ActivityViewChange = 997)] = "ActivityViewChange"),
			(e[(e.ActivityViewRefreshCurrent = 998)] = "ActivityViewRefreshCurrent"),
			(e[(e.LongShanUpdate = 999)] = "LongShanUpdate"),
			(e[(e.OnPhantomCollectUpdate = 1e3)] = "OnPhantomCollectUpdate"),
			(e[(e.TurntableStartRun = 1001)] = "TurntableStartRun"),
			(e[(e.GmAutoModeChange = 1002)] = "GmAutoModeChange"),
			(e[(e.OnAddNotAllowFightInputViewName = 1003)] =
				"OnAddNotAllowFightInputViewName"),
			(e[(e.OnRemoveNotAllowFightInputViewName = 1004)] =
				"OnRemoveNotAllowFightInputViewName"),
			(e[(e.OnClearNotAllowFightInputViewName = 1005)] =
				"OnClearNotAllowFightInputViewName"),
			(e[(e.OnSelectedEditPanelItem = 1006)] = "OnSelectedEditPanelItem"),
			(e[(e.UiRoleSequenceEndKeyFrame = 1007)] = "UiRoleSequenceEndKeyFrame"),
			(e[(e.DropItemStarted = 1008)] = "DropItemStarted"),
			(e[(e.OnRoleChangeEnd = 1009)] = "OnRoleChangeEnd"),
			(e[(e.ComboTeachingPress = 1010)] = "ComboTeachingPress"),
			(e[(e.ComboTeachingRelease = 1011)] = "ComboTeachingRelease"),
			(e[(e.ComboTeachingHold = 1012)] = "ComboTeachingHold"),
			(e[(e.ComboTeachingNodeEnd = 1013)] = "ComboTeachingNodeEnd"),
			(e[(e.ComboTeachingViewOpen = 1014)] = "ComboTeachingViewOpen"),
			(e[(e.SkillAcceptChanged = 1015)] = "SkillAcceptChanged"),
			(e[(e.ComboTeachingFinish = 1016)] = "ComboTeachingFinish"),
			(e[(e.ComboTeachingCloseGuide = 1017)] = "ComboTeachingCloseGuide"),
			(e[(e.RequestClearMeshRotationBuffer = 1018)] =
				"RequestClearMeshRotationBuffer"),
			(e[(e.NavigationViewCreate = 1019)] = "NavigationViewCreate"),
			(e[(e.NavigationViewDestroy = 1020)] = "NavigationViewDestroy"),
			(e[(e.ResetNavigationListener = 1021)] = "ResetNavigationListener"),
			(e[(e.NavigationTriggerMapForward = 1022)] =
				"NavigationTriggerMapForward"),
			(e[(e.NavigationTriggerMapRight = 1023)] = "NavigationTriggerMapRight"),
			(e[(e.NavigationTriggerMapZoom = 1024)] = "NavigationTriggerMapZoom"),
			(e[(e.NavigationTriggerRoleLookUp = 1025)] =
				"NavigationTriggerRoleLookUp"),
			(e[(e.NavigationTriggerRoleTurn = 1026)] = "NavigationTriggerRoleTurn"),
			(e[(e.NavigationTriggerRoleZoom = 1027)] = "NavigationTriggerRoleZoom"),
			(e[(e.NavigationTriggerRoleReset = 1028)] = "NavigationTriggerRoleReset"),
			(e[(e.FunctionGridSelected = 1029)] = "FunctionGridSelected"),
			(e[(e.OnPersonalCardRead = 1030)] = "OnPersonalCardRead"),
			(e[(e.OnHeadIconChange = 1031)] = "OnHeadIconChange"),
			(e[(e.OnSignChange = 1032)] = "OnSignChange"),
			(e[(e.OnNameChange = 1033)] = "OnNameChange"),
			(e[(e.OnBirthChange = 1034)] = "OnBirthChange"),
			(e[(e.OnBirthDisplayChange = 1035)] = "OnBirthDisplayChange"),
			(e[(e.OnCardChange = 1036)] = "OnCardChange"),
			(e[(e.ResetRoleFlag = 1037)] = "ResetRoleFlag"),
			(e[(e.OnRoleShowListChange = 1038)] = "OnRoleShowListChange"),
			(e[(e.OnRoleElementChange = 1039)] = "OnRoleElementChange"),
			(e[(e.ShowRoleElementChangePreviewEffect = 1040)] =
				"ShowRoleElementChangePreviewEffect"),
			(e[(e.OnChangedActionKeys = 1041)] = "OnChangedActionKeys"),
			(e[(e.OnChangedAxisKeys = 1042)] = "OnChangedAxisKeys"),
			(e[(e.SelectRoleTab = 1043)] = "SelectRoleTab"),
			(e[(e.SelectRoleTabOutside = 1044)] = "SelectRoleTabOutside"),
			(e[(e.OnFunctionViewShow = 1045)] = "OnFunctionViewShow"),
			(e[(e.UpdatePanelQteWorldTimeDilation = 1046)] =
				"UpdatePanelQteWorldTimeDilation"),
			(e[(e.PanelQteStart = 1047)] = "PanelQteStart"),
			(e[(e.PanelQteEnd = 1048)] = "PanelQteEnd"),
			(e[(e.StartHeartBeat = 1049)] = "StartHeartBeat"),
			(e[(e.StopHeartBeat = 1050)] = "StopHeartBeat"),
			(e[(e.CreateEffectHandle = 1051)] = "CreateEffectHandle"),
			(e[(e.RemoveEffectHandle = 1052)] = "RemoveEffectHandle"),
			(e[(e.LoadEffect = 1053)] = "LoadEffect"),
			(e[(e.BeforePlayEffect = 1054)] = "BeforePlayEffect"),
			(e[(e.AfterPlayEffect = 1055)] = "AfterPlayEffect"),
			(e[(e.FinishEffect = 1056)] = "FinishEffect"),
			(e[(e.TestQuestAutoPilotFinish = 1057)] = "TestQuestAutoPilotFinish"),
			(e[(e.TestQuestFunctionFinish = 1058)] = "TestQuestFunctionFinish"),
			(e[(e.OnRefreshRewardViewItemList = 1059)] =
				"OnRefreshRewardViewItemList"),
			(e[(e.OnRefreshRewardProgressBar = 1060)] = "OnRefreshRewardProgressBar"),
			(e[(e.OnRefreshRewardButton = 1061)] = "OnRefreshRewardButton"),
			(e[(e.OnItemRewardNotify = 1062)] = "OnItemRewardNotify"),
			(e[(e.OnShowRewardView = 1063)] = "OnShowRewardView"),
			(e[(e.OnCloseRewardView = 1064)] = "OnCloseRewardView"),
			(e[(e.OnPlotWaitViewDone = 1065)] = "OnPlotWaitViewDone"),
			(e[(e.OnPlayCameraAnimationStart = 1066)] = "OnPlayCameraAnimationStart"),
			(e[(e.OnPlayCameraAnimationFinish = 1067)] =
				"OnPlayCameraAnimationFinish"),
			(e[(e.CommunicateFinished = 1068)] = "CommunicateFinished"),
			(e[(e.CommunicateAgain = 1069)] = "CommunicateAgain"),
			(e[(e.OnPhotographSetUpViewVisibleChanged = 1070)] =
				"OnPhotographSetUpViewVisibleChanged"),
			(e[(e.OnEntityCameraOneSituationChanged = 1071)] =
				"OnEntityCameraOneSituationChanged"),
			(e[(e.OnEntityCameraSearchGreat = 1072)] = "OnEntityCameraSearchGreat"),
			(e[(e.OnEntityCameraFinished = 1073)] = "OnEntityCameraFinished"),
			(e[(e.OnScreenShotDone = 1074)] = "OnScreenShotDone"),
			(e[(e.OnSubmitItemSuccess = 1075)] = "OnSubmitItemSuccess"),
			(e[(e.OnSubmitItemFail = 1076)] = "OnSubmitItemFail"),
			(e[(e.OnSubmitItemLevelUp = 1077)] = "OnSubmitItemLevelUp"),
			(e[(e.OnSubmitItemLevelMax = 1078)] = "OnSubmitItemLevelMax"),
			(e[(e.OnCameraSequenceSetUiVisible = 1079)] =
				"OnCameraSequenceSetUiVisible"),
			(e[(e.OnUiScreenRootVisibleChange = 1080)] =
				"OnUiScreenRootVisibleChange"),
			(e[(e.OnTurntableControllerBusyStateChange = 1081)] =
				"OnTurntableControllerBusyStateChange"),
			(e[(e.OnAnyProgressControlEnableStateChange = 1082)] =
				"OnAnyProgressControlEnableStateChange"),
			(e[(e.OnDropItemSuccess = 1083)] = "OnDropItemSuccess"),
			(e[(e.OnInteractDropItemSuccess = 1084)] = "OnInteractDropItemSuccess"),
			(e[(e.OnExecuteUiCameraSequenceEvent = 1085)] =
				"OnExecuteUiCameraSequenceEvent"),
			(e[(e.OnInputAnyKey = 1086)] = "OnInputAnyKey"),
			(e[(e.OnFilterDataUpdate = 1087)] = "OnFilterDataUpdate"),
			(e[(e.OnPlayNpcPerformSequence = 1088)] = "OnPlayNpcPerformSequence"),
			(e[(e.OnNpcPerformSequenceFinished = 1089)] =
				"OnNpcPerformSequenceFinished"),
			(e[(e.OnAntiqueShopUpgradeSequenceFinished = 1090)] =
				"OnAntiqueShopUpgradeSequenceFinished"),
			(e[(e.OnAntiqueShopLevelMaxSequenceFinished = 1091)] =
				"OnAntiqueShopLevelMaxSequenceFinished"),
			(e[(e.OnAntiqueShopUpgradeSequencePlayFail = 1092)] =
				"OnAntiqueShopUpgradeSequencePlayFail"),
			(e[(e.OnCookSuccessSequenceFinished = 1093)] =
				"OnCookSuccessSequenceFinished"),
			(e[(e.OnBeginPlayCookSuccessDisplay = 1094)] =
				"OnBeginPlayCookSuccessDisplay"),
			(e[(e.OnPlayCookSuccessDisplayFinished = 1095)] =
				"OnPlayCookSuccessDisplayFinished"),
			(e[(e.OnBeginPlayCookFailDisplay = 1096)] = "OnBeginPlayCookFailDisplay"),
			(e[(e.OnPlayCookFailDisplayFinished = 1097)] =
				"OnPlayCookFailDisplayFinished"),
			(e[(e.OnBeginPlayCompositeWorkingDisplay = 1098)] =
				"OnBeginPlayCompositeWorkingDisplay"),
			(e[(e.OnPlayCompositeWorkingDisplayFinished = 1099)] =
				"OnPlayCompositeWorkingDisplayFinished"),
			(e[(e.OnBeginPlayForgingWorkingDisplay = 1100)] =
				"OnBeginPlayForgingWorkingDisplay"),
			(e[(e.OnPlayForgingWorkingDisplayFinished = 1101)] =
				"OnPlayForgingWorkingDisplayFinished"),
			(e[(e.OnCharFootOnTheGround = 1102)] = "OnCharFootOnTheGround"),
			(e[(e.BattleViewActiveSequenceFinish = 1103)] =
				"BattleViewActiveSequenceFinish"),
			(e[(e.SmartObjectAiAlterNotify = 1104)] = "SmartObjectAiAlterNotify"),
			(e[(e.OnSetActorHidden = 1105)] = "OnSetActorHidden"),
			(e[(e.OnCheckGamePing = 1106)] = "OnCheckGamePing"),
			(e[(e.OnRemoveItemRedDot = 1107)] = "OnRemoveItemRedDot"),
			(e[(e.RunGm = 1108)] = "RunGm"),
			(e[(e.GmHandleActionFailed = 1109)] = "GmHandleActionFailed"),
			(e[(e.TestEffectAddDaRec = 1110)] = "TestEffectAddDaRec"),
			(e[(e.TestEffectAddEffectRec = 1111)] = "TestEffectAddEffectRec"),
			(e[(e.TestManuallyGarbageCollection = 1112)] =
				"TestManuallyGarbageCollection"),
			(e[(e.GmEntityPerformanceTestFinish = 1113)] =
				"GmEntityPerformanceTestFinish"),
			(e[(e.GmOnlyShowMiniMap = 1114)] = "GmOnlyShowMiniMap"),
			(e[(e.GmOnlyShowJoyStick = 1115)] = "GmOnlyShowJoyStick"),
			(e[(e.RoguelikeCloseGainSelectView = 1116)] =
				"RoguelikeCloseGainSelectView"),
			(e[(e.RoguelikeDataUpdate = 1117)] = "RoguelikeDataUpdate"),
			(e[(e.RoguelikeChooseDataResult = 1118)] = "RoguelikeChooseDataResult"),
			(e[(e.RoguelikeChooseDataNotify = 1119)] = "RoguelikeChooseDataNotify"),
			(e[(e.RoguelikeInfoSelectedToken = 1120)] = "RoguelikeInfoSelectedToken"),
			(e[(e.RoguelikeRefreshGain = 1121)] = "RoguelikeRefreshGain"),
			(e[(e.RoguelikeSelectSkill = 1122)] = "RoguelikeSelectSkill"),
			(e[(e.RoguelikeTalentLevelUp = 1123)] = "RoguelikeTalentLevelUp"),
			(e[(e.RoguelikeCurrencyUpdate = 1124)] = "RoguelikeCurrencyUpdate"),
			(e[(e.RoguelikeSelectToken = 1125)] = "RoguelikeSelectToken"),
			(e[(e.RoguelikeSelectSeason = 1126)] = "RoguelikeSelectSeason"),
			(e[(e.RoguelikeGetTokenReward = 1127)] = "RoguelikeGetTokenReward"),
			(e[(e.RogueTermUnlock = 1128)] = "RogueTermUnlock"),
			(e[(e.OnMarkItemViewCreate = 1129)] = "OnMarkItemViewCreate"),
			(e[(e.OnMarkItemViewDestroy = 1130)] = "OnMarkItemViewDestroy"),
			(e[(e.OnMarkItemViewEnter = 1131)] = "OnMarkItemViewEnter"),
			(e[(e.OnMarkItemViewExit = 1132)] = "OnMarkItemViewExit"),
			(e[(e.OnOpenSystemFeed = 1133)] = "OnOpenSystemFeed"),
			(e[(e.OnCloseSystemFeed = 1134)] = "OnCloseSystemFeed"),
			(e[(e.OnDeliveryProps = 1135)] = "OnDeliveryProps"),
			(e[(e.OnWorldMapTrackMarkItem = 1136)] = "OnWorldMapTrackMarkItem"),
			(e[(e.OnSundialRingChangeShine = 1137)] = "OnSundialRingChangeShine"),
			(e[(e.OnSundialRingSwitch = 1138)] = "OnSundialRingSwitch"),
			(e[(e.OnNeedUpdateSundialTips = 1139)] = "OnNeedUpdateSundialTips"),
			(e[(e.OnSignalDeviceLinkingCheck = 1140)] = "OnSignalDeviceLinkingCheck"),
			(e[(e.OnSignalDeviceReset = 1141)] = "OnSignalDeviceReset"),
			(e[(e.OnSignalDeviceLinking = 1142)] = "OnSignalDeviceLinking"),
			(e[(e.OnSignalDeviceFinish = 1143)] = "OnSignalDeviceFinish"),
			(e[(e.OnOverlapSceneItemExploreInteractRange = 1144)] =
				"OnOverlapSceneItemExploreInteractRange"),
			(e[(e.OnUseMapExploreToolSuccess = 1145)] = "OnUseMapExploreToolSuccess"),
			(e[(e.OnMapExploreToolPlaceNumUpdated = 1146)] =
				"OnMapExploreToolPlaceNumUpdated"),
			(e[(e.DoLeaveLevel = 1147)] = "DoLeaveLevel"),
			(e[(e.ClearSceneBegin = 1148)] = "ClearSceneBegin"),
			(e[(e.OnExploreProgressResponse = 1149)] = "OnExploreProgressResponse"),
			(e[(e.OnExploreScoreRewardResponse = 1150)] =
				"OnExploreScoreRewardResponse"),
			(e[(e.OnCountryExploreScoreInfoResponse = 1151)] =
				"OnCountryExploreScoreInfoResponse"),
			(e[(e.OnExploreLevelNotify = 1152)] = "OnExploreLevelNotify"),
			(e[(e.OnSignalCatchSuccess = 1153)] = "OnSignalCatchSuccess"),
			(e[(e.OnSignalCatchFailed = 1154)] = "OnSignalCatchFailed"),
			(e[(e.OnSignalCatchStart = 1155)] = "OnSignalCatchStart"),
			(e[(e.OnSignalCatchContinue = 1156)] = "OnSignalCatchContinue"),
			(e[(e.OnSignalCatchStartAgain = 1157)] = "OnSignalCatchStartAgain"),
			(e[(e.RefreshMonthCardRedDot = 1158)] = "RefreshMonthCardRedDot"),
			(e[(e.OnSetJoystickMode = 1159)] = "OnSetJoystickMode"),
			(e[(e.OnOverlapEncloseSpace = 1160)] = "OnOverlapEncloseSpace"),
			(e[(e.OnEncloseSpaceTypeChange = 1161)] = "OnEncloseSpaceTypeChange"),
			(e[(e.OnAndroidConfigurationChange = 1162)] =
				"OnAndroidConfigurationChange"),
			(e[(e.OnChatPlayerInfoChanged = 1163)] = "OnChatPlayerInfoChanged"),
			(e[(e.OnPlotTransitionRemoveCallback = 1164)] =
				"OnPlotTransitionRemoveCallback"),
			(e[(e.OnEnterOrExitExecutionRange = 1165)] =
				"OnEnterOrExitExecutionRange"),
			(e[(e.OnExecutionOptionChange = 1166)] = "OnExecutionOptionChange"),
			(e[(e.OnInteractActionEnd = 1167)] = "OnInteractActionEnd"),
			(e[(e.OnLevelFuncFlagSet = 1168)] = "OnLevelFuncFlagSet"),
			(e[(e.OnLevelFuncFlagChanged = 1169)] = "OnLevelFuncFlagChanged"),
			(e[(e.OnRefreshRewardView = 1170)] = "OnRefreshRewardView"),
			(e[(e.OnRefreshSpecialItemAllowReqUse = 1171)] =
				"OnRefreshSpecialItemAllowReqUse"),
			(e[(e.OnQueryProductInfo = 1172)] = "OnQueryProductInfo"),
			(e[(e.ReconnectClearData = 1173)] = "ReconnectClearData"),
			(e[(e.OnPreEndPIE = 1174)] = "OnPreEndPIE"),
			(e[(e.NoticeJourneyReceive = 1175)] = "NoticeJourneyReceive"),
			(e[(e.OnEntityInOutRangeLocal = 1176)] = "OnEntityInOutRangeLocal"),
			(e[(e.OnMyPlayerInOutRangeLocal = 1177)] = "OnMyPlayerInOutRangeLocal"),
			(e[(e.OnActorInOutRangeLocal = 1178)] = "OnActorInOutRangeLocal"),
			(e[(e.OnEntityInOutRangeOnline = 1179)] = "OnEntityInOutRangeOnline"),
			(e[(e.OnPlayerInOutRangeOnline = 1180)] = "OnPlayerInOutRangeOnline"),
			(e[(e.OnSetLoginServerId = 1181)] = "OnSetLoginServerId"),
			(e[(e.SetDecalShadowEnabled = 1182)] = "SetDecalShadowEnabled"),
			(e[(e.OnSelectTimePreset = 1183)] = "OnSelectTimePreset"),
			(e[(e.OnActionKeyChanged = 1184)] = "OnActionKeyChanged"),
			(e[(e.OnAxisKeyChanged = 1185)] = "OnAxisKeyChanged"),
			(e[(e.BeamCastStart = 1186)] = "BeamCastStart"),
			(e[(e.BeamCastStop = 1187)] = "BeamCastStop"),
			(e[(e.OnResetPhotographCamera = 1188)] = "OnResetPhotographCamera"),
			(e[(e.OnSpecialItemNotAllow = 1189)] = "OnSpecialItemNotAllow"),
			(e[(e.OnMarkItemShowStateChange = 1190)] = "OnMarkItemShowStateChange"),
			(e[(e.OnAbsoluteTimeStop = 1191)] = "OnAbsoluteTimeStop"),
			(e[(e.OnFightTestEnd = 1192)] = "OnFightTestEnd"),
			(e[(e.OnManipulateShowLandTips = 1193)] = "OnManipulateShowLandTips"),
			(e[(e.BeforeUiModelLoadStart = 1194)] = "BeforeUiModelLoadStart"),
			(e[(e.OnUiModelRoleConfigIdChange = 1195)] =
				"OnUiModelRoleConfigIdChange"),
			(e[(e.OnUiModelRoleDataIdChange = 1196)] = "OnUiModelRoleDataIdChange"),
			(e[(e.OnUiModelLoadComplete = 1197)] = "OnUiModelLoadComplete"),
			(e[(e.OnUiModelVisibleChange = 1198)] = "OnUiModelVisibleChange"),
			(e[(e.OnUiModelSetDitherEffect = 1199)] = "OnUiModelSetDitherEffect"),
			(e[(e.WorldMapSubMapChanged = 1200)] = "WorldMapSubMapChanged"),
			(e[(e.WorldMapSelectMultiMap = 1201)] = "WorldMapSelectMultiMap"),
			(e[(e.RoguelikePopularEntriesChange = 1202)] =
				"RoguelikePopularEntriesChange"),
			(e[(e.OnSceneItemMoveEventBroken = 1203)] = "OnSceneItemMoveEventBroken"),
			(e[(e.OnFragmentMemoryDataUpdate = 1204)] = "OnFragmentMemoryDataUpdate"),
			(e[(e.OnFragmentMemoryCollectUpdate = 1205)] =
				"OnFragmentMemoryCollectUpdate"),
			(e[(e.OnFragmentTopicSelect = 1206)] = "OnFragmentTopicSelect"),
			(e[(e.OnFragmentTopicClick = 1207)] = "OnFragmentTopicClick"),
			(e[(e.FragmentRewardRedDot = 1208)] = "FragmentRewardRedDot"),
			(e[(e.FragmentRewardTopicRedDot = 1209)] = "FragmentRewardTopicRedDot"),
			(e[(e.FragmentRewardEntranceRedDot = 1210)] =
				"FragmentRewardEntranceRedDot"),
			(e[(e.OnChangeBossRushBuff = 1211)] = "OnChangeBossRushBuff"),
			(e[(e.RequestChangeBossRushView = 1212)] = "RequestChangeBossRushView"),
			(e[(e.BossRushDataUpdate = 1213)] = "BossRushDataUpdate"),
			(e[(e.BossRefreshBossRushRewardRedDot = 1214)] =
				"BossRefreshBossRushRewardRedDot"),
			(e[(e.OnSetGameModeDataDone = 1215)] = "OnSetGameModeDataDone"),
			(e[(e.OnBossRushBuffViewOpened = 1216)] = "OnBossRushBuffViewOpened"),
			(e[(e.OnTutorialTipExistChanged = 1217)] = "OnTutorialTipExistChanged"),
			(e[(e.OnTutorialUpdate = 1218)] = "OnTutorialUpdate"),
			(e[(e.LevelLoadingLockTimeDilation = 1219)] =
				"LevelLoadingLockTimeDilation"),
			(e[(e.LevelLoadingUnlockDilation = 1220)] = "LevelLoadingUnlockDilation"),
			(e[(e.ElevatorMove = 1221)] = "ElevatorMove");
	})((EEventName = exports.EEventName || (exports.EEventName = {})));
