"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.RESETSPEED =
		exports.SPEEDUP =
		exports.ENTITY_TIMESCALE_PAUSE_THRESHOLD =
		exports.ENTITY_TIMESCALE_ENABLE_THRESHOLD =
		exports.RPTC_SKIP_PROGRESS =
		exports.RPTC_COVER_LEVEL_CLOSING =
		exports.RPTC_COVER_LEVEL_OPENING =
		exports.RTPC_COVER_LEVEL_DELTA =
		exports.RTPC_COVER_ALPHA =
		exports.RTPC_COVER_LEVEL =
		exports.RTPCGLOBALWET =
		exports.RTPCSNOWINTENSITY =
		exports.RTPCRAININTENSITY =
		exports.RTPCTEXTREPLY =
		exports.RTPCSPEEDUP =
		exports.PLOT_NOT_VIDEO =
		exports.PLOT_VIDEO =
		exports.PLOT_VIDEO_GROUP =
		exports.STATEPLOTPERFORMLEVELGROUP =
		exports.STATEBACKGROUND =
		exports.STATEINCUTSCENE =
		exports.STATENORMAL =
		exports.STATEGROUP =
			void 0),
	(exports.STATEGROUP = "game_state"),
	(exports.STATENORMAL = "normal"),
	(exports.STATEINCUTSCENE = "incutscene"),
	(exports.STATEBACKGROUND = "background"),
	(exports.STATEPLOTPERFORMLEVELGROUP = "plot_perform_level"),
	(exports.PLOT_VIDEO_GROUP = "plot_perform_video"),
	(exports.PLOT_VIDEO = "video"),
	(exports.PLOT_NOT_VIDEO = "not_video"),
	(exports.RTPCSPEEDUP = "Cutscene_speedup"),
	(exports.RTPCTEXTREPLY = "Set_TextReply"),
	(exports.RTPCRAININTENSITY = "weather_rain_intensity"),
	(exports.RTPCSNOWINTENSITY = "weather_snow_intensity"),
	(exports.RTPCGLOBALWET = "global_wet"),
	(exports.RTPC_COVER_LEVEL = "ui_cover_level"),
	(exports.RTPC_COVER_ALPHA = "ui_cover_alpha"),
	(exports.RTPC_COVER_LEVEL_DELTA = "ui_cover_level_delta"),
	(exports.RPTC_COVER_LEVEL_OPENING = "ui_cover_level_opening"),
	(exports.RPTC_COVER_LEVEL_CLOSING = "ui_cover_level_closing"),
	(exports.RPTC_SKIP_PROGRESS = "ui_plot_skip_progress"),
	(exports.ENTITY_TIMESCALE_ENABLE_THRESHOLD = 0.8),
	(exports.ENTITY_TIMESCALE_PAUSE_THRESHOLD = 0.0625),
	(exports.SPEEDUP = 15),
	(exports.RESETSPEED = 0);
//# sourceMappingURL=AudioDefine.js.map
