"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.ROGUELIKE_SPECIAL_ITEM_LOCK_ALPHA =
		exports.ROGUELIKE_SPECIAL_ITEM_UNLOCK_ALPHA =
		exports.T_ROGUELIKETOTALELEMENT =
		exports.ROGUELIKEVIEW_FINIST_TEXT =
		exports.ROGUELIKEVIEW_PREVIEW_TEXT =
		exports.ROGUELIKEVIEW_NOTFINIST_TEXT =
		exports.COMPLETE =
		exports.ROGUELIKEVIEW_25_TEXT =
		exports.ROGUELIKEVIEW_24_TEXT =
		exports.ROGUELIKEVIEW_23_TEXT =
		exports.ROGUELIKEVIEW_22_TEXT =
		exports.ROGUELIKEVIEW_21_TEXT =
		exports.ROGUELIKEVIEW_20_TEXT =
		exports.ROGUELIKEVIEW_19_TEXT =
		exports.ROGUELIKEVIEW_18_TEXT =
		exports.ROGUELIKEVIEW_17_TEXT =
		exports.ROGUELIKEVIEW_16_TEXT =
		exports.ROGUELIKEVIEW_15_TEXT =
		exports.ROGUELIKEVIEW_14_TEXT =
		exports.ROGUELIKEVIEW_13_TEXT =
		exports.ROGUELIKEVIEW_12_TEXT =
		exports.ROGUELIKEVIEW_11_TEXT =
		exports.ROGUELIKEVIEW_10_TEXT =
		exports.ROGUELIKEVIEW_9_TEXT =
		exports.ROGUELIKEVIEW_8_TEXT =
		exports.ROGUELIKEVIEW_7_TEXT =
		exports.ROGUELIKEVIEW_6_TEXT =
		exports.ROGUELIKEVIEW_5_TEXT =
		exports.ROGUELIKEVIEW_4_TEXT =
		exports.ROGUELIKEVIEW_3_TEXT =
		exports.ROGUELIKEVIEW_2_TEXT =
		exports.ROGUELIKEVIEW_1_TEXT =
		exports.COMMON_SELECT_ITEM =
		exports.ROLE_SELECT_ITEM =
		exports.PHANTOM_SELECT_ITEM =
		exports.DEFAULT_ROGUELIKE_ENTRY_RATE =
		exports.ROGUELIKE_HELP_ID =
		exports.ROGUE_DETECTION_TAB_ID =
		exports.SKILL_POINT_ID =
		exports.COLLECT_SCORE_ID =
		exports.INSIDE_CURRENCY_ID =
		exports.OUTSIDE_CURRENCY_ID =
		exports.sortElementArray =
		exports.ElementInfo =
			void 0);
class ElementInfo {
	constructor(E, e, _ = void 0) {
		(this.ElementId = 0),
			(this.Count = 0),
			(this.Name = void 0),
			(this.IsPreview = !1),
			(this.ElementId = E),
			(this.Count = e),
			(this.Name = _);
	}
}
(exports.ElementInfo = ElementInfo),
	(exports.sortElementArray = [1, 2, 3, 4]),
	(exports.OUTSIDE_CURRENCY_ID = 80100001),
	(exports.INSIDE_CURRENCY_ID = 801e5),
	(exports.COLLECT_SCORE_ID = 80100002),
	(exports.SKILL_POINT_ID = 80100003),
	(exports.ROGUE_DETECTION_TAB_ID = 18),
	(exports.ROGUELIKE_HELP_ID = 76),
	(exports.DEFAULT_ROGUELIKE_ENTRY_RATE = 1e4),
	(exports.PHANTOM_SELECT_ITEM = "UiItem_PhantomSelectItem_Prefab"),
	(exports.ROLE_SELECT_ITEM = "UiItem_RoleSelectItem_Prefab"),
	(exports.COMMON_SELECT_ITEM = "UiItem_CommonSelectItem_Prefab"),
	(exports.ROGUELIKEVIEW_1_TEXT = "RoguelikeView_1_Text"),
	(exports.ROGUELIKEVIEW_2_TEXT = "RoguelikeView_2_Text"),
	(exports.ROGUELIKEVIEW_3_TEXT = "RoguelikeView_3_Text"),
	(exports.ROGUELIKEVIEW_4_TEXT = "RoguelikeView_4_Text"),
	(exports.ROGUELIKEVIEW_5_TEXT = "RoguelikeView_5_Text"),
	(exports.ROGUELIKEVIEW_6_TEXT = "RoguelikeView_6_Text"),
	(exports.ROGUELIKEVIEW_7_TEXT = "RoguelikeView_7_Text"),
	(exports.ROGUELIKEVIEW_8_TEXT = "RoguelikeView_8_Text"),
	(exports.ROGUELIKEVIEW_9_TEXT = "RoguelikeView_9_Text"),
	(exports.ROGUELIKEVIEW_10_TEXT = "RoguelikeView_10_Text"),
	(exports.ROGUELIKEVIEW_11_TEXT = "RoguelikeView_11_Text"),
	(exports.ROGUELIKEVIEW_12_TEXT = "RoguelikeView_12_Text"),
	(exports.ROGUELIKEVIEW_13_TEXT = "RoguelikeView_13_Text"),
	(exports.ROGUELIKEVIEW_14_TEXT = "RoguelikeView_14_Text"),
	(exports.ROGUELIKEVIEW_15_TEXT = "RoguelikeView_15_Text"),
	(exports.ROGUELIKEVIEW_16_TEXT = "RoguelikeView_16_Text"),
	(exports.ROGUELIKEVIEW_17_TEXT = "RoguelikeView_17_Text"),
	(exports.ROGUELIKEVIEW_18_TEXT = "RoguelikeView_18_Text"),
	(exports.ROGUELIKEVIEW_19_TEXT = "RoguelikeView_19_Text"),
	(exports.ROGUELIKEVIEW_20_TEXT = "RoguelikeView_20_Text"),
	(exports.ROGUELIKEVIEW_21_TEXT = "RoguelikeView_21_Text"),
	(exports.ROGUELIKEVIEW_22_TEXT = "RoguelikeView_22_Text"),
	(exports.ROGUELIKEVIEW_23_TEXT = "RoguelikeView_23_Text"),
	(exports.ROGUELIKEVIEW_24_TEXT = "RoguelikeView_24_Text"),
	(exports.ROGUELIKEVIEW_25_TEXT = "RoguelikeView_25_Text"),
	(exports.COMPLETE = "Complete"),
	(exports.ROGUELIKEVIEW_NOTFINIST_TEXT = "RoguelikeView_NotFinish_Text"),
	(exports.ROGUELIKEVIEW_PREVIEW_TEXT = "RoguelikeView_Preview_Text"),
	(exports.ROGUELIKEVIEW_FINIST_TEXT = "RoguelikeView_Finish_Text"),
	(exports.T_ROGUELIKETOTALELEMENT = "T_RoguelikeTotalElement"),
	(exports.ROGUELIKE_SPECIAL_ITEM_UNLOCK_ALPHA = 1),
	(exports.ROGUELIKE_SPECIAL_ITEM_LOCK_ALPHA = 0.6);
