"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.roleSystemModeUiParam = void 0),
	(exports.roleSystemModeUiParam = {
		0: {
			RoleListButton: !0,
			RoleListButtonRedDot: !0,
			RoleList: !0,
			RoleListNeedTrial: !0,
			RoleListRedDot: !1,
			TabRedDot: !0,
			TeachBtn: !0,
		},
		1: {
			RoleListButton: !0,
			RoleListButtonRedDot: !0,
			RoleList: !0,
			RoleListNeedTrial: !0,
			RoleListRedDot: !0,
			TabRedDot: !0,
			TeachBtn: !0,
		},
		2: {
			RoleListButton: !1,
			RoleListButtonRedDot: !1,
			RoleList: !0,
			RoleListNeedTrial: !1,
			RoleListRedDot: !1,
			TabRedDot: !1,
			TeachBtn: !1,
		},
		3: {
			RoleListButton: !1,
			RoleListButtonRedDot: !1,
			RoleList: !0,
			RoleListNeedTrial: !1,
			RoleListRedDot: !1,
			TabRedDot: !1,
			TeachBtn: !1,
		},
	});
