"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.genericPromptView = void 0),
	(exports.genericPromptView = {
		0: "EventConditionFloatTips",
		1: "DungeonClearanceFloatTips",
		2: "DungeonAutoExitFloatTips",
		3: "ChallengeSuccessFloatTips",
		4: "ChallengeFailedFloatTips",
		5: "ChallengeAchieveFloatTips",
		6: "AdditionalTasksFloatTips",
		7: "DelegateCompletionFloatTips",
		8: "CountDownFloatTips",
		9: "GenericPromptView",
		10: "ChapterStartFloatTips",
		11: "ChapterEndFloatTips",
		12: "DailyTaskEndTips",
		13: "PrepareCountdownFloatTips",
		14: "ComboTeachingFloatTips",
		15: "RoguelikeRoomFloatTips",
		16: "FlowChapterStartTips",
		17: "FlowChapterEndTips",
		18: "RemainStarWarningTips",
	});
