"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 });
const UE = require("ue");
class ItemMaterialControllerActorData extends UE.PrimaryDataAsset {
	constructor() {
		super(...arguments),
			(this.StartTime = -0),
			(this.LoopTime = -0),
			(this.EndTime = -0),
			(this.EnableBaseColorScale = !1),
			(this.BaseColorScale = void 0),
			(this.EnableAddEmissionColor = !1),
			(this.AddEmissionColor = void 0),
			(this.EnableEmissionChange = !1),
			(this.EmissionLightColorChangeProgress = void 0),
			(this.EmissionLightColorChangeStrength = void 0),
			(this.EmissionLightColorChangeColor = void 0),
			(this.EnableRimLight = !1),
			(this.RimLightColor = void 0),
			(this.RimPower = void 0),
			(this.EnableDissolve = !1),
			(this.DissolveProgress = void 0),
			(this.DissolveAdjustment = void 0),
			(this.DissolveEdageWidth = void 0),
			(this.DissolveEdageColor = void 0),
			(this.DissolveEdageStrength = void 0),
			(this.DissolveTexSpeed = void 0),
			(this.DissolveUv = 0),
			(this.DissolveTexScaleOffset = void 0),
			(this.EnableScanning = !1),
			(this.ScanningOutlineMixNoiseStrength = void 0),
			(this.ScanningOutlineStrength = void 0),
			(this.ScanningOutlineTexScaleOffset = void 0),
			(this.ScanningOutlineColor = void 0),
			(this.VertexAnimTimeDebug = void 0),
			(this.VertexAnimFrame = void 0),
			(this.PivotPainterTransform = void 0),
			(this.FloatingThreshold = void 0),
			(this.EnablePivotPainterWorldPositionOffset = !1),
			(this.EnableWorldPositionOffset = !1),
			(this.DisableFoliageEffect = !1),
			(this.EnableFoliageEffect = !1),
			(this.RimLightColorSpecil = void 0),
			(this.UseRimlightColorSpecil = !1),
			(this.RimlightColorStrength = void 0),
			(this.UseEmissionTex = !1),
			(this.EmissionTexStrength = void 0),
			(this.WorldPositionOffsetNormal = void 0),
			(this.WorldPositionOffsetOffset = void 0),
			(this.SimpleUspeed = void 0),
			(this.SimpleVspeed = void 0),
			(this.SimpleUseFlow = void 0),
			(this.EnableQuanXiPinTu = !1),
			(this.TransparencyQuanXiPinTu = void 0),
			(this.TransparentColorQuanXiPinTu = void 0),
			(this.OpaqueColorQuanXiPinTu = void 0),
			(this.EnableQuanXiFengSuo = !1),
			(this.TransparencyQuanXiFengSuo = void 0),
			(this.TransparentColorQuanXiFengSuo = void 0);
	}
}
exports.default = ItemMaterialControllerActorData;
