"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.ConfigStatement = void 0);
const CommonParamById_1 = require("../ConfigCommon/CommonParamById"),
	CommonParamLang_1 = require("../ConfigCommon/CommonParamLang"),
	AbnormalDamageConfigByLevel_1 = require("./AbnormalDamageConfigByLevel"),
	AbpMontageDataById_1 = require("./AbpMontageDataById"),
	AccessPathById_1 = require("./AccessPathById"),
	AchievementByGroupId_1 = require("./AchievementByGroupId"),
	AchievementById_1 = require("./AchievementById"),
	AchievementCategoryAll_1 = require("./AchievementCategoryAll"),
	AchievementCategoryById_1 = require("./AchievementCategoryById"),
	AchievementGroupByCategory_1 = require("./AchievementGroupByCategory"),
	AchievementGroupById_1 = require("./AchievementGroupById"),
	AchievementStarLevelByLevel_1 = require("./AchievementStarLevelByLevel"),
	ActionMappingAll_1 = require("./ActionMappingAll"),
	ActionMappingByActionName_1 = require("./ActionMappingByActionName"),
	ActionMappingByActionType_1 = require("./ActionMappingByActionType"),
	ActionTypeByType_1 = require("./ActionTypeByType"),
	ActivityById_1 = require("./ActivityById"),
	ActivitySignById_1 = require("./ActivitySignById"),
	AdventureTaskAll_1 = require("./AdventureTaskAll"),
	AdventureTaskById_1 = require("./AdventureTaskById"),
	AdventureTaskChapterAll_1 = require("./AdventureTaskChapterAll"),
	AdventureTaskChapterById_1 = require("./AdventureTaskChapterById"),
	AdviceConjunctionAll_1 = require("./AdviceConjunctionAll"),
	AdviceConjunctionById_1 = require("./AdviceConjunctionById"),
	AdviceParamsById_1 = require("./AdviceParamsById"),
	AdviceSentenceAll_1 = require("./AdviceSentenceAll"),
	AdviceSentenceById_1 = require("./AdviceSentenceById"),
	AdviceWordAll_1 = require("./AdviceWordAll"),
	AdviceWordById_1 = require("./AdviceWordById"),
	AdviceWordByType_1 = require("./AdviceWordByType"),
	AdviceWordTypeAll_1 = require("./AdviceWordTypeAll"),
	AdviceWordTypeById_1 = require("./AdviceWordTypeById"),
	AiAlertById_1 = require("./AiAlertById"),
	AiBaseById_1 = require("./AiBaseById"),
	AiBaseSkillById_1 = require("./AiBaseSkillById"),
	AiBattleWanderById_1 = require("./AiBattleWanderById"),
	AiBattleWanderGroupById_1 = require("./AiBattleWanderGroupById"),
	AiFleeById_1 = require("./AiFleeById"),
	AiHateById_1 = require("./AiHateById"),
	AiPatrolById_1 = require("./AiPatrolById"),
	AiSenseById_1 = require("./AiSenseById"),
	AiSenseGroupById_1 = require("./AiSenseGroupById"),
	AiSkillInfosById_1 = require("./AiSkillInfosById"),
	AiSkillPreconditionById_1 = require("./AiSkillPreconditionById"),
	AiStateMachineConfigById_1 = require("./AiStateMachineConfigById"),
	AiTeamAreaNewById_1 = require("./AiTeamAreaNewById"),
	AiTeamAttackById_1 = require("./AiTeamAttackById"),
	AiTeamLevelNewById_1 = require("./AiTeamLevelNewById"),
	AiWanderById_1 = require("./AiWanderById"),
	AiWanderRadiusConfigById_1 = require("./AiWanderRadiusConfigById"),
	AkiMapByMapId_1 = require("./AkiMapByMapId"),
	AkiMapSourceByMapId_1 = require("./AkiMapSourceByMapId"),
	AnimalHandBookAll_1 = require("./AnimalHandBookAll"),
	AnimalHandBookById_1 = require("./AnimalHandBookById"),
	AnimalHandBookByMeshId_1 = require("./AnimalHandBookByMeshId"),
	AreaByAreaId_1 = require("./AreaByAreaId"),
	AreaByCountryAndLevel_1 = require("./AreaByCountryAndLevel"),
	AreaByDeliveryMarkId_1 = require("./AreaByDeliveryMarkId"),
	AreaAtmosphereInfoById_1 = require("./AreaAtmosphereInfoById"),
	AreaMpcById_1 = require("./AreaMpcById"),
	AreaTaskExploreByAreaId_1 = require("./AreaTaskExploreByAreaId"),
	AreaTaskExploreById_1 = require("./AreaTaskExploreById"),
	AudioById_1 = require("./AudioById"),
	AxisMappingAll_1 = require("./AxisMappingAll"),
	AxisMappingByAxisName_1 = require("./AxisMappingByAxisName"),
	AxisMappingByAxisType_1 = require("./AxisMappingByAxisType"),
	AxisRevertAll_1 = require("./AxisRevertAll"),
	AxisRevertByRevertType_1 = require("./AxisRevertByRevertType"),
	BackgroundCardAll_1 = require("./BackgroundCardAll"),
	BackgroundCardById_1 = require("./BackgroundCardById"),
	BanInfoById_1 = require("./BanInfoById"),
	BanInfoByTypeAndReason_1 = require("./BanInfoByTypeAndReason"),
	BasePropertyById_1 = require("./BasePropertyById"),
	BattlePassById_1 = require("./BattlePassById"),
	BattlePassRewardByBattlePassId_1 = require("./BattlePassRewardByBattlePassId"),
	BattlePassTaskByTaskId_1 = require("./BattlePassTaskByTaskId"),
	BattlePassUnlockPopByBattlePassTypeId_1 = require("./BattlePassUnlockPopByBattlePassTypeId"),
	BattleScoreConfById_1 = require("./BattleScoreConfById"),
	BattleScoreLevelConfByGroupId_1 = require("./BattleScoreLevelConfByGroupId"),
	BattleScoreLevelConfById_1 = require("./BattleScoreLevelConfById"),
	BeginnerGuideById_1 = require("./BeginnerGuideById"),
	BlackboardWhiteListAll_1 = require("./BlackboardWhiteListAll"),
	BlockSwitchById_1 = require("./BlockSwitchById"),
	BlueprintConfigAll_1 = require("./BlueprintConfigAll"),
	BlueprintConfigByBlueprintType_1 = require("./BlueprintConfigByBlueprintType"),
	BossRushActivityAll_1 = require("./BossRushActivityAll"),
	BossRushActivityByActivityIdAndInstanceId_1 = require("./BossRushActivityByActivityIdAndInstanceId"),
	BossRushActivityById_1 = require("./BossRushActivityById"),
	BossRushBuffAll_1 = require("./BossRushBuffAll"),
	BossRushBuffById_1 = require("./BossRushBuffById"),
	BossRushMapMarkByActivityId_1 = require("./BossRushMapMarkByActivityId"),
	BossRushScoreAll_1 = require("./BossRushScoreAll"),
	BossRushScoreById_1 = require("./BossRushScoreById"),
	BoxStateById_1 = require("./BoxStateById"),
	BoxTypeById_1 = require("./BoxTypeById"),
	BranchLineAll_1 = require("./BranchLineAll"),
	BranchLineById_1 = require("./BranchLineById"),
	BroadcastImageById_1 = require("./BroadcastImageById"),
	BubbleDataByActionGuid_1 = require("./BubbleDataByActionGuid"),
	BuffById_1 = require("./BuffById"),
	BuffItemById_1 = require("./BuffItemById"),
	BuffItemByPublicCdGroup_1 = require("./BuffItemByPublicCdGroup"),
	BuffItemCdGroupById_1 = require("./BuffItemCdGroupById"),
	BuildingAll_1 = require("./BuildingAll"),
	BuildingById_1 = require("./BuildingById"),
	BuildingUpGradeCurveByGroupId_1 = require("./BuildingUpGradeCurveByGroupId"),
	BuildingUpGradeCurveByGroupIdAndLevel_1 = require("./BuildingUpGradeCurveByGroupIdAndLevel"),
	BulletPreloadByActorBlueprintAndBulletId_1 = require("./BulletPreloadByActorBlueprintAndBulletId"),
	BulletPreloadById_1 = require("./BulletPreloadById"),
	CalabashDevelopConditionById_1 = require("./CalabashDevelopConditionById"),
	CalabashDevelopRewardAll_1 = require("./CalabashDevelopRewardAll"),
	CalabashDevelopRewardByMonsterId_1 = require("./CalabashDevelopRewardByMonsterId"),
	CalabashLevelAll_1 = require("./CalabashLevelAll"),
	CalabashLevelByLevel_1 = require("./CalabashLevelByLevel"),
	CalabashTransformById_1 = require("./CalabashTransformById"),
	CatchSignalDifficultyById_1 = require("./CatchSignalDifficultyById"),
	CatchSignalGameplayById_1 = require("./CatchSignalGameplayById"),
	CharacterAll_1 = require("./CharacterAll"),
	CharacterById_1 = require("./CharacterById"),
	CharacterAudioConfigById_1 = require("./CharacterAudioConfigById"),
	CharacterAudioConfigByIdWithDefaultId_1 = require("./CharacterAudioConfigByIdWithDefaultId"),
	ChatById_1 = require("./ChatById"),
	ChatExpressionAll_1 = require("./ChatExpressionAll"),
	ChatExpressionByGroupId_1 = require("./ChatExpressionByGroupId"),
	ChatExpressionById_1 = require("./ChatExpressionById"),
	ChatExpressionGroupAll_1 = require("./ChatExpressionGroupAll"),
	ChatExpressionGroupById_1 = require("./ChatExpressionGroupById"),
	ChildUiCameraMappingAll_1 = require("./ChildUiCameraMappingAll"),
	ChildUiCameraMappingById_1 = require("./ChildUiCameraMappingById"),
	ChildUiCameraMappingByViewName_1 = require("./ChildUiCameraMappingByViewName"),
	ChipHandBookAll_1 = require("./ChipHandBookAll"),
	ChipHandBookById_1 = require("./ChipHandBookById"),
	ChipHandBookByType_1 = require("./ChipHandBookByType"),
	ChipTypeAll_1 = require("./ChipTypeAll"),
	ChipTypeById_1 = require("./ChipTypeById"),
	CipherGameplayById_1 = require("./CipherGameplayById"),
	CircumBaseByEntryType_1 = require("./CircumBaseByEntryType"),
	CircumEntryByEntryType_1 = require("./CircumEntryByEntryType"),
	CircumFluenceTaskById_1 = require("./CircumFluenceTaskById"),
	CircumFluenceTaskByTaskType_1 = require("./CircumFluenceTaskByTaskType"),
	CircumScoreRewardAll_1 = require("./CircumScoreRewardAll"),
	CircumScoreRewardById_1 = require("./CircumScoreRewardById"),
	ClimbById_1 = require("./ClimbById"),
	ClueContentByGroupId_1 = require("./ClueContentByGroupId"),
	ClueContentById_1 = require("./ClueContentById"),
	ClueEntranceById_1 = require("./ClueEntranceById"),
	CombinationActionAll_1 = require("./CombinationActionAll"),
	CombinationActionByActionName_1 = require("./CombinationActionByActionName"),
	CombinationActionByActionType_1 = require("./CombinationActionByActionType"),
	CombinationActionById_1 = require("./CombinationActionById"),
	CombinationAxisAll_1 = require("./CombinationAxisAll"),
	CombinationAxisByAxisName_1 = require("./CombinationAxisByAxisName"),
	CombinationAxisByAxisType_1 = require("./CombinationAxisByAxisType"),
	CombinationAxisById_1 = require("./CombinationAxisById"),
	ComboTeachingById_1 = require("./ComboTeachingById"),
	ComboTeachingConditionById_1 = require("./ComboTeachingConditionById"),
	CommonRewardViewDisplayById_1 = require("./CommonRewardViewDisplayById"),
	CommonSkillPreloadAll_1 = require("./CommonSkillPreloadAll"),
	CommonSkillPreloadById_1 = require("./CommonSkillPreloadById"),
	CommunicateById_1 = require("./CommunicateById"),
	CommunityAll_1 = require("./CommunityAll"),
	CommunityById_1 = require("./CommunityById"),
	CompositeRewardDisplayById_1 = require("./CompositeRewardDisplayById"),
	ConditionById_1 = require("./ConditionById"),
	ConditionGroupById_1 = require("./ConditionGroupById"),
	ConfirmBoxById_1 = require("./ConfirmBoxById"),
	CookFixToolById_1 = require("./CookFixToolById"),
	CookFormulaAll_1 = require("./CookFormulaAll"),
	CookFormulaByFormulaItemId_1 = require("./CookFormulaByFormulaItemId"),
	CookFormulaById_1 = require("./CookFormulaById"),
	CookLevelAll_1 = require("./CookLevelAll"),
	CookLevelById_1 = require("./CookLevelById"),
	CookProcessMsgById_1 = require("./CookProcessMsgById"),
	CookProcessedAll_1 = require("./CookProcessedAll"),
	CookProcessedById_1 = require("./CookProcessedById"),
	CountryAll_1 = require("./CountryAll"),
	CountryById_1 = require("./CountryById"),
	CustomMarkAll_1 = require("./CustomMarkAll"),
	CustomMarkByMarkId_1 = require("./CustomMarkByMarkId"),
	CustomSequenceById_1 = require("./CustomSequenceById"),
	CustomSequenceLang_1 = require("./CustomSequenceLang"),
	CustomerServiceAll_1 = require("./CustomerServiceAll"),
	CustomerServiceById_1 = require("./CustomerServiceById"),
	DailyAdventureActivityByActivityId_1 = require("./DailyAdventureActivityByActivityId"),
	DailyAdventurePointById_1 = require("./DailyAdventurePointById"),
	DailyAdventureTaskByTaskId_1 = require("./DailyAdventureTaskByTaskId"),
	DailyTaskById_1 = require("./DailyTaskById"),
	DailyTaskGroupById_1 = require("./DailyTaskGroupById"),
	DamageById_1 = require("./DamageById"),
	DamagePayloadById_1 = require("./DamagePayloadById"),
	DamageTextAll_1 = require("./DamageTextAll"),
	DataLayerById_1 = require("./DataLayerById"),
	DaySelectPresetAll_1 = require("./DaySelectPresetAll"),
	DaySelectPresetById_1 = require("./DaySelectPresetById"),
	DebugCommandConfigById_1 = require("./DebugCommandConfigById"),
	DebugEntranceConfigAll_1 = require("./DebugEntranceConfigAll"),
	DebugEntranceConfigById_1 = require("./DebugEntranceConfigById"),
	DebugEntranceTypeConfigAll_1 = require("./DebugEntranceTypeConfigAll"),
	DebugEntranceTypeConfigById_1 = require("./DebugEntranceTypeConfigById"),
	DetectionTextById_1 = require("./DetectionTextById"),
	DevicePlatformById_1 = require("./DevicePlatformById"),
	DevicePlatformByPidAndVid_1 = require("./DevicePlatformByPidAndVid"),
	DeviceRenderFeatureByDeviceId_1 = require("./DeviceRenderFeatureByDeviceId"),
	DigitalScreenById_1 = require("./DigitalScreenById"),
	DigitalScreenTextById_1 = require("./DigitalScreenTextById"),
	DoubleRewardActivityById_1 = require("./DoubleRewardActivityById"),
	DragonPoolAll_1 = require("./DragonPoolAll"),
	DragonPoolById_1 = require("./DragonPoolById"),
	DropPackageById_1 = require("./DropPackageById"),
	DropShowPlanById_1 = require("./DropShowPlanById"),
	DungeonDetectionAll_1 = require("./DungeonDetectionAll"),
	DungeonDetectionByDungeonId_1 = require("./DungeonDetectionByDungeonId"),
	DungeonDetectionById_1 = require("./DungeonDetectionById"),
	DynamicMapMarkByMapId_1 = require("./DynamicMapMarkByMapId"),
	DynamicMapMarkByMarkId_1 = require("./DynamicMapMarkByMarkId"),
	EffectConfigById_1 = require("./EffectConfigById"),
	EffectSpecDataByPath_1 = require("./EffectSpecDataByPath"),
	ElementIconTagById_1 = require("./ElementIconTagById"),
	ElementInfoById_1 = require("./ElementInfoById"),
	ElementInfoById2_1 = require("./ElementInfoById2"),
	ElementLevelByLevel_1 = require("./ElementLevelByLevel"),
	ElementReactionMatrixAll_1 = require("./ElementReactionMatrixAll"),
	ElementalReactionAll_1 = require("./ElementalReactionAll"),
	ElementalReactionByReactionId_1 = require("./ElementalReactionByReactionId"),
	EntityAudioConfigById_1 = require("./EntityAudioConfigById"),
	EntityAudioConfigByIdWithZero_1 = require("./EntityAudioConfigByIdWithZero"),
	EntityOwnerDataByGuid_1 = require("./EntityOwnerDataByGuid"),
	EntitySkillPreloadByActorBlueprintAndSkillId_1 = require("./EntitySkillPreloadByActorBlueprintAndSkillId"),
	EntitySkillPreloadById_1 = require("./EntitySkillPreloadById"),
	EntityVoxelInfoByMapIdAndEntityId_1 = require("./EntityVoxelInfoByMapIdAndEntityId"),
	EntranceIconTagById_1 = require("./EntranceIconTagById"),
	EntrustFinishDialogByEntrustIdAndLevel_1 = require("./EntrustFinishDialogByEntrustIdAndLevel"),
	EntrustRoleAll_1 = require("./EntrustRoleAll"),
	EntrustRoleById_1 = require("./EntrustRoleById"),
	EntrustTypeById_1 = require("./EntrustTypeById"),
	ErrorCodeById_1 = require("./ErrorCodeById"),
	EvaluateById_1 = require("./EvaluateById"),
	ExchangeRewardById_1 = require("./ExchangeRewardById"),
	ExchangeSharedById_1 = require("./ExchangeSharedById"),
	ExecutionConfById_1 = require("./ExecutionConfById"),
	ExploreProgressAll_1 = require("./ExploreProgressAll"),
	ExploreProgressByArea_1 = require("./ExploreProgressByArea"),
	ExploreProgressById_1 = require("./ExploreProgressById"),
	ExploreRewardByCountry_1 = require("./ExploreRewardByCountry"),
	ExploreRewardById_1 = require("./ExploreRewardById"),
	ExploreRewardDisplayById_1 = require("./ExploreRewardDisplayById"),
	ExploreScoreAll_1 = require("./ExploreScoreAll"),
	ExploreScoreByArea_1 = require("./ExploreScoreByArea"),
	ExploreToolsAll_1 = require("./ExploreToolsAll"),
	ExploreToolsByPhantomSkillId_1 = require("./ExploreToolsByPhantomSkillId"),
	ExternalSourceSettingById_1 = require("./ExternalSourceSettingById"),
	FaceExpressionDataById_1 = require("./FaceExpressionDataById"),
	FavorGoodsByRoleId_1 = require("./FavorGoodsByRoleId"),
	FavorLevelByLevel_1 = require("./FavorLevelByLevel"),
	FavorRoleInfoByRoleId_1 = require("./FavorRoleInfoByRoleId"),
	FavorStoryByRoleId_1 = require("./FavorStoryByRoleId"),
	FavorTabCameraById_1 = require("./FavorTabCameraById"),
	FavorWordByRoleIdAndType_1 = require("./FavorWordByRoleIdAndType"),
	FeedingAnimalById_1 = require("./FeedingAnimalById"),
	FightFormationById_1 = require("./FightFormationById"),
	FilterById_1 = require("./FilterById"),
	FilterRuleById_1 = require("./FilterRuleById"),
	FilterSortGroupById_1 = require("./FilterSortGroupById"),
	FlowById_1 = require("./FlowById"),
	FlowStateByStateKey_1 = require("./FlowStateByStateKey"),
	FlowTemplateDataById_1 = require("./FlowTemplateDataById"),
	FlowTextByIdAndFlowListId_1 = require("./FlowTextByIdAndFlowListId"),
	FlowTextLang_1 = require("./FlowTextLang"),
	FogBlockAll_1 = require("./FogBlockAll"),
	FogBlockByBlock_1 = require("./FogBlockByBlock"),
	FogTextureConfigAll_1 = require("./FogTextureConfigAll"),
	FogTextureConfigByBlock_1 = require("./FogTextureConfigByBlock"),
	FoleySynthBoneConfigById_1 = require("./FoleySynthBoneConfigById"),
	FoleySynthConfigById_1 = require("./FoleySynthConfigById"),
	FoleySynthConfigByIdWithDefaultId_1 = require("./FoleySynthConfigByIdWithDefaultId"),
	ForgeFormulaAll_1 = require("./ForgeFormulaAll"),
	ForgeFormulaByFormulaItemId_1 = require("./ForgeFormulaByFormulaItemId"),
	ForgeFormulaById_1 = require("./ForgeFormulaById"),
	ForgeFormulaByTypeId_1 = require("./ForgeFormulaByTypeId"),
	FormationPropertyAll_1 = require("./FormationPropertyAll"),
	FormationPropertyById_1 = require("./FormationPropertyById"),
	FriendFilterAll_1 = require("./FriendFilterAll"),
	FuncMenuWheelAll_1 = require("./FuncMenuWheelAll"),
	FuncMenuWheelByFuncId_1 = require("./FuncMenuWheelByFuncId"),
	FunctionConditionByFunctionId_1 = require("./FunctionConditionByFunctionId"),
	FunctionMenuAll_1 = require("./FunctionMenuAll"),
	FunctionMenuByFunctionId_1 = require("./FunctionMenuByFunctionId"),
	FunctionOpenViewLimitAll_1 = require("./FunctionOpenViewLimitAll"),
	GaChaShareById_1 = require("./GaChaShareById"),
	GachaAll_1 = require("./GachaAll"),
	GachaById_1 = require("./GachaById"),
	GachaEffectConfigByTimesAndQuality_1 = require("./GachaEffectConfigByTimesAndQuality"),
	GachaPoolById_1 = require("./GachaPoolById"),
	GachaSequenceConfigById_1 = require("./GachaSequenceConfigById"),
	GachaTextureInfoById_1 = require("./GachaTextureInfoById"),
	GachaViewInfoById_1 = require("./GachaViewInfoById"),
	GachaViewTypeInfoByType_1 = require("./GachaViewTypeInfoByType"),
	GachaWeaponTransformById_1 = require("./GachaWeaponTransformById"),
	GamePlayInformationGroupById_1 = require("./GamePlayInformationGroupById"),
	GamePlayInformationInfoById_1 = require("./GamePlayInformationInfoById"),
	GamePlayScanByUid_1 = require("./GamePlayScanByUid"),
	GamePlayScanCompositeByUid_1 = require("./GamePlayScanCompositeByUid"),
	GamepadKeyById_1 = require("./GamepadKeyById"),
	GamepadKeyByKeyName_1 = require("./GamepadKeyByKeyName"),
	GameplayCueById_1 = require("./GameplayCueById"),
	GatherActivityAll_1 = require("./GatherActivityAll"),
	GatherActivityById_1 = require("./GatherActivityById"),
	GenderTextByMaleText_1 = require("./GenderTextByMaleText"),
	GeneralActionById_1 = require("./GeneralActionById"),
	GeneralActionGroupById_1 = require("./GeneralActionGroupById"),
	GenericPromptByTipsId_1 = require("./GenericPromptByTipsId"),
	GenericPromptTypesByTypeId_1 = require("./GenericPromptTypesByTypeId"),
	GeographyHandBookAll_1 = require("./GeographyHandBookAll"),
	GeographyHandBookById_1 = require("./GeographyHandBookById"),
	GeographyHandBookByType_1 = require("./GeographyHandBookByType"),
	GeographyTypeAll_1 = require("./GeographyTypeAll"),
	GeographyTypeById_1 = require("./GeographyTypeById"),
	GiftPackageById_1 = require("./GiftPackageById"),
	GlobalConfigFromCsvByName_1 = require("./GlobalConfigFromCsvByName"),
	GmAccountAll_1 = require("./GmAccountAll"),
	GmAccountById_1 = require("./GmAccountById"),
	GmOrderConfigAll_1 = require("./GmOrderConfigAll"),
	GmOrderListAll_1 = require("./GmOrderListAll"),
	GmOrderListById_1 = require("./GmOrderListById"),
	GuideDataById_1 = require("./GuideDataById"),
	GuideFocusNewByGuideId_1 = require("./GuideFocusNewByGuideId"),
	GuideGroupAll_1 = require("./GuideGroupAll"),
	GuideGroupById_1 = require("./GuideGroupById"),
	GuideStepAll_1 = require("./GuideStepAll"),
	GuideStepById_1 = require("./GuideStepById"),
	GuideTipsByGuideId_1 = require("./GuideTipsByGuideId"),
	GuideTutorialAll_1 = require("./GuideTutorialAll"),
	GuideTutorialById_1 = require("./GuideTutorialById"),
	GuideTutorialPageById_1 = require("./GuideTutorialPageById"),
	HandBookEntranceAll_1 = require("./HandBookEntranceAll"),
	HandBookEntranceById_1 = require("./HandBookEntranceById"),
	HandBookQuestTabAll_1 = require("./HandBookQuestTabAll"),
	HandBookQuestTabById_1 = require("./HandBookQuestTabById"),
	HardnessModeById_1 = require("./HardnessModeById"),
	HeadIconById_1 = require("./HeadIconById"),
	HelpTextByGroupId_1 = require("./HelpTextByGroupId"),
	HelpTextById_1 = require("./HelpTextById"),
	HotKeyIconByKeyName_1 = require("./HotKeyIconByKeyName"),
	HotKeyMapById_1 = require("./HotKeyMapById"),
	HotKeyTextByTextId_1 = require("./HotKeyTextByTextId"),
	HotKeyTypeById_1 = require("./HotKeyTypeById"),
	HotKeyViewById_1 = require("./HotKeyViewById"),
	HotPatchTextLang_1 = require("./HotPatchTextLang"),
	InfluenceAll_1 = require("./InfluenceAll"),
	InfluenceById_1 = require("./InfluenceById"),
	InfoDisplayById_1 = require("./InfoDisplayById"),
	InstanceDungeonAll_1 = require("./InstanceDungeonAll"),
	InstanceDungeonById_1 = require("./InstanceDungeonById"),
	InstanceDungeonEntranceAll_1 = require("./InstanceDungeonEntranceAll"),
	InstanceDungeonEntranceById_1 = require("./InstanceDungeonEntranceById"),
	InstanceDungeonEntranceByMarkId_1 = require("./InstanceDungeonEntranceByMarkId"),
	InstanceDungeonTitleById_1 = require("./InstanceDungeonTitleById"),
	InstanceEnterControlById_1 = require("./InstanceEnterControlById"),
	InstanceTrialRoleConfigById_1 = require("./InstanceTrialRoleConfigById"),
	InteractAudioMaterialByCollisionMaterial_1 = require("./InteractAudioMaterialByCollisionMaterial"),
	InteractBackGroundById_1 = require("./InteractBackGroundById"),
	InteractBackGroundByViewName_1 = require("./InteractBackGroundByViewName"),
	InteractDataByGuid_1 = require("./InteractDataByGuid"),
	InterjectionByTimberIdAndUniversalToneId_1 = require("./InterjectionByTimberIdAndUniversalToneId"),
	ItemExchangeContentAll_1 = require("./ItemExchangeContentAll"),
	ItemExchangeContentByItemId_1 = require("./ItemExchangeContentByItemId"),
	ItemExchangeLimitByItemId_1 = require("./ItemExchangeLimitByItemId"),
	ItemHandBookAll_1 = require("./ItemHandBookAll"),
	ItemHandBookById_1 = require("./ItemHandBookById"),
	ItemHandBookByType_1 = require("./ItemHandBookByType"),
	ItemHandBookTypeAll_1 = require("./ItemHandBookTypeAll"),
	ItemHandBookTypeById_1 = require("./ItemHandBookTypeById"),
	ItemIconTagById_1 = require("./ItemIconTagById"),
	ItemInfoAll_1 = require("./ItemInfoAll"),
	ItemInfoById_1 = require("./ItemInfoById"),
	ItemInfoByItemType_1 = require("./ItemInfoByItemType"),
	ItemMainTypeAll_1 = require("./ItemMainTypeAll"),
	ItemMainTypeById_1 = require("./ItemMainTypeById"),
	ItemShowTypeById_1 = require("./ItemShowTypeById"),
	KeySettingAll_1 = require("./KeySettingAll"),
	KeySettingById_1 = require("./KeySettingById"),
	KeySettingByTypeId_1 = require("./KeySettingByTypeId"),
	KeySettingByTypeIdAndInputControllerType_1 = require("./KeySettingByTypeIdAndInputControllerType"),
	KeyTypeAll_1 = require("./KeyTypeAll"),
	KeyTypeByTypeId_1 = require("./KeyTypeByTypeId"),
	KillMonstersScoresByInstanceID_1 = require("./KillMonstersScoresByInstanceID"),
	LangOfLogoByName_1 = require("./LangOfLogoByName"),
	LanguageDefineByLanguageCode_1 = require("./LanguageDefineByLanguageCode"),
	LanguageDefineByLanguageType_1 = require("./LanguageDefineByLanguageType"),
	LevelEntityConfigByBlueprintType_1 = require("./LevelEntityConfigByBlueprintType"),
	LevelEntityConfigByMapIdAndEntityId_1 = require("./LevelEntityConfigByMapIdAndEntityId"),
	LevelPlayDataById_1 = require("./LevelPlayDataById"),
	LevelPlayNodeDataByKey_1 = require("./LevelPlayNodeDataByKey"),
	LivenessAll_1 = require("./LivenessAll"),
	LivenessById_1 = require("./LivenessById"),
	LivenessTaskByTaskId_1 = require("./LivenessTaskByTaskId"),
	LoadingLevelAreaAll_1 = require("./LoadingLevelAreaAll"),
	LoadingTipsTextAll_1 = require("./LoadingTipsTextAll"),
	LoadingTipsTextById_1 = require("./LoadingTipsTextById"),
	LoadingTipsTextByLevelAreaId_1 = require("./LoadingTipsTextByLevelAreaId"),
	LockOnConfigById_1 = require("./LockOnConfigById"),
	LongPressConfigById_1 = require("./LongPressConfigById"),
	LongShanStageAll_1 = require("./LongShanStageAll"),
	LongShanStageById_1 = require("./LongShanStageById"),
	LongShanTaskById_1 = require("./LongShanTaskById"),
	LordGymAll_1 = require("./LordGymAll"),
	LordGymByDifficulty_1 = require("./LordGymByDifficulty"),
	LordGymById_1 = require("./LordGymById"),
	LordGymEntranceAll_1 = require("./LordGymEntranceAll"),
	LordGymEntranceById_1 = require("./LordGymEntranceById"),
	LordGymEntranceByMarkId_1 = require("./LordGymEntranceByMarkId"),
	LordGymFilterTypeAll_1 = require("./LordGymFilterTypeAll"),
	LordGymFilterTypeById_1 = require("./LordGymFilterTypeById"),
	MailFilterAll_1 = require("./MailFilterAll"),
	MailFilterById_1 = require("./MailFilterById"),
	MainLineAll_1 = require("./MainLineAll"),
	MainLineById_1 = require("./MainLineById"),
	MainRoleConfigAll_1 = require("./MainRoleConfigAll"),
	MainRoleConfigByGender_1 = require("./MainRoleConfigByGender"),
	MainRoleConfigById_1 = require("./MainRoleConfigById"),
	MainTypeAll_1 = require("./MainTypeAll"),
	MainTypeById_1 = require("./MainTypeById"),
	MapAudioById_1 = require("./MapAudioById"),
	MapBorderAll_1 = require("./MapBorderAll"),
	MapBorderByBorderId_1 = require("./MapBorderByBorderId"),
	MapMarkByEntityConfigId_1 = require("./MapMarkByEntityConfigId"),
	MapMarkByMapId_1 = require("./MapMarkByMapId"),
	MapMarkByMarkId_1 = require("./MapMarkByMarkId"),
	MapMarkByRelativeMainSubType_1 = require("./MapMarkByRelativeMainSubType"),
	MapMarkHasEntityConfigId_1 = require("./MapMarkHasEntityConfigId"),
	MapMarkPhantomGroupByMarkId_1 = require("./MapMarkPhantomGroupByMarkId"),
	MapMarkRelativeSubTypeAll_1 = require("./MapMarkRelativeSubTypeAll"),
	MapMarkRelativeSubTypeByFunctionId_1 = require("./MapMarkRelativeSubTypeByFunctionId"),
	MapMarkRelativeSubTypeById_1 = require("./MapMarkRelativeSubTypeById"),
	MapNoteById_1 = require("./MapNoteById"),
	MappingBySheetNameAndFieldName_1 = require("./MappingBySheetNameAndFieldName"),
	MappingBySheetNameFieldNameAndValue_1 = require("./MappingBySheetNameFieldNameAndValue"),
	MarkEffectByMarkId_1 = require("./MarkEffectByMarkId"),
	MenuConfigAll_1 = require("./MenuConfigAll"),
	MenuConfigByFunctionId_1 = require("./MenuConfigByFunctionId"),
	MobileBattleUiSetAll_1 = require("./MobileBattleUiSetAll"),
	MobileBattleUiSetByPanelIndex_1 = require("./MobileBattleUiSetByPanelIndex"),
	ModelConfigPreloadById_1 = require("./ModelConfigPreloadById"),
	MonitorActionById_1 = require("./MonitorActionById"),
	MonsterBattleConfById_1 = require("./MonsterBattleConfById"),
	MonsterBodyTypeConfigById_1 = require("./MonsterBodyTypeConfigById"),
	MonsterDetectionAll_1 = require("./MonsterDetectionAll"),
	MonsterDetectionById_1 = require("./MonsterDetectionById"),
	MonsterDetectionFilterAll_1 = require("./MonsterDetectionFilterAll"),
	MonsterDisplayById_1 = require("./MonsterDisplayById"),
	MonsterDisplayLang_1 = require("./MonsterDisplayLang"),
	MonsterHandBookAll_1 = require("./MonsterHandBookAll"),
	MonsterHandBookById_1 = require("./MonsterHandBookById"),
	MonsterHandBookByType_1 = require("./MonsterHandBookByType"),
	MonsterHandBookTypeAll_1 = require("./MonsterHandBookTypeAll"),
	MonsterIconTagById_1 = require("./MonsterIconTagById"),
	MonsterInfoById_1 = require("./MonsterInfoById"),
	MonsterPerchById_1 = require("./MonsterPerchById"),
	MonsterPropertyGrowthById_1 = require("./MonsterPropertyGrowthById"),
	MonsterRarityById_1 = require("./MonsterRarityById"),
	MonsterSizeIdById_1 = require("./MonsterSizeIdById"),
	MontageDataById_1 = require("./MontageDataById"),
	MonthCardContentById_1 = require("./MonthCardContentById"),
	MotionById_1 = require("./MotionById"),
	MotionByRoleId_1 = require("./MotionByRoleId"),
	MotionByRoleIdAndType_1 = require("./MotionByRoleIdAndType"),
	MultiMapAll_1 = require("./MultiMapAll"),
	MultiMapByGroupId_1 = require("./MultiMapByGroupId"),
	MultiMapById_1 = require("./MultiMapById"),
	MultiMapAreaConfigAll_1 = require("./MultiMapAreaConfigAll"),
	MultiMapAreaConfigByBlock_1 = require("./MultiMapAreaConfigByBlock"),
	MultiTextLang_1 = require("./MultiTextLang"),
	NewOccupationConfigAll_1 = require("./NewOccupationConfigAll"),
	NewOccupationConfigById_1 = require("./NewOccupationConfigById"),
	NewbieCourseAll_1 = require("./NewbieCourseAll"),
	NewbieCourseById_1 = require("./NewbieCourseById"),
	NpcHeadInfoById_1 = require("./NpcHeadInfoById"),
	NpcSystemBackgroundById_1 = require("./NpcSystemBackgroundById"),
	NpcSystemBackgroundByViewName_1 = require("./NpcSystemBackgroundByViewName"),
	OccupationConfigById_1 = require("./OccupationConfigById"),
	OccupationConfigLang_1 = require("./OccupationConfigLang"),
	OpenAndCloseViewHotKeyAll_1 = require("./OpenAndCloseViewHotKeyAll"),
	OpenAndCloseViewHotKeyByActionName_1 = require("./OpenAndCloseViewHotKeyByActionName"),
	OpenAndCloseViewHotKeyByInputControllerType_1 = require("./OpenAndCloseViewHotKeyByInputControllerType"),
	OverlayAbpMontageDataById_1 = require("./OverlayAbpMontageDataById"),
	PackageCapacityAll_1 = require("./PackageCapacityAll"),
	PackageCapacityByPackageId_1 = require("./PackageCapacityByPackageId"),
	ParkourChallengeById_1 = require("./ParkourChallengeById"),
	ParkourChallengeByMarkId_1 = require("./ParkourChallengeByMarkId"),
	PassiveSkillById_1 = require("./PassiveSkillById"),
	PayById_1 = require("./PayById"),
	PayByPayIdAndRegion_1 = require("./PayByPayIdAndRegion"),
	PayByRegion_1 = require("./PayByRegion"),
	PayItemAll_1 = require("./PayItemAll"),
	PayItemById_1 = require("./PayItemById"),
	PayShopAll_1 = require("./PayShopAll"),
	PayShopById_1 = require("./PayShopById"),
	PayShopConditionById_1 = require("./PayShopConditionById"),
	PayShopDirectGoodsByGoodsId_1 = require("./PayShopDirectGoodsByGoodsId"),
	PayShopGoodsById_1 = require("./PayShopGoodsById"),
	PayShopGoodsByItemId_1 = require("./PayShopGoodsByItemId"),
	PayShopTabByShopId_1 = require("./PayShopTabByShopId"),
	PayShopTabByShopIdAndTabId_1 = require("./PayShopTabByShopIdAndTabId"),
	PcKeyById_1 = require("./PcKeyById"),
	PcKeyByKeyName_1 = require("./PcKeyByKeyName"),
	PersonalTipsByFunctionId_1 = require("./PersonalTipsByFunctionId"),
	PersonalTipsById_1 = require("./PersonalTipsById"),
	PhantomCollectActivityById_1 = require("./PhantomCollectActivityById"),
	PhantomCollectTaskDescById_1 = require("./PhantomCollectTaskDescById"),
	PhantomCustomizeItemByItemId_1 = require("./PhantomCustomizeItemByItemId"),
	PhantomExpItemAll_1 = require("./PhantomExpItemAll"),
	PhantomExpItemByItemId_1 = require("./PhantomExpItemByItemId"),
	PhantomFetterAll_1 = require("./PhantomFetterAll"),
	PhantomFetterById_1 = require("./PhantomFetterById"),
	PhantomFetterGroupAll_1 = require("./PhantomFetterGroupAll"),
	PhantomFetterGroupById_1 = require("./PhantomFetterGroupById"),
	PhantomFetterHandBookAll_1 = require("./PhantomFetterHandBookAll"),
	PhantomGrowthByGrowthIdAndLevel_1 = require("./PhantomGrowthByGrowthIdAndLevel"),
	PhantomHandBookAll_1 = require("./PhantomHandBookAll"),
	PhantomHandBookById_1 = require("./PhantomHandBookById"),
	PhantomHandBookPageAll_1 = require("./PhantomHandBookPageAll"),
	PhantomItemAll_1 = require("./PhantomItemAll"),
	PhantomItemByItemId_1 = require("./PhantomItemByItemId"),
	PhantomItemByMonsterId_1 = require("./PhantomItemByMonsterId"),
	PhantomLevelByGroupId_1 = require("./PhantomLevelByGroupId"),
	PhantomLevelByGroupIdAndLevel_1 = require("./PhantomLevelByGroupIdAndLevel"),
	PhantomMainPropItemById_1 = require("./PhantomMainPropItemById"),
	PhantomMainPropertyById_1 = require("./PhantomMainPropertyById"),
	PhantomQualityByQuality_1 = require("./PhantomQualityByQuality"),
	PhantomRarityByRare_1 = require("./PhantomRarityByRare"),
	PhantomSkillById_1 = require("./PhantomSkillById"),
	PhantomSkillByPhantomSkillId_1 = require("./PhantomSkillByPhantomSkillId"),
	PhantomSubPropertyById_1 = require("./PhantomSubPropertyById"),
	PhantomSubPropertyByPropId_1 = require("./PhantomSubPropertyByPropId"),
	PhantomWildItemAll_1 = require("./PhantomWildItemAll"),
	PhantomWildItemByItemId_1 = require("./PhantomWildItemByItemId"),
	PhotoMemoryActivityById_1 = require("./PhotoMemoryActivityById"),
	PhotoMemoryCollectById_1 = require("./PhotoMemoryCollectById"),
	PhotoMemoryCollectByTopicID_1 = require("./PhotoMemoryCollectByTopicID"),
	PhotoMemoryTopicAll_1 = require("./PhotoMemoryTopicAll"),
	PhotoMemoryTopicById_1 = require("./PhotoMemoryTopicById"),
	PhotoMontageById_1 = require("./PhotoMontageById"),
	PhotoMontageByRoleId_1 = require("./PhotoMontageByRoleId"),
	PhotoSetupAll_1 = require("./PhotoSetupAll"),
	PhotoSetupByValueType_1 = require("./PhotoSetupByValueType"),
	PhotographHandBookAll_1 = require("./PhotographHandBookAll"),
	PhotographHandBookById_1 = require("./PhotographHandBookById"),
	PhotographHandBookByType_1 = require("./PhotographHandBookByType"),
	PhysicsAssetConfigById_1 = require("./PhysicsAssetConfigById"),
	PhysicsAssetConfigByIdWithDefaultId_1 = require("./PhysicsAssetConfigByIdWithDefaultId"),
	PlatformIconById_1 = require("./PlatformIconById"),
	PlayerExpByPlayerLevel_1 = require("./PlayerExpByPlayerLevel"),
	PlayerExpByPlayerLevelArea_1 = require("./PlayerExpByPlayerLevelArea"),
	PlayerStateRestrictionById_1 = require("./PlayerStateRestrictionById"),
	PlotAudioById_1 = require("./PlotAudioById"),
	PlotHandBookConfigAll_1 = require("./PlotHandBookConfigAll"),
	PlotHandBookConfigByQuestId_1 = require("./PlotHandBookConfigByQuestId"),
	PlotTypeAll_1 = require("./PlotTypeAll"),
	PlotTypeById_1 = require("./PlotTypeById"),
	PopularityAll_1 = require("./PopularityAll"),
	PrefabConfigById_1 = require("./PrefabConfigById"),
	PrefabTextItemAll_1 = require("./PrefabTextItemAll"),
	PrefabTextItemByItemId_1 = require("./PrefabTextItemByItemId"),
	PrefabTextItemByPrefabPathHash_1 = require("./PrefabTextItemByPrefabPathHash"),
	PreviewItemAll_1 = require("./PreviewItemAll"),
	PreviewItemById_1 = require("./PreviewItemById"),
	PropRewardConfById_1 = require("./PropRewardConfById"),
	PropertyIndexAll_1 = require("./PropertyIndexAll"),
	PropertyIndexById_1 = require("./PropertyIndexById"),
	QualityIconTagById_1 = require("./QualityIconTagById"),
	QualityInfoAll_1 = require("./QualityInfoAll"),
	QualityInfoById_1 = require("./QualityInfoById"),
	QuestById_1 = require("./QuestById"),
	QuestChapterById_1 = require("./QuestChapterById"),
	QuestDataById_1 = require("./QuestDataById"),
	QuestMainTypeById_1 = require("./QuestMainTypeById"),
	QuestNodeDataByKey_1 = require("./QuestNodeDataByKey"),
	QuestTagById_1 = require("./QuestTagById"),
	QuestTypeAll_1 = require("./QuestTypeAll"),
	QuestTypeById_1 = require("./QuestTypeById"),
	QuestTypeByMainId_1 = require("./QuestTypeByMainId"),
	QuickChatAll_1 = require("./QuickChatAll"),
	RecordConfigById_1 = require("./RecordConfigById"),
	RedDotByRelativeName_1 = require("./RedDotByRelativeName"),
	RegressRewardsById_1 = require("./RegressRewardsById"),
	ReportPlayerInfoAll_1 = require("./ReportPlayerInfoAll"),
	ResonantChainByGroupId_1 = require("./ResonantChainByGroupId"),
	ResonantChainByGroupIdAndGroupIndex_1 = require("./ResonantChainByGroupIdAndGroupIndex"),
	ResonantChainByGroupIdAndNodeType_1 = require("./ResonantChainByGroupIdAndNodeType"),
	ResonantChainById_1 = require("./ResonantChainById"),
	ReviveById_1 = require("./ReviveById"),
	RewardConfigById_1 = require("./RewardConfigById"),
	RewardViewFromSourceAll_1 = require("./RewardViewFromSourceAll"),
	RewardViewFromSourceBySourceId_1 = require("./RewardViewFromSourceBySourceId"),
	RogueActivityById_1 = require("./RogueActivityById"),
	RogueAffixById_1 = require("./RogueAffixById"),
	RogueBuffPoolById_1 = require("./RogueBuffPoolById"),
	RogueCharacterById_1 = require("./RogueCharacterById"),
	RogueCharacterBuffById_1 = require("./RogueCharacterBuffById"),
	RogueCurrencyById_1 = require("./RogueCurrencyById"),
	RogueEffectById_1 = require("./RogueEffectById"),
	RogueEventById_1 = require("./RogueEventById"),
	RogueParamById_1 = require("./RogueParamById"),
	RoguePokemonById_1 = require("./RoguePokemonById"),
	RoguePopularEntrieArgAll_1 = require("./RoguePopularEntrieArgAll"),
	RoguePopularEntrieArgById_1 = require("./RoguePopularEntrieArgById"),
	RoguePopularEntrieArgBySeasonIdAndInstId_1 = require("./RoguePopularEntrieArgBySeasonIdAndInstId"),
	RogueQualityConfigById_1 = require("./RogueQualityConfigById"),
	RogueRoomPoolByBehaviorTree_1 = require("./RogueRoomPoolByBehaviorTree"),
	RogueRoomShowConfigById_1 = require("./RogueRoomShowConfigById"),
	RogueRoomTypeById_1 = require("./RogueRoomTypeById"),
	RogueSeasonAll_1 = require("./RogueSeasonAll"),
	RogueSeasonById_1 = require("./RogueSeasonById"),
	RogueSeasonRewardBySeasonId_1 = require("./RogueSeasonRewardBySeasonId"),
	RogueTalentTreeAll_1 = require("./RogueTalentTreeAll"),
	RogueTalentTreeById_1 = require("./RogueTalentTreeById"),
	RogueTalentTreeDescById_1 = require("./RogueTalentTreeDescById"),
	RogueTokenBySeasonId_1 = require("./RogueTokenBySeasonId"),
	RoleAnimAudioByRoleId_1 = require("./RoleAnimAudioByRoleId"),
	RoleAudioById_1 = require("./RoleAudioById"),
	RoleAudioRulesById_1 = require("./RoleAudioRulesById"),
	RoleBattleViewInfoAll_1 = require("./RoleBattleViewInfoAll"),
	RoleBattleViewInfoById_1 = require("./RoleBattleViewInfoById"),
	RoleBreachByBreachGroupId_1 = require("./RoleBreachByBreachGroupId"),
	RoleBreachByBreachGroupIdAndBreachLevel_1 = require("./RoleBreachByBreachGroupIdAndBreachLevel"),
	RoleDescriptionById_1 = require("./RoleDescriptionById"),
	RoleDevelopCurveByGroupId_1 = require("./RoleDevelopCurveByGroupId"),
	RoleDevelopTypeById_1 = require("./RoleDevelopTypeById"),
	RoleExpItemAll_1 = require("./RoleExpItemAll"),
	RoleExpItemById_1 = require("./RoleExpItemById"),
	RoleGuideActivityById_1 = require("./RoleGuideActivityById"),
	RoleIconTagById_1 = require("./RoleIconTagById"),
	RoleInfluenceAll_1 = require("./RoleInfluenceAll"),
	RoleInfluenceById_1 = require("./RoleInfluenceById"),
	RoleInfoAll_1 = require("./RoleInfoAll"),
	RoleInfoById_1 = require("./RoleInfoById"),
	RoleInfoByRoleType_1 = require("./RoleInfoByRoleType"),
	RoleLevelConsumeByConsumeGroupIdAndLevel_1 = require("./RoleLevelConsumeByConsumeGroupIdAndLevel"),
	RolePropertyGrowthByLevelAndBreachLevel_1 = require("./RolePropertyGrowthByLevelAndBreachLevel"),
	RoleQualityInfoById_1 = require("./RoleQualityInfoById"),
	RoleQuestById_1 = require("./RoleQuestById"),
	RoleQuestByRoleId_1 = require("./RoleQuestByRoleId"),
	RoleQuestByRoleIdAll_1 = require("./RoleQuestByRoleIdAll"),
	RoleSkillInputById_1 = require("./RoleSkillInputById"),
	RoleTagAll_1 = require("./RoleTagAll"),
	RoleTagById_1 = require("./RoleTagById"),
	RoleTrainingDegreeByDifficultyLevel_1 = require("./RoleTrainingDegreeByDifficultyLevel"),
	RoleTrialActivityById_1 = require("./RoleTrialActivityById"),
	RoleTrialInfoById_1 = require("./RoleTrialInfoById"),
	RougeMiraclecreationById_1 = require("./RougeMiraclecreationById"),
	RougePopularEntrieAll_1 = require("./RougePopularEntrieAll"),
	RougePopularEntrieById_1 = require("./RougePopularEntrieById"),
	ScoreRewardById_1 = require("./ScoreRewardById"),
	SecondaryGuideDataById_1 = require("./SecondaryGuideDataById"),
	SetAccountAll_1 = require("./SetAccountAll"),
	SetAccountById_1 = require("./SetAccountById"),
	SharePlatformAll_1 = require("./SharePlatformAll"),
	SharePlatformById_1 = require("./SharePlatformById"),
	ShareRewardById_1 = require("./ShareRewardById"),
	ShieldById_1 = require("./ShieldById"),
	ShopFixedByShopId_1 = require("./ShopFixedByShopId"),
	ShopFixedByShopIdAndId_1 = require("./ShopFixedByShopIdAndId"),
	ShopInfoById_1 = require("./ShopInfoById"),
	SignRewardByActivityId_1 = require("./SignRewardByActivityId"),
	SignalDecodeGamePlayById_1 = require("./SignalDecodeGamePlayById"),
	SignalDecodeTabColorById_1 = require("./SignalDecodeTabColorById"),
	SignalDecodeWaveformById_1 = require("./SignalDecodeWaveformById"),
	SilentAreaDetectionAll_1 = require("./SilentAreaDetectionAll"),
	SilentAreaDetectionById_1 = require("./SilentAreaDetectionById"),
	SkillById_1 = require("./SkillById"),
	SkillBySkillGroupId_1 = require("./SkillBySkillGroupId"),
	SkillButtonByRoleId_1 = require("./SkillButtonByRoleId"),
	SkillButtonEffectById_1 = require("./SkillButtonEffectById"),
	SkillButtonIndexById_1 = require("./SkillButtonIndexById"),
	SkillButtonTextAll_1 = require("./SkillButtonTextAll"),
	SkillButtonTextById_1 = require("./SkillButtonTextById"),
	SkillCommonButtonAll_1 = require("./SkillCommonButtonAll"),
	SkillConditionById_1 = require("./SkillConditionById"),
	SkillDescriptionById_1 = require("./SkillDescriptionById"),
	SkillDescriptionBySkillLevelGroupId_1 = require("./SkillDescriptionBySkillLevelGroupId"),
	SkillIconByTag_1 = require("./SkillIconByTag"),
	SkillInputById_1 = require("./SkillInputById"),
	SkillLevelBySkillLevelGroupId_1 = require("./SkillLevelBySkillLevelGroupId"),
	SkillLevelBySkillLevelGroupIdAndSkillId_1 = require("./SkillLevelBySkillLevelGroupIdAndSkillId"),
	SkillTagById_1 = require("./SkillTagById"),
	SkillTreeById_1 = require("./SkillTreeById"),
	SkillTreeByNodeGroup_1 = require("./SkillTreeByNodeGroup"),
	SkillTreeByNodeGroupAndNodeIndex_1 = require("./SkillTreeByNodeGroupAndNodeIndex"),
	SkillTreeByNodeIndex_1 = require("./SkillTreeByNodeIndex"),
	SkillTypeById_1 = require("./SkillTypeById"),
	SkyboxById_1 = require("./SkyboxById"),
	SlideById_1 = require("./SlideById"),
	SortById_1 = require("./SortById"),
	SortRuleByIdAndDataId_1 = require("./SortRuleByIdAndDataId"),
	SoundAreaPlayInfoAll_1 = require("./SoundAreaPlayInfoAll"),
	SoundAreaPlayInfoById_1 = require("./SoundAreaPlayInfoById"),
	SoundBoxMarkByMarkId_1 = require("./SoundBoxMarkByMarkId"),
	SpeakerById_1 = require("./SpeakerById"),
	SpeakerLang_1 = require("./SpeakerLang"),
	SpecialHateAndSenseById_1 = require("./SpecialHateAndSenseById"),
	SpecialItemById_1 = require("./SpecialItemById"),
	StateMachinePreloadByFsmKey_1 = require("./StateMachinePreloadByFsmKey"),
	StateMachinePreloadById_1 = require("./StateMachinePreloadById"),
	SubtitleTextByRowNameAndDatatableName_1 = require("./SubtitleTextByRowNameAndDatatableName"),
	SubtitleTextLang_1 = require("./SubtitleTextLang"),
	SummonCfgById_1 = require("./SummonCfgById"),
	SwimById_1 = require("./SwimById"),
	SwimBuffById_1 = require("./SwimBuffById"),
	SynthesisFormulaByFormulaItemId_1 = require("./SynthesisFormulaByFormulaItemId"),
	SynthesisFormulaByFormulaType_1 = require("./SynthesisFormulaByFormulaType"),
	SynthesisFormulaById_1 = require("./SynthesisFormulaById"),
	SynthesisLevelAll_1 = require("./SynthesisLevelAll"),
	TakeWeedsDifficultyById_1 = require("./TakeWeedsDifficultyById"),
	TalkOptionIconById_1 = require("./TalkOptionIconById"),
	TaskMarkByMarkId_1 = require("./TaskMarkByMarkId"),
	TeamConfigById_1 = require("./TeamConfigById"),
	TeleporterById_1 = require("./TeleporterById"),
	TemplateConfigAll_1 = require("./TemplateConfigAll"),
	TemplateConfigByBlueprintType_1 = require("./TemplateConfigByBlueprintType"),
	TemplateConfigById_1 = require("./TemplateConfigById"),
	TemporaryTeleportMarkByMarkId_1 = require("./TemporaryTeleportMarkByMarkId"),
	TextById_1 = require("./TextById"),
	TimeOfDayById_1 = require("./TimeOfDayById"),
	TimePointRewardActivityByActivityId_1 = require("./TimePointRewardActivityByActivityId"),
	TimePointRewardActivityById_1 = require("./TimePointRewardActivityById"),
	TimePointRewardConfigByActivityId_1 = require("./TimePointRewardConfigByActivityId"),
	ToughCalcRatioById_1 = require("./ToughCalcRatioById"),
	TowerBuffById_1 = require("./TowerBuffById"),
	TowerConfigAll_1 = require("./TowerConfigAll"),
	TowerConfigById_1 = require("./TowerConfigById"),
	TowerConfigBySeason_1 = require("./TowerConfigBySeason"),
	TowerDefenceInstanceAll_1 = require("./TowerDefenceInstanceAll"),
	TowerDefenceInstanceById_1 = require("./TowerDefenceInstanceById"),
	TowerDefenceInstanceByInstanceId_1 = require("./TowerDefenceInstanceByInstanceId"),
	TowerDefenceMapMarkAll_1 = require("./TowerDefenceMapMarkAll"),
	TowerDefenceMapMarkByActivityId_1 = require("./TowerDefenceMapMarkByActivityId"),
	TowerDefencePhantomAll_1 = require("./TowerDefencePhantomAll"),
	TowerDefencePhantomById_1 = require("./TowerDefencePhantomById"),
	TowerDefencePhantomLevelAll_1 = require("./TowerDefencePhantomLevelAll"),
	TowerDefencePhantomLevelByGroupId_1 = require("./TowerDefencePhantomLevelByGroupId"),
	TowerDefencePhantomLevelById_1 = require("./TowerDefencePhantomLevelById"),
	TowerDefenceRewardAll_1 = require("./TowerDefenceRewardAll"),
	TowerDefenceRewardById_1 = require("./TowerDefenceRewardById"),
	TowerDifficultyByDifficulty_1 = require("./TowerDifficultyByDifficulty"),
	TowerGuideById_1 = require("./TowerGuideById"),
	TowerTargetById_1 = require("./TowerTargetById"),
	TrackMoonActivityById_1 = require("./TrackMoonActivityById"),
	TrackMoonActivityRewardAll_1 = require("./TrackMoonActivityRewardAll"),
	TrackMoonActivityRewardById_1 = require("./TrackMoonActivityRewardById"),
	TrackMoonEntrustById_1 = require("./TrackMoonEntrustById"),
	TrackMoonHandbookRewardAll_1 = require("./TrackMoonHandbookRewardAll"),
	TrackMoonHandbookRewardById_1 = require("./TrackMoonHandbookRewardById"),
	TrackMoonMemoryAll_1 = require("./TrackMoonMemoryAll"),
	TrackMoonMemoryByClassify_1 = require("./TrackMoonMemoryByClassify"),
	TrackMoonMemoryById_1 = require("./TrackMoonMemoryById"),
	TrackMoonPhaseActivityById_1 = require("./TrackMoonPhaseActivityById"),
	TrackMoonTargetById_1 = require("./TrackMoonTargetById"),
	TrackMoonTargetTypeAll_1 = require("./TrackMoonTargetTypeAll"),
	TrailPhantomPropById_1 = require("./TrailPhantomPropById"),
	TrainRoleDialogByRoleIdAndTrainType_1 = require("./TrainRoleDialogByRoleIdAndTrainType"),
	TreasureBoxDetectorMarkByMarkId_1 = require("./TreasureBoxDetectorMarkByMarkId"),
	TreasureBoxMarkByMarkId_1 = require("./TreasureBoxMarkByMarkId"),
	TrialPhantomPropItemById_1 = require("./TrialPhantomPropItemById"),
	TrialRoleInfoAll_1 = require("./TrialRoleInfoAll"),
	TrialRoleInfoByGroupId_1 = require("./TrialRoleInfoByGroupId"),
	TrialRoleInfoById_1 = require("./TrialRoleInfoById"),
	TrialWeaponInfoById_1 = require("./TrialWeaponInfoById"),
	TurntableActivityByActivityId_1 = require("./TurntableActivityByActivityId"),
	TurntableAwardsByActivityId_1 = require("./TurntableAwardsByActivityId"),
	TurntableAwardsById_1 = require("./TurntableAwardsById"),
	TurntableInfoById_1 = require("./TurntableInfoById"),
	TypeInfoById_1 = require("./TypeInfoById"),
	UiCameraMappingAll_1 = require("./UiCameraMappingAll"),
	UiCameraMappingById_1 = require("./UiCameraMappingById"),
	UiCameraMappingByViewName_1 = require("./UiCameraMappingByViewName"),
	UiDynamicTabByChildViewName_1 = require("./UiDynamicTabByChildViewName"),
	UiDynamicTabById_1 = require("./UiDynamicTabById"),
	UiDynamicTabByParentViewName_1 = require("./UiDynamicTabByParentViewName"),
	UiFloatConfigByViewName_1 = require("./UiFloatConfigByViewName"),
	UiFloatConfigByViewNameIfNull_1 = require("./UiFloatConfigByViewNameIfNull"),
	UiNormalConfigByViewName_1 = require("./UiNormalConfigByViewName"),
	UiNormalConfigByViewNameIfNull_1 = require("./UiNormalConfigByViewNameIfNull"),
	UiPlayItemById_1 = require("./UiPlayItemById"),
	UiResourceById_1 = require("./UiResourceById"),
	UiShowByViewName_1 = require("./UiShowByViewName"),
	UiWeaponVisibleConfigById_1 = require("./UiWeaponVisibleConfigById"),
	UniversalActivityById_1 = require("./UniversalActivityById"),
	VideoCaptionByCgName_1 = require("./VideoCaptionByCgName"),
	VideoDataByCgNameAndGirlOrBoy_1 = require("./VideoDataByCgNameAndGirlOrBoy"),
	VideoSoundByCgNameAndGirlOrBoy_1 = require("./VideoSoundByCgNameAndGirlOrBoy"),
	WeaponBreachByBreachId_1 = require("./WeaponBreachByBreachId"),
	WeaponBreachByBreachIdAndLevel_1 = require("./WeaponBreachByBreachIdAndLevel"),
	WeaponConfByItemId_1 = require("./WeaponConfByItemId"),
	WeaponExpItemById_1 = require("./WeaponExpItemById"),
	WeaponHandBookAll_1 = require("./WeaponHandBookAll"),
	WeaponHandBookById_1 = require("./WeaponHandBookById"),
	WeaponHideConfigById_1 = require("./WeaponHideConfigById"),
	WeaponHideConfigByIdWithZero_1 = require("./WeaponHideConfigByIdWithZero"),
	WeaponLevelByLevelId_1 = require("./WeaponLevelByLevelId"),
	WeaponLevelByLevelIdAndLevel_1 = require("./WeaponLevelByLevelIdAndLevel"),
	WeaponModelTransformById_1 = require("./WeaponModelTransformById"),
	WeaponPropertyGrowthByCurveIdLevelAndBreachLevel_1 = require("./WeaponPropertyGrowthByCurveIdLevelAndBreachLevel"),
	WeaponQualityInfoById_1 = require("./WeaponQualityInfoById"),
	WeaponResonByResonIdAndLevel_1 = require("./WeaponResonByResonIdAndLevel"),
	WeaponVisibleConfigById_1 = require("./WeaponVisibleConfigById"),
	WeaponVisibleConfigByIdWithZero_1 = require("./WeaponVisibleConfigByIdWithZero"),
	WeatherById_1 = require("./WeatherById"),
	WorldLevelById_1 = require("./WorldLevelById"),
	WorldNewJourneyAll_1 = require("./WorldNewJourneyAll"),
	WorldNewJourneyById_1 = require("./WorldNewJourneyById");
class ConfigStatement {
	static Init() {
		CommonParamById_1.configCommonParamById.Init(),
			CommonParamLang_1.configCommonParamLang.Init(),
			AbnormalDamageConfigByLevel_1.configAbnormalDamageConfigByLevel.Init(),
			AbpMontageDataById_1.configAbpMontageDataById.Init(),
			AccessPathById_1.configAccessPathById.Init(),
			AchievementByGroupId_1.configAchievementByGroupId.Init(),
			AchievementById_1.configAchievementById.Init(),
			AchievementCategoryAll_1.configAchievementCategoryAll.Init(),
			AchievementCategoryById_1.configAchievementCategoryById.Init(),
			AchievementGroupByCategory_1.configAchievementGroupByCategory.Init(),
			AchievementGroupById_1.configAchievementGroupById.Init(),
			AchievementStarLevelByLevel_1.configAchievementStarLevelByLevel.Init(),
			ActionMappingAll_1.configActionMappingAll.Init(),
			ActionMappingByActionName_1.configActionMappingByActionName.Init(),
			ActionMappingByActionType_1.configActionMappingByActionType.Init(),
			ActionTypeByType_1.configActionTypeByType.Init(),
			ActivityById_1.configActivityById.Init(),
			ActivitySignById_1.configActivitySignById.Init(),
			AdventureTaskAll_1.configAdventureTaskAll.Init(),
			AdventureTaskById_1.configAdventureTaskById.Init(),
			AdventureTaskChapterAll_1.configAdventureTaskChapterAll.Init(),
			AdventureTaskChapterById_1.configAdventureTaskChapterById.Init(),
			AdviceConjunctionAll_1.configAdviceConjunctionAll.Init(),
			AdviceConjunctionById_1.configAdviceConjunctionById.Init(),
			AdviceParamsById_1.configAdviceParamsById.Init(),
			AdviceSentenceAll_1.configAdviceSentenceAll.Init(),
			AdviceSentenceById_1.configAdviceSentenceById.Init(),
			AdviceWordAll_1.configAdviceWordAll.Init(),
			AdviceWordById_1.configAdviceWordById.Init(),
			AdviceWordByType_1.configAdviceWordByType.Init(),
			AdviceWordTypeAll_1.configAdviceWordTypeAll.Init(),
			AdviceWordTypeById_1.configAdviceWordTypeById.Init(),
			AiAlertById_1.configAiAlertById.Init(),
			AiBaseById_1.configAiBaseById.Init(),
			AiBaseSkillById_1.configAiBaseSkillById.Init(),
			AiBattleWanderById_1.configAiBattleWanderById.Init(),
			AiBattleWanderGroupById_1.configAiBattleWanderGroupById.Init(),
			AiFleeById_1.configAiFleeById.Init(),
			AiHateById_1.configAiHateById.Init(),
			AiPatrolById_1.configAiPatrolById.Init(),
			AiSenseById_1.configAiSenseById.Init(),
			AiSenseGroupById_1.configAiSenseGroupById.Init(),
			AiSkillInfosById_1.configAiSkillInfosById.Init(),
			AiSkillPreconditionById_1.configAiSkillPreconditionById.Init(),
			AiStateMachineConfigById_1.configAiStateMachineConfigById.Init(),
			AiTeamAreaNewById_1.configAiTeamAreaNewById.Init(),
			AiTeamAttackById_1.configAiTeamAttackById.Init(),
			AiTeamLevelNewById_1.configAiTeamLevelNewById.Init(),
			AiWanderById_1.configAiWanderById.Init(),
			AiWanderRadiusConfigById_1.configAiWanderRadiusConfigById.Init(),
			AkiMapByMapId_1.configAkiMapByMapId.Init(),
			AkiMapSourceByMapId_1.configAkiMapSourceByMapId.Init(),
			AnimalHandBookAll_1.configAnimalHandBookAll.Init(),
			AnimalHandBookById_1.configAnimalHandBookById.Init(),
			AnimalHandBookByMeshId_1.configAnimalHandBookByMeshId.Init(),
			AreaByAreaId_1.configAreaByAreaId.Init(),
			AreaByCountryAndLevel_1.configAreaByCountryAndLevel.Init(),
			AreaByDeliveryMarkId_1.configAreaByDeliveryMarkId.Init(),
			AreaAtmosphereInfoById_1.configAreaAtmosphereInfoById.Init(),
			AreaMpcById_1.configAreaMpcById.Init(),
			AreaTaskExploreByAreaId_1.configAreaTaskExploreByAreaId.Init(),
			AreaTaskExploreById_1.configAreaTaskExploreById.Init(),
			AudioById_1.configAudioById.Init(),
			AxisMappingAll_1.configAxisMappingAll.Init(),
			AxisMappingByAxisName_1.configAxisMappingByAxisName.Init(),
			AxisMappingByAxisType_1.configAxisMappingByAxisType.Init(),
			AxisRevertAll_1.configAxisRevertAll.Init(),
			AxisRevertByRevertType_1.configAxisRevertByRevertType.Init(),
			BackgroundCardAll_1.configBackgroundCardAll.Init(),
			BackgroundCardById_1.configBackgroundCardById.Init(),
			BanInfoById_1.configBanInfoById.Init(),
			BanInfoByTypeAndReason_1.configBanInfoByTypeAndReason.Init(),
			BasePropertyById_1.configBasePropertyById.Init(),
			BattlePassById_1.configBattlePassById.Init(),
			BattlePassRewardByBattlePassId_1.configBattlePassRewardByBattlePassId.Init(),
			BattlePassTaskByTaskId_1.configBattlePassTaskByTaskId.Init(),
			BattlePassUnlockPopByBattlePassTypeId_1.configBattlePassUnlockPopByBattlePassTypeId.Init(),
			BattleScoreConfById_1.configBattleScoreConfById.Init(),
			BattleScoreLevelConfByGroupId_1.configBattleScoreLevelConfByGroupId.Init(),
			BattleScoreLevelConfById_1.configBattleScoreLevelConfById.Init(),
			BeginnerGuideById_1.configBeginnerGuideById.Init(),
			BlackboardWhiteListAll_1.configBlackboardWhiteListAll.Init(),
			BlockSwitchById_1.configBlockSwitchById.Init(),
			BlueprintConfigAll_1.configBlueprintConfigAll.Init(),
			BlueprintConfigByBlueprintType_1.configBlueprintConfigByBlueprintType.Init(),
			BossRushActivityAll_1.configBossRushActivityAll.Init(),
			BossRushActivityByActivityIdAndInstanceId_1.configBossRushActivityByActivityIdAndInstanceId.Init(),
			BossRushActivityById_1.configBossRushActivityById.Init(),
			BossRushBuffAll_1.configBossRushBuffAll.Init(),
			BossRushBuffById_1.configBossRushBuffById.Init(),
			BossRushMapMarkByActivityId_1.configBossRushMapMarkByActivityId.Init(),
			BossRushScoreAll_1.configBossRushScoreAll.Init(),
			BossRushScoreById_1.configBossRushScoreById.Init(),
			BoxStateById_1.configBoxStateById.Init(),
			BoxTypeById_1.configBoxTypeById.Init(),
			BranchLineAll_1.configBranchLineAll.Init(),
			BranchLineById_1.configBranchLineById.Init(),
			BroadcastImageById_1.configBroadcastImageById.Init(),
			BubbleDataByActionGuid_1.configBubbleDataByActionGuid.Init(),
			BuffById_1.configBuffById.Init(),
			BuffItemById_1.configBuffItemById.Init(),
			BuffItemByPublicCdGroup_1.configBuffItemByPublicCdGroup.Init(),
			BuffItemCdGroupById_1.configBuffItemCdGroupById.Init(),
			BuildingAll_1.configBuildingAll.Init(),
			BuildingById_1.configBuildingById.Init(),
			BuildingUpGradeCurveByGroupId_1.configBuildingUpGradeCurveByGroupId.Init(),
			BuildingUpGradeCurveByGroupIdAndLevel_1.configBuildingUpGradeCurveByGroupIdAndLevel.Init(),
			BulletPreloadByActorBlueprintAndBulletId_1.configBulletPreloadByActorBlueprintAndBulletId.Init(),
			BulletPreloadById_1.configBulletPreloadById.Init(),
			CalabashDevelopConditionById_1.configCalabashDevelopConditionById.Init(),
			CalabashDevelopRewardAll_1.configCalabashDevelopRewardAll.Init(),
			CalabashDevelopRewardByMonsterId_1.configCalabashDevelopRewardByMonsterId.Init(),
			CalabashLevelAll_1.configCalabashLevelAll.Init(),
			CalabashLevelByLevel_1.configCalabashLevelByLevel.Init(),
			CalabashTransformById_1.configCalabashTransformById.Init(),
			CatchSignalDifficultyById_1.configCatchSignalDifficultyById.Init(),
			CatchSignalGameplayById_1.configCatchSignalGameplayById.Init(),
			CharacterAll_1.configCharacterAll.Init(),
			CharacterById_1.configCharacterById.Init(),
			CharacterAudioConfigById_1.configCharacterAudioConfigById.Init(),
			CharacterAudioConfigByIdWithDefaultId_1.configCharacterAudioConfigByIdWithDefaultId.Init(),
			ChatById_1.configChatById.Init(),
			ChatExpressionAll_1.configChatExpressionAll.Init(),
			ChatExpressionByGroupId_1.configChatExpressionByGroupId.Init(),
			ChatExpressionById_1.configChatExpressionById.Init(),
			ChatExpressionGroupAll_1.configChatExpressionGroupAll.Init(),
			ChatExpressionGroupById_1.configChatExpressionGroupById.Init(),
			ChildUiCameraMappingAll_1.configChildUiCameraMappingAll.Init(),
			ChildUiCameraMappingById_1.configChildUiCameraMappingById.Init(),
			ChildUiCameraMappingByViewName_1.configChildUiCameraMappingByViewName.Init(),
			ChipHandBookAll_1.configChipHandBookAll.Init(),
			ChipHandBookById_1.configChipHandBookById.Init(),
			ChipHandBookByType_1.configChipHandBookByType.Init(),
			ChipTypeAll_1.configChipTypeAll.Init(),
			ChipTypeById_1.configChipTypeById.Init(),
			CipherGameplayById_1.configCipherGameplayById.Init(),
			CircumBaseByEntryType_1.configCircumBaseByEntryType.Init(),
			CircumEntryByEntryType_1.configCircumEntryByEntryType.Init(),
			CircumFluenceTaskById_1.configCircumFluenceTaskById.Init(),
			CircumFluenceTaskByTaskType_1.configCircumFluenceTaskByTaskType.Init(),
			CircumScoreRewardAll_1.configCircumScoreRewardAll.Init(),
			CircumScoreRewardById_1.configCircumScoreRewardById.Init(),
			ClimbById_1.configClimbById.Init(),
			ClueContentByGroupId_1.configClueContentByGroupId.Init(),
			ClueContentById_1.configClueContentById.Init(),
			ClueEntranceById_1.configClueEntranceById.Init(),
			CombinationActionAll_1.configCombinationActionAll.Init(),
			CombinationActionByActionName_1.configCombinationActionByActionName.Init(),
			CombinationActionByActionType_1.configCombinationActionByActionType.Init(),
			CombinationActionById_1.configCombinationActionById.Init(),
			CombinationAxisAll_1.configCombinationAxisAll.Init(),
			CombinationAxisByAxisName_1.configCombinationAxisByAxisName.Init(),
			CombinationAxisByAxisType_1.configCombinationAxisByAxisType.Init(),
			CombinationAxisById_1.configCombinationAxisById.Init(),
			ComboTeachingById_1.configComboTeachingById.Init(),
			ComboTeachingConditionById_1.configComboTeachingConditionById.Init(),
			CommonRewardViewDisplayById_1.configCommonRewardViewDisplayById.Init(),
			CommonSkillPreloadAll_1.configCommonSkillPreloadAll.Init(),
			CommonSkillPreloadById_1.configCommonSkillPreloadById.Init(),
			CommunicateById_1.configCommunicateById.Init(),
			CommunityAll_1.configCommunityAll.Init(),
			CommunityById_1.configCommunityById.Init(),
			CompositeRewardDisplayById_1.configCompositeRewardDisplayById.Init(),
			ConditionById_1.configConditionById.Init(),
			ConditionGroupById_1.configConditionGroupById.Init(),
			ConfirmBoxById_1.configConfirmBoxById.Init(),
			CookFixToolById_1.configCookFixToolById.Init(),
			CookFormulaAll_1.configCookFormulaAll.Init(),
			CookFormulaByFormulaItemId_1.configCookFormulaByFormulaItemId.Init(),
			CookFormulaById_1.configCookFormulaById.Init(),
			CookLevelAll_1.configCookLevelAll.Init(),
			CookLevelById_1.configCookLevelById.Init(),
			CookProcessMsgById_1.configCookProcessMsgById.Init(),
			CookProcessedAll_1.configCookProcessedAll.Init(),
			CookProcessedById_1.configCookProcessedById.Init(),
			CountryAll_1.configCountryAll.Init(),
			CountryById_1.configCountryById.Init(),
			CustomMarkAll_1.configCustomMarkAll.Init(),
			CustomMarkByMarkId_1.configCustomMarkByMarkId.Init(),
			CustomSequenceById_1.configCustomSequenceById.Init(),
			CustomSequenceLang_1.configCustomSequenceLang.Init(),
			CustomerServiceAll_1.configCustomerServiceAll.Init(),
			CustomerServiceById_1.configCustomerServiceById.Init(),
			DailyAdventureActivityByActivityId_1.configDailyAdventureActivityByActivityId.Init(),
			DailyAdventurePointById_1.configDailyAdventurePointById.Init(),
			DailyAdventureTaskByTaskId_1.configDailyAdventureTaskByTaskId.Init(),
			DailyTaskById_1.configDailyTaskById.Init(),
			DailyTaskGroupById_1.configDailyTaskGroupById.Init(),
			DamageById_1.configDamageById.Init(),
			DamagePayloadById_1.configDamagePayloadById.Init(),
			DamageTextAll_1.configDamageTextAll.Init(),
			DataLayerById_1.configDataLayerById.Init(),
			DaySelectPresetAll_1.configDaySelectPresetAll.Init(),
			DaySelectPresetById_1.configDaySelectPresetById.Init(),
			DebugCommandConfigById_1.configDebugCommandConfigById.Init(),
			DebugEntranceConfigAll_1.configDebugEntranceConfigAll.Init(),
			DebugEntranceConfigById_1.configDebugEntranceConfigById.Init(),
			DebugEntranceTypeConfigAll_1.configDebugEntranceTypeConfigAll.Init(),
			DebugEntranceTypeConfigById_1.configDebugEntranceTypeConfigById.Init(),
			DetectionTextById_1.configDetectionTextById.Init(),
			DevicePlatformById_1.configDevicePlatformById.Init(),
			DevicePlatformByPidAndVid_1.configDevicePlatformByPidAndVid.Init(),
			DeviceRenderFeatureByDeviceId_1.configDeviceRenderFeatureByDeviceId.Init(),
			DigitalScreenById_1.configDigitalScreenById.Init(),
			DigitalScreenTextById_1.configDigitalScreenTextById.Init(),
			DoubleRewardActivityById_1.configDoubleRewardActivityById.Init(),
			DragonPoolAll_1.configDragonPoolAll.Init(),
			DragonPoolById_1.configDragonPoolById.Init(),
			DropPackageById_1.configDropPackageById.Init(),
			DropShowPlanById_1.configDropShowPlanById.Init(),
			DungeonDetectionAll_1.configDungeonDetectionAll.Init(),
			DungeonDetectionByDungeonId_1.configDungeonDetectionByDungeonId.Init(),
			DungeonDetectionById_1.configDungeonDetectionById.Init(),
			DynamicMapMarkByMapId_1.configDynamicMapMarkByMapId.Init(),
			DynamicMapMarkByMarkId_1.configDynamicMapMarkByMarkId.Init(),
			EffectConfigById_1.configEffectConfigById.Init(),
			EffectSpecDataByPath_1.configEffectSpecDataByPath.Init(),
			ElementIconTagById_1.configElementIconTagById.Init(),
			ElementInfoById_1.configElementInfoById.Init(),
			ElementInfoById2_1.configElementInfoById2.Init(),
			ElementLevelByLevel_1.configElementLevelByLevel.Init(),
			ElementReactionMatrixAll_1.configElementReactionMatrixAll.Init(),
			ElementalReactionAll_1.configElementalReactionAll.Init(),
			ElementalReactionByReactionId_1.configElementalReactionByReactionId.Init(),
			EntityAudioConfigById_1.configEntityAudioConfigById.Init(),
			EntityAudioConfigByIdWithZero_1.configEntityAudioConfigByIdWithZero.Init(),
			EntityOwnerDataByGuid_1.configEntityOwnerDataByGuid.Init(),
			EntitySkillPreloadByActorBlueprintAndSkillId_1.configEntitySkillPreloadByActorBlueprintAndSkillId.Init(),
			EntitySkillPreloadById_1.configEntitySkillPreloadById.Init(),
			EntityVoxelInfoByMapIdAndEntityId_1.configEntityVoxelInfoByMapIdAndEntityId.Init(),
			EntranceIconTagById_1.configEntranceIconTagById.Init(),
			EntrustFinishDialogByEntrustIdAndLevel_1.configEntrustFinishDialogByEntrustIdAndLevel.Init(),
			EntrustRoleAll_1.configEntrustRoleAll.Init(),
			EntrustRoleById_1.configEntrustRoleById.Init(),
			EntrustTypeById_1.configEntrustTypeById.Init(),
			ErrorCodeById_1.configErrorCodeById.Init(),
			EvaluateById_1.configEvaluateById.Init(),
			ExchangeRewardById_1.configExchangeRewardById.Init(),
			ExchangeSharedById_1.configExchangeSharedById.Init(),
			ExecutionConfById_1.configExecutionConfById.Init(),
			ExploreProgressAll_1.configExploreProgressAll.Init(),
			ExploreProgressByArea_1.configExploreProgressByArea.Init(),
			ExploreProgressById_1.configExploreProgressById.Init(),
			ExploreRewardByCountry_1.configExploreRewardByCountry.Init(),
			ExploreRewardById_1.configExploreRewardById.Init(),
			ExploreRewardDisplayById_1.configExploreRewardDisplayById.Init(),
			ExploreScoreAll_1.configExploreScoreAll.Init(),
			ExploreScoreByArea_1.configExploreScoreByArea.Init(),
			ExploreToolsAll_1.configExploreToolsAll.Init(),
			ExploreToolsByPhantomSkillId_1.configExploreToolsByPhantomSkillId.Init(),
			ExternalSourceSettingById_1.configExternalSourceSettingById.Init(),
			FaceExpressionDataById_1.configFaceExpressionDataById.Init(),
			FavorGoodsByRoleId_1.configFavorGoodsByRoleId.Init(),
			FavorLevelByLevel_1.configFavorLevelByLevel.Init(),
			FavorRoleInfoByRoleId_1.configFavorRoleInfoByRoleId.Init(),
			FavorStoryByRoleId_1.configFavorStoryByRoleId.Init(),
			FavorTabCameraById_1.configFavorTabCameraById.Init(),
			FavorWordByRoleIdAndType_1.configFavorWordByRoleIdAndType.Init(),
			FeedingAnimalById_1.configFeedingAnimalById.Init(),
			FightFormationById_1.configFightFormationById.Init(),
			FilterById_1.configFilterById.Init(),
			FilterRuleById_1.configFilterRuleById.Init(),
			FilterSortGroupById_1.configFilterSortGroupById.Init(),
			FlowById_1.configFlowById.Init(),
			FlowStateByStateKey_1.configFlowStateByStateKey.Init(),
			FlowTemplateDataById_1.configFlowTemplateDataById.Init(),
			FlowTextByIdAndFlowListId_1.configFlowTextByIdAndFlowListId.Init(),
			FlowTextLang_1.configFlowTextLang.Init(),
			FogBlockAll_1.configFogBlockAll.Init(),
			FogBlockByBlock_1.configFogBlockByBlock.Init(),
			FogTextureConfigAll_1.configFogTextureConfigAll.Init(),
			FogTextureConfigByBlock_1.configFogTextureConfigByBlock.Init(),
			FoleySynthBoneConfigById_1.configFoleySynthBoneConfigById.Init(),
			FoleySynthConfigById_1.configFoleySynthConfigById.Init(),
			FoleySynthConfigByIdWithDefaultId_1.configFoleySynthConfigByIdWithDefaultId.Init(),
			ForgeFormulaAll_1.configForgeFormulaAll.Init(),
			ForgeFormulaByFormulaItemId_1.configForgeFormulaByFormulaItemId.Init(),
			ForgeFormulaById_1.configForgeFormulaById.Init(),
			ForgeFormulaByTypeId_1.configForgeFormulaByTypeId.Init(),
			FormationPropertyAll_1.configFormationPropertyAll.Init(),
			FormationPropertyById_1.configFormationPropertyById.Init(),
			FriendFilterAll_1.configFriendFilterAll.Init(),
			FuncMenuWheelAll_1.configFuncMenuWheelAll.Init(),
			FuncMenuWheelByFuncId_1.configFuncMenuWheelByFuncId.Init(),
			FunctionConditionByFunctionId_1.configFunctionConditionByFunctionId.Init(),
			FunctionMenuAll_1.configFunctionMenuAll.Init(),
			FunctionMenuByFunctionId_1.configFunctionMenuByFunctionId.Init(),
			FunctionOpenViewLimitAll_1.configFunctionOpenViewLimitAll.Init(),
			GaChaShareById_1.configGaChaShareById.Init(),
			GachaAll_1.configGachaAll.Init(),
			GachaById_1.configGachaById.Init(),
			GachaEffectConfigByTimesAndQuality_1.configGachaEffectConfigByTimesAndQuality.Init(),
			GachaPoolById_1.configGachaPoolById.Init(),
			GachaSequenceConfigById_1.configGachaSequenceConfigById.Init(),
			GachaTextureInfoById_1.configGachaTextureInfoById.Init(),
			GachaViewInfoById_1.configGachaViewInfoById.Init(),
			GachaViewTypeInfoByType_1.configGachaViewTypeInfoByType.Init(),
			GachaWeaponTransformById_1.configGachaWeaponTransformById.Init(),
			GamePlayInformationGroupById_1.configGamePlayInformationGroupById.Init(),
			GamePlayInformationInfoById_1.configGamePlayInformationInfoById.Init(),
			GamePlayScanByUid_1.configGamePlayScanByUid.Init(),
			GamePlayScanCompositeByUid_1.configGamePlayScanCompositeByUid.Init(),
			GamepadKeyById_1.configGamepadKeyById.Init(),
			GamepadKeyByKeyName_1.configGamepadKeyByKeyName.Init(),
			GameplayCueById_1.configGameplayCueById.Init(),
			GatherActivityAll_1.configGatherActivityAll.Init(),
			GatherActivityById_1.configGatherActivityById.Init(),
			GenderTextByMaleText_1.configGenderTextByMaleText.Init(),
			GeneralActionById_1.configGeneralActionById.Init(),
			GeneralActionGroupById_1.configGeneralActionGroupById.Init(),
			GenericPromptByTipsId_1.configGenericPromptByTipsId.Init(),
			GenericPromptTypesByTypeId_1.configGenericPromptTypesByTypeId.Init(),
			GeographyHandBookAll_1.configGeographyHandBookAll.Init(),
			GeographyHandBookById_1.configGeographyHandBookById.Init(),
			GeographyHandBookByType_1.configGeographyHandBookByType.Init(),
			GeographyTypeAll_1.configGeographyTypeAll.Init(),
			GeographyTypeById_1.configGeographyTypeById.Init(),
			GiftPackageById_1.configGiftPackageById.Init(),
			GlobalConfigFromCsvByName_1.configGlobalConfigFromCsvByName.Init(),
			GmAccountAll_1.configGmAccountAll.Init(),
			GmAccountById_1.configGmAccountById.Init(),
			GmOrderConfigAll_1.configGmOrderConfigAll.Init(),
			GmOrderListAll_1.configGmOrderListAll.Init(),
			GmOrderListById_1.configGmOrderListById.Init(),
			GuideDataById_1.configGuideDataById.Init(),
			GuideFocusNewByGuideId_1.configGuideFocusNewByGuideId.Init(),
			GuideGroupAll_1.configGuideGroupAll.Init(),
			GuideGroupById_1.configGuideGroupById.Init(),
			GuideStepAll_1.configGuideStepAll.Init(),
			GuideStepById_1.configGuideStepById.Init(),
			GuideTipsByGuideId_1.configGuideTipsByGuideId.Init(),
			GuideTutorialAll_1.configGuideTutorialAll.Init(),
			GuideTutorialById_1.configGuideTutorialById.Init(),
			GuideTutorialPageById_1.configGuideTutorialPageById.Init(),
			HandBookEntranceAll_1.configHandBookEntranceAll.Init(),
			HandBookEntranceById_1.configHandBookEntranceById.Init(),
			HandBookQuestTabAll_1.configHandBookQuestTabAll.Init(),
			HandBookQuestTabById_1.configHandBookQuestTabById.Init(),
			HardnessModeById_1.configHardnessModeById.Init(),
			HeadIconById_1.configHeadIconById.Init(),
			HelpTextByGroupId_1.configHelpTextByGroupId.Init(),
			HelpTextById_1.configHelpTextById.Init(),
			HotKeyIconByKeyName_1.configHotKeyIconByKeyName.Init(),
			HotKeyMapById_1.configHotKeyMapById.Init(),
			HotKeyTextByTextId_1.configHotKeyTextByTextId.Init(),
			HotKeyTypeById_1.configHotKeyTypeById.Init(),
			HotKeyViewById_1.configHotKeyViewById.Init(),
			HotPatchTextLang_1.configHotPatchTextLang.Init(),
			InfluenceAll_1.configInfluenceAll.Init(),
			InfluenceById_1.configInfluenceById.Init(),
			InfoDisplayById_1.configInfoDisplayById.Init(),
			InstanceDungeonAll_1.configInstanceDungeonAll.Init(),
			InstanceDungeonById_1.configInstanceDungeonById.Init(),
			InstanceDungeonEntranceAll_1.configInstanceDungeonEntranceAll.Init(),
			InstanceDungeonEntranceById_1.configInstanceDungeonEntranceById.Init(),
			InstanceDungeonEntranceByMarkId_1.configInstanceDungeonEntranceByMarkId.Init(),
			InstanceDungeonTitleById_1.configInstanceDungeonTitleById.Init(),
			InstanceEnterControlById_1.configInstanceEnterControlById.Init(),
			InstanceTrialRoleConfigById_1.configInstanceTrialRoleConfigById.Init(),
			InteractAudioMaterialByCollisionMaterial_1.configInteractAudioMaterialByCollisionMaterial.Init(),
			InteractBackGroundById_1.configInteractBackGroundById.Init(),
			InteractBackGroundByViewName_1.configInteractBackGroundByViewName.Init(),
			InteractDataByGuid_1.configInteractDataByGuid.Init(),
			InterjectionByTimberIdAndUniversalToneId_1.configInterjectionByTimberIdAndUniversalToneId.Init(),
			ItemExchangeContentAll_1.configItemExchangeContentAll.Init(),
			ItemExchangeContentByItemId_1.configItemExchangeContentByItemId.Init(),
			ItemExchangeLimitByItemId_1.configItemExchangeLimitByItemId.Init(),
			ItemHandBookAll_1.configItemHandBookAll.Init(),
			ItemHandBookById_1.configItemHandBookById.Init(),
			ItemHandBookByType_1.configItemHandBookByType.Init(),
			ItemHandBookTypeAll_1.configItemHandBookTypeAll.Init(),
			ItemHandBookTypeById_1.configItemHandBookTypeById.Init(),
			ItemIconTagById_1.configItemIconTagById.Init(),
			ItemInfoAll_1.configItemInfoAll.Init(),
			ItemInfoById_1.configItemInfoById.Init(),
			ItemInfoByItemType_1.configItemInfoByItemType.Init(),
			ItemMainTypeAll_1.configItemMainTypeAll.Init(),
			ItemMainTypeById_1.configItemMainTypeById.Init(),
			ItemShowTypeById_1.configItemShowTypeById.Init(),
			KeySettingAll_1.configKeySettingAll.Init(),
			KeySettingById_1.configKeySettingById.Init(),
			KeySettingByTypeId_1.configKeySettingByTypeId.Init(),
			KeySettingByTypeIdAndInputControllerType_1.configKeySettingByTypeIdAndInputControllerType.Init(),
			KeyTypeAll_1.configKeyTypeAll.Init(),
			KeyTypeByTypeId_1.configKeyTypeByTypeId.Init(),
			KillMonstersScoresByInstanceID_1.configKillMonstersScoresByInstanceID.Init(),
			LangOfLogoByName_1.configLangOfLogoByName.Init(),
			LanguageDefineByLanguageCode_1.configLanguageDefineByLanguageCode.Init(),
			LanguageDefineByLanguageType_1.configLanguageDefineByLanguageType.Init(),
			LevelEntityConfigByBlueprintType_1.configLevelEntityConfigByBlueprintType.Init(),
			LevelEntityConfigByMapIdAndEntityId_1.configLevelEntityConfigByMapIdAndEntityId.Init(),
			LevelPlayDataById_1.configLevelPlayDataById.Init(),
			LevelPlayNodeDataByKey_1.configLevelPlayNodeDataByKey.Init(),
			LivenessAll_1.configLivenessAll.Init(),
			LivenessById_1.configLivenessById.Init(),
			LivenessTaskByTaskId_1.configLivenessTaskByTaskId.Init(),
			LoadingLevelAreaAll_1.configLoadingLevelAreaAll.Init(),
			LoadingTipsTextAll_1.configLoadingTipsTextAll.Init(),
			LoadingTipsTextById_1.configLoadingTipsTextById.Init(),
			LoadingTipsTextByLevelAreaId_1.configLoadingTipsTextByLevelAreaId.Init(),
			LockOnConfigById_1.configLockOnConfigById.Init(),
			LongPressConfigById_1.configLongPressConfigById.Init(),
			LongShanStageAll_1.configLongShanStageAll.Init(),
			LongShanStageById_1.configLongShanStageById.Init(),
			LongShanTaskById_1.configLongShanTaskById.Init(),
			LordGymAll_1.configLordGymAll.Init(),
			LordGymByDifficulty_1.configLordGymByDifficulty.Init(),
			LordGymById_1.configLordGymById.Init(),
			LordGymEntranceAll_1.configLordGymEntranceAll.Init(),
			LordGymEntranceById_1.configLordGymEntranceById.Init(),
			LordGymEntranceByMarkId_1.configLordGymEntranceByMarkId.Init(),
			LordGymFilterTypeAll_1.configLordGymFilterTypeAll.Init(),
			LordGymFilterTypeById_1.configLordGymFilterTypeById.Init(),
			MailFilterAll_1.configMailFilterAll.Init(),
			MailFilterById_1.configMailFilterById.Init(),
			MainLineAll_1.configMainLineAll.Init(),
			MainLineById_1.configMainLineById.Init(),
			MainRoleConfigAll_1.configMainRoleConfigAll.Init(),
			MainRoleConfigByGender_1.configMainRoleConfigByGender.Init(),
			MainRoleConfigById_1.configMainRoleConfigById.Init(),
			MainTypeAll_1.configMainTypeAll.Init(),
			MainTypeById_1.configMainTypeById.Init(),
			MapAudioById_1.configMapAudioById.Init(),
			MapBorderAll_1.configMapBorderAll.Init(),
			MapBorderByBorderId_1.configMapBorderByBorderId.Init(),
			MapMarkByEntityConfigId_1.configMapMarkByEntityConfigId.Init(),
			MapMarkByMapId_1.configMapMarkByMapId.Init(),
			MapMarkByMarkId_1.configMapMarkByMarkId.Init(),
			MapMarkByRelativeMainSubType_1.configMapMarkByRelativeMainSubType.Init(),
			MapMarkHasEntityConfigId_1.configMapMarkHasEntityConfigId.Init(),
			MapMarkPhantomGroupByMarkId_1.configMapMarkPhantomGroupByMarkId.Init(),
			MapMarkRelativeSubTypeAll_1.configMapMarkRelativeSubTypeAll.Init(),
			MapMarkRelativeSubTypeByFunctionId_1.configMapMarkRelativeSubTypeByFunctionId.Init(),
			MapMarkRelativeSubTypeById_1.configMapMarkRelativeSubTypeById.Init(),
			MapNoteById_1.configMapNoteById.Init(),
			MappingBySheetNameAndFieldName_1.configMappingBySheetNameAndFieldName.Init(),
			MappingBySheetNameFieldNameAndValue_1.configMappingBySheetNameFieldNameAndValue.Init(),
			MarkEffectByMarkId_1.configMarkEffectByMarkId.Init(),
			MenuConfigAll_1.configMenuConfigAll.Init(),
			MenuConfigByFunctionId_1.configMenuConfigByFunctionId.Init(),
			MobileBattleUiSetAll_1.configMobileBattleUiSetAll.Init(),
			MobileBattleUiSetByPanelIndex_1.configMobileBattleUiSetByPanelIndex.Init(),
			ModelConfigPreloadById_1.configModelConfigPreloadById.Init(),
			MonitorActionById_1.configMonitorActionById.Init(),
			MonsterBattleConfById_1.configMonsterBattleConfById.Init(),
			MonsterBodyTypeConfigById_1.configMonsterBodyTypeConfigById.Init(),
			MonsterDetectionAll_1.configMonsterDetectionAll.Init(),
			MonsterDetectionById_1.configMonsterDetectionById.Init(),
			MonsterDetectionFilterAll_1.configMonsterDetectionFilterAll.Init(),
			MonsterDisplayById_1.configMonsterDisplayById.Init(),
			MonsterDisplayLang_1.configMonsterDisplayLang.Init(),
			MonsterHandBookAll_1.configMonsterHandBookAll.Init(),
			MonsterHandBookById_1.configMonsterHandBookById.Init(),
			MonsterHandBookByType_1.configMonsterHandBookByType.Init(),
			MonsterHandBookTypeAll_1.configMonsterHandBookTypeAll.Init(),
			MonsterIconTagById_1.configMonsterIconTagById.Init(),
			MonsterInfoById_1.configMonsterInfoById.Init(),
			MonsterPerchById_1.configMonsterPerchById.Init(),
			MonsterPropertyGrowthById_1.configMonsterPropertyGrowthById.Init(),
			MonsterRarityById_1.configMonsterRarityById.Init(),
			MonsterSizeIdById_1.configMonsterSizeIdById.Init(),
			MontageDataById_1.configMontageDataById.Init(),
			MonthCardContentById_1.configMonthCardContentById.Init(),
			MotionById_1.configMotionById.Init(),
			MotionByRoleId_1.configMotionByRoleId.Init(),
			MotionByRoleIdAndType_1.configMotionByRoleIdAndType.Init(),
			MultiMapAll_1.configMultiMapAll.Init(),
			MultiMapByGroupId_1.configMultiMapByGroupId.Init(),
			MultiMapById_1.configMultiMapById.Init(),
			MultiMapAreaConfigAll_1.configMultiMapAreaConfigAll.Init(),
			MultiMapAreaConfigByBlock_1.configMultiMapAreaConfigByBlock.Init(),
			MultiTextLang_1.configMultiTextLang.Init(),
			NewOccupationConfigAll_1.configNewOccupationConfigAll.Init(),
			NewOccupationConfigById_1.configNewOccupationConfigById.Init(),
			NewbieCourseAll_1.configNewbieCourseAll.Init(),
			NewbieCourseById_1.configNewbieCourseById.Init(),
			NpcHeadInfoById_1.configNpcHeadInfoById.Init(),
			NpcSystemBackgroundById_1.configNpcSystemBackgroundById.Init(),
			NpcSystemBackgroundByViewName_1.configNpcSystemBackgroundByViewName.Init(),
			OccupationConfigById_1.configOccupationConfigById.Init(),
			OccupationConfigLang_1.configOccupationConfigLang.Init(),
			OpenAndCloseViewHotKeyAll_1.configOpenAndCloseViewHotKeyAll.Init(),
			OpenAndCloseViewHotKeyByActionName_1.configOpenAndCloseViewHotKeyByActionName.Init(),
			OpenAndCloseViewHotKeyByInputControllerType_1.configOpenAndCloseViewHotKeyByInputControllerType.Init(),
			OverlayAbpMontageDataById_1.configOverlayAbpMontageDataById.Init(),
			PackageCapacityAll_1.configPackageCapacityAll.Init(),
			PackageCapacityByPackageId_1.configPackageCapacityByPackageId.Init(),
			ParkourChallengeById_1.configParkourChallengeById.Init(),
			ParkourChallengeByMarkId_1.configParkourChallengeByMarkId.Init(),
			PassiveSkillById_1.configPassiveSkillById.Init(),
			PayById_1.configPayById.Init(),
			PayByPayIdAndRegion_1.configPayByPayIdAndRegion.Init(),
			PayByRegion_1.configPayByRegion.Init(),
			PayItemAll_1.configPayItemAll.Init(),
			PayItemById_1.configPayItemById.Init(),
			PayShopAll_1.configPayShopAll.Init(),
			PayShopById_1.configPayShopById.Init(),
			PayShopConditionById_1.configPayShopConditionById.Init(),
			PayShopDirectGoodsByGoodsId_1.configPayShopDirectGoodsByGoodsId.Init(),
			PayShopGoodsById_1.configPayShopGoodsById.Init(),
			PayShopGoodsByItemId_1.configPayShopGoodsByItemId.Init(),
			PayShopTabByShopId_1.configPayShopTabByShopId.Init(),
			PayShopTabByShopIdAndTabId_1.configPayShopTabByShopIdAndTabId.Init(),
			PcKeyById_1.configPcKeyById.Init(),
			PcKeyByKeyName_1.configPcKeyByKeyName.Init(),
			PersonalTipsByFunctionId_1.configPersonalTipsByFunctionId.Init(),
			PersonalTipsById_1.configPersonalTipsById.Init(),
			PhantomCollectActivityById_1.configPhantomCollectActivityById.Init(),
			PhantomCollectTaskDescById_1.configPhantomCollectTaskDescById.Init(),
			PhantomCustomizeItemByItemId_1.configPhantomCustomizeItemByItemId.Init(),
			PhantomExpItemAll_1.configPhantomExpItemAll.Init(),
			PhantomExpItemByItemId_1.configPhantomExpItemByItemId.Init(),
			PhantomFetterAll_1.configPhantomFetterAll.Init(),
			PhantomFetterById_1.configPhantomFetterById.Init(),
			PhantomFetterGroupAll_1.configPhantomFetterGroupAll.Init(),
			PhantomFetterGroupById_1.configPhantomFetterGroupById.Init(),
			PhantomFetterHandBookAll_1.configPhantomFetterHandBookAll.Init(),
			PhantomGrowthByGrowthIdAndLevel_1.configPhantomGrowthByGrowthIdAndLevel.Init(),
			PhantomHandBookAll_1.configPhantomHandBookAll.Init(),
			PhantomHandBookById_1.configPhantomHandBookById.Init(),
			PhantomHandBookPageAll_1.configPhantomHandBookPageAll.Init(),
			PhantomItemAll_1.configPhantomItemAll.Init(),
			PhantomItemByItemId_1.configPhantomItemByItemId.Init(),
			PhantomItemByMonsterId_1.configPhantomItemByMonsterId.Init(),
			PhantomLevelByGroupId_1.configPhantomLevelByGroupId.Init(),
			PhantomLevelByGroupIdAndLevel_1.configPhantomLevelByGroupIdAndLevel.Init(),
			PhantomMainPropItemById_1.configPhantomMainPropItemById.Init(),
			PhantomMainPropertyById_1.configPhantomMainPropertyById.Init(),
			PhantomQualityByQuality_1.configPhantomQualityByQuality.Init(),
			PhantomRarityByRare_1.configPhantomRarityByRare.Init(),
			PhantomSkillById_1.configPhantomSkillById.Init(),
			PhantomSkillByPhantomSkillId_1.configPhantomSkillByPhantomSkillId.Init(),
			PhantomSubPropertyById_1.configPhantomSubPropertyById.Init(),
			PhantomSubPropertyByPropId_1.configPhantomSubPropertyByPropId.Init(),
			PhantomWildItemAll_1.configPhantomWildItemAll.Init(),
			PhantomWildItemByItemId_1.configPhantomWildItemByItemId.Init(),
			PhotoMemoryActivityById_1.configPhotoMemoryActivityById.Init(),
			PhotoMemoryCollectById_1.configPhotoMemoryCollectById.Init(),
			PhotoMemoryCollectByTopicID_1.configPhotoMemoryCollectByTopicID.Init(),
			PhotoMemoryTopicAll_1.configPhotoMemoryTopicAll.Init(),
			PhotoMemoryTopicById_1.configPhotoMemoryTopicById.Init(),
			PhotoMontageById_1.configPhotoMontageById.Init(),
			PhotoMontageByRoleId_1.configPhotoMontageByRoleId.Init(),
			PhotoSetupAll_1.configPhotoSetupAll.Init(),
			PhotoSetupByValueType_1.configPhotoSetupByValueType.Init(),
			PhotographHandBookAll_1.configPhotographHandBookAll.Init(),
			PhotographHandBookById_1.configPhotographHandBookById.Init(),
			PhotographHandBookByType_1.configPhotographHandBookByType.Init(),
			PhysicsAssetConfigById_1.configPhysicsAssetConfigById.Init(),
			PhysicsAssetConfigByIdWithDefaultId_1.configPhysicsAssetConfigByIdWithDefaultId.Init(),
			PlatformIconById_1.configPlatformIconById.Init(),
			PlayerExpByPlayerLevel_1.configPlayerExpByPlayerLevel.Init(),
			PlayerExpByPlayerLevelArea_1.configPlayerExpByPlayerLevelArea.Init(),
			PlayerStateRestrictionById_1.configPlayerStateRestrictionById.Init(),
			PlotAudioById_1.configPlotAudioById.Init(),
			PlotHandBookConfigAll_1.configPlotHandBookConfigAll.Init(),
			PlotHandBookConfigByQuestId_1.configPlotHandBookConfigByQuestId.Init(),
			PlotTypeAll_1.configPlotTypeAll.Init(),
			PlotTypeById_1.configPlotTypeById.Init(),
			PopularityAll_1.configPopularityAll.Init(),
			PrefabConfigById_1.configPrefabConfigById.Init(),
			PrefabTextItemAll_1.configPrefabTextItemAll.Init(),
			PrefabTextItemByItemId_1.configPrefabTextItemByItemId.Init(),
			PrefabTextItemByPrefabPathHash_1.configPrefabTextItemByPrefabPathHash.Init(),
			PreviewItemAll_1.configPreviewItemAll.Init(),
			PreviewItemById_1.configPreviewItemById.Init(),
			PropRewardConfById_1.configPropRewardConfById.Init(),
			PropertyIndexAll_1.configPropertyIndexAll.Init(),
			PropertyIndexById_1.configPropertyIndexById.Init(),
			QualityIconTagById_1.configQualityIconTagById.Init(),
			QualityInfoAll_1.configQualityInfoAll.Init(),
			QualityInfoById_1.configQualityInfoById.Init(),
			QuestById_1.configQuestById.Init(),
			QuestChapterById_1.configQuestChapterById.Init(),
			QuestDataById_1.configQuestDataById.Init(),
			QuestMainTypeById_1.configQuestMainTypeById.Init(),
			QuestNodeDataByKey_1.configQuestNodeDataByKey.Init(),
			QuestTagById_1.configQuestTagById.Init(),
			QuestTypeAll_1.configQuestTypeAll.Init(),
			QuestTypeById_1.configQuestTypeById.Init(),
			QuestTypeByMainId_1.configQuestTypeByMainId.Init(),
			QuickChatAll_1.configQuickChatAll.Init(),
			RecordConfigById_1.configRecordConfigById.Init(),
			RedDotByRelativeName_1.configRedDotByRelativeName.Init(),
			RegressRewardsById_1.configRegressRewardsById.Init(),
			ReportPlayerInfoAll_1.configReportPlayerInfoAll.Init(),
			ResonantChainByGroupId_1.configResonantChainByGroupId.Init(),
			ResonantChainByGroupIdAndGroupIndex_1.configResonantChainByGroupIdAndGroupIndex.Init(),
			ResonantChainByGroupIdAndNodeType_1.configResonantChainByGroupIdAndNodeType.Init(),
			ResonantChainById_1.configResonantChainById.Init(),
			ReviveById_1.configReviveById.Init(),
			RewardConfigById_1.configRewardConfigById.Init(),
			RewardViewFromSourceAll_1.configRewardViewFromSourceAll.Init(),
			RewardViewFromSourceBySourceId_1.configRewardViewFromSourceBySourceId.Init(),
			RogueActivityById_1.configRogueActivityById.Init(),
			RogueAffixById_1.configRogueAffixById.Init(),
			RogueBuffPoolById_1.configRogueBuffPoolById.Init(),
			RogueCharacterById_1.configRogueCharacterById.Init(),
			RogueCharacterBuffById_1.configRogueCharacterBuffById.Init(),
			RogueCurrencyById_1.configRogueCurrencyById.Init(),
			RogueEffectById_1.configRogueEffectById.Init(),
			RogueEventById_1.configRogueEventById.Init(),
			RogueParamById_1.configRogueParamById.Init(),
			RoguePokemonById_1.configRoguePokemonById.Init(),
			RoguePopularEntrieArgAll_1.configRoguePopularEntrieArgAll.Init(),
			RoguePopularEntrieArgById_1.configRoguePopularEntrieArgById.Init(),
			RoguePopularEntrieArgBySeasonIdAndInstId_1.configRoguePopularEntrieArgBySeasonIdAndInstId.Init(),
			RogueQualityConfigById_1.configRogueQualityConfigById.Init(),
			RogueRoomPoolByBehaviorTree_1.configRogueRoomPoolByBehaviorTree.Init(),
			RogueRoomShowConfigById_1.configRogueRoomShowConfigById.Init(),
			RogueRoomTypeById_1.configRogueRoomTypeById.Init(),
			RogueSeasonAll_1.configRogueSeasonAll.Init(),
			RogueSeasonById_1.configRogueSeasonById.Init(),
			RogueSeasonRewardBySeasonId_1.configRogueSeasonRewardBySeasonId.Init(),
			RogueTalentTreeAll_1.configRogueTalentTreeAll.Init(),
			RogueTalentTreeById_1.configRogueTalentTreeById.Init(),
			RogueTalentTreeDescById_1.configRogueTalentTreeDescById.Init(),
			RogueTokenBySeasonId_1.configRogueTokenBySeasonId.Init(),
			RoleAnimAudioByRoleId_1.configRoleAnimAudioByRoleId.Init(),
			RoleAudioById_1.configRoleAudioById.Init(),
			RoleAudioRulesById_1.configRoleAudioRulesById.Init(),
			RoleBattleViewInfoAll_1.configRoleBattleViewInfoAll.Init(),
			RoleBattleViewInfoById_1.configRoleBattleViewInfoById.Init(),
			RoleBreachByBreachGroupId_1.configRoleBreachByBreachGroupId.Init(),
			RoleBreachByBreachGroupIdAndBreachLevel_1.configRoleBreachByBreachGroupIdAndBreachLevel.Init(),
			RoleDescriptionById_1.configRoleDescriptionById.Init(),
			RoleDevelopCurveByGroupId_1.configRoleDevelopCurveByGroupId.Init(),
			RoleDevelopTypeById_1.configRoleDevelopTypeById.Init(),
			RoleExpItemAll_1.configRoleExpItemAll.Init(),
			RoleExpItemById_1.configRoleExpItemById.Init(),
			RoleGuideActivityById_1.configRoleGuideActivityById.Init(),
			RoleIconTagById_1.configRoleIconTagById.Init(),
			RoleInfluenceAll_1.configRoleInfluenceAll.Init(),
			RoleInfluenceById_1.configRoleInfluenceById.Init(),
			RoleInfoAll_1.configRoleInfoAll.Init(),
			RoleInfoById_1.configRoleInfoById.Init(),
			RoleInfoByRoleType_1.configRoleInfoByRoleType.Init(),
			RoleLevelConsumeByConsumeGroupIdAndLevel_1.configRoleLevelConsumeByConsumeGroupIdAndLevel.Init(),
			RolePropertyGrowthByLevelAndBreachLevel_1.configRolePropertyGrowthByLevelAndBreachLevel.Init(),
			RoleQualityInfoById_1.configRoleQualityInfoById.Init(),
			RoleQuestById_1.configRoleQuestById.Init(),
			RoleQuestByRoleId_1.configRoleQuestByRoleId.Init(),
			RoleQuestByRoleIdAll_1.configRoleQuestByRoleIdAll.Init(),
			RoleSkillInputById_1.configRoleSkillInputById.Init(),
			RoleTagAll_1.configRoleTagAll.Init(),
			RoleTagById_1.configRoleTagById.Init(),
			RoleTrainingDegreeByDifficultyLevel_1.configRoleTrainingDegreeByDifficultyLevel.Init(),
			RoleTrialActivityById_1.configRoleTrialActivityById.Init(),
			RoleTrialInfoById_1.configRoleTrialInfoById.Init(),
			RougeMiraclecreationById_1.configRougeMiraclecreationById.Init(),
			RougePopularEntrieAll_1.configRougePopularEntrieAll.Init(),
			RougePopularEntrieById_1.configRougePopularEntrieById.Init(),
			ScoreRewardById_1.configScoreRewardById.Init(),
			SecondaryGuideDataById_1.configSecondaryGuideDataById.Init(),
			SetAccountAll_1.configSetAccountAll.Init(),
			SetAccountById_1.configSetAccountById.Init(),
			SharePlatformAll_1.configSharePlatformAll.Init(),
			SharePlatformById_1.configSharePlatformById.Init(),
			ShareRewardById_1.configShareRewardById.Init(),
			ShieldById_1.configShieldById.Init(),
			ShopFixedByShopId_1.configShopFixedByShopId.Init(),
			ShopFixedByShopIdAndId_1.configShopFixedByShopIdAndId.Init(),
			ShopInfoById_1.configShopInfoById.Init(),
			SignRewardByActivityId_1.configSignRewardByActivityId.Init(),
			SignalDecodeGamePlayById_1.configSignalDecodeGamePlayById.Init(),
			SignalDecodeTabColorById_1.configSignalDecodeTabColorById.Init(),
			SignalDecodeWaveformById_1.configSignalDecodeWaveformById.Init(),
			SilentAreaDetectionAll_1.configSilentAreaDetectionAll.Init(),
			SilentAreaDetectionById_1.configSilentAreaDetectionById.Init(),
			SkillById_1.configSkillById.Init(),
			SkillBySkillGroupId_1.configSkillBySkillGroupId.Init(),
			SkillButtonByRoleId_1.configSkillButtonByRoleId.Init(),
			SkillButtonEffectById_1.configSkillButtonEffectById.Init(),
			SkillButtonIndexById_1.configSkillButtonIndexById.Init(),
			SkillButtonTextAll_1.configSkillButtonTextAll.Init(),
			SkillButtonTextById_1.configSkillButtonTextById.Init(),
			SkillCommonButtonAll_1.configSkillCommonButtonAll.Init(),
			SkillConditionById_1.configSkillConditionById.Init(),
			SkillDescriptionById_1.configSkillDescriptionById.Init(),
			SkillDescriptionBySkillLevelGroupId_1.configSkillDescriptionBySkillLevelGroupId.Init(),
			SkillIconByTag_1.configSkillIconByTag.Init(),
			SkillInputById_1.configSkillInputById.Init(),
			SkillLevelBySkillLevelGroupId_1.configSkillLevelBySkillLevelGroupId.Init(),
			SkillLevelBySkillLevelGroupIdAndSkillId_1.configSkillLevelBySkillLevelGroupIdAndSkillId.Init(),
			SkillTagById_1.configSkillTagById.Init(),
			SkillTreeById_1.configSkillTreeById.Init(),
			SkillTreeByNodeGroup_1.configSkillTreeByNodeGroup.Init(),
			SkillTreeByNodeGroupAndNodeIndex_1.configSkillTreeByNodeGroupAndNodeIndex.Init(),
			SkillTreeByNodeIndex_1.configSkillTreeByNodeIndex.Init(),
			SkillTypeById_1.configSkillTypeById.Init(),
			SkyboxById_1.configSkyboxById.Init(),
			SlideById_1.configSlideById.Init(),
			SortById_1.configSortById.Init(),
			SortRuleByIdAndDataId_1.configSortRuleByIdAndDataId.Init(),
			SoundAreaPlayInfoAll_1.configSoundAreaPlayInfoAll.Init(),
			SoundAreaPlayInfoById_1.configSoundAreaPlayInfoById.Init(),
			SoundBoxMarkByMarkId_1.configSoundBoxMarkByMarkId.Init(),
			SpeakerById_1.configSpeakerById.Init(),
			SpeakerLang_1.configSpeakerLang.Init(),
			SpecialHateAndSenseById_1.configSpecialHateAndSenseById.Init(),
			SpecialItemById_1.configSpecialItemById.Init(),
			StateMachinePreloadByFsmKey_1.configStateMachinePreloadByFsmKey.Init(),
			StateMachinePreloadById_1.configStateMachinePreloadById.Init(),
			SubtitleTextByRowNameAndDatatableName_1.configSubtitleTextByRowNameAndDatatableName.Init(),
			SubtitleTextLang_1.configSubtitleTextLang.Init(),
			SummonCfgById_1.configSummonCfgById.Init(),
			SwimById_1.configSwimById.Init(),
			SwimBuffById_1.configSwimBuffById.Init(),
			SynthesisFormulaByFormulaItemId_1.configSynthesisFormulaByFormulaItemId.Init(),
			SynthesisFormulaByFormulaType_1.configSynthesisFormulaByFormulaType.Init(),
			SynthesisFormulaById_1.configSynthesisFormulaById.Init(),
			SynthesisLevelAll_1.configSynthesisLevelAll.Init(),
			TakeWeedsDifficultyById_1.configTakeWeedsDifficultyById.Init(),
			TalkOptionIconById_1.configTalkOptionIconById.Init(),
			TaskMarkByMarkId_1.configTaskMarkByMarkId.Init(),
			TeamConfigById_1.configTeamConfigById.Init(),
			TeleporterById_1.configTeleporterById.Init(),
			TemplateConfigAll_1.configTemplateConfigAll.Init(),
			TemplateConfigByBlueprintType_1.configTemplateConfigByBlueprintType.Init(),
			TemplateConfigById_1.configTemplateConfigById.Init(),
			TemporaryTeleportMarkByMarkId_1.configTemporaryTeleportMarkByMarkId.Init(),
			TextById_1.configTextById.Init(),
			TimeOfDayById_1.configTimeOfDayById.Init(),
			TimePointRewardActivityByActivityId_1.configTimePointRewardActivityByActivityId.Init(),
			TimePointRewardActivityById_1.configTimePointRewardActivityById.Init(),
			TimePointRewardConfigByActivityId_1.configTimePointRewardConfigByActivityId.Init(),
			ToughCalcRatioById_1.configToughCalcRatioById.Init(),
			TowerBuffById_1.configTowerBuffById.Init(),
			TowerConfigAll_1.configTowerConfigAll.Init(),
			TowerConfigById_1.configTowerConfigById.Init(),
			TowerConfigBySeason_1.configTowerConfigBySeason.Init(),
			TowerDefenceInstanceAll_1.configTowerDefenceInstanceAll.Init(),
			TowerDefenceInstanceById_1.configTowerDefenceInstanceById.Init(),
			TowerDefenceInstanceByInstanceId_1.configTowerDefenceInstanceByInstanceId.Init(),
			TowerDefenceMapMarkAll_1.configTowerDefenceMapMarkAll.Init(),
			TowerDefenceMapMarkByActivityId_1.configTowerDefenceMapMarkByActivityId.Init(),
			TowerDefencePhantomAll_1.configTowerDefencePhantomAll.Init(),
			TowerDefencePhantomById_1.configTowerDefencePhantomById.Init(),
			TowerDefencePhantomLevelAll_1.configTowerDefencePhantomLevelAll.Init(),
			TowerDefencePhantomLevelByGroupId_1.configTowerDefencePhantomLevelByGroupId.Init(),
			TowerDefencePhantomLevelById_1.configTowerDefencePhantomLevelById.Init(),
			TowerDefenceRewardAll_1.configTowerDefenceRewardAll.Init(),
			TowerDefenceRewardById_1.configTowerDefenceRewardById.Init(),
			TowerDifficultyByDifficulty_1.configTowerDifficultyByDifficulty.Init(),
			TowerGuideById_1.configTowerGuideById.Init(),
			TowerTargetById_1.configTowerTargetById.Init(),
			TrackMoonActivityById_1.configTrackMoonActivityById.Init(),
			TrackMoonActivityRewardAll_1.configTrackMoonActivityRewardAll.Init(),
			TrackMoonActivityRewardById_1.configTrackMoonActivityRewardById.Init(),
			TrackMoonEntrustById_1.configTrackMoonEntrustById.Init(),
			TrackMoonHandbookRewardAll_1.configTrackMoonHandbookRewardAll.Init(),
			TrackMoonHandbookRewardById_1.configTrackMoonHandbookRewardById.Init(),
			TrackMoonMemoryAll_1.configTrackMoonMemoryAll.Init(),
			TrackMoonMemoryByClassify_1.configTrackMoonMemoryByClassify.Init(),
			TrackMoonMemoryById_1.configTrackMoonMemoryById.Init(),
			TrackMoonPhaseActivityById_1.configTrackMoonPhaseActivityById.Init(),
			TrackMoonTargetById_1.configTrackMoonTargetById.Init(),
			TrackMoonTargetTypeAll_1.configTrackMoonTargetTypeAll.Init(),
			TrailPhantomPropById_1.configTrailPhantomPropById.Init(),
			TrainRoleDialogByRoleIdAndTrainType_1.configTrainRoleDialogByRoleIdAndTrainType.Init(),
			TreasureBoxDetectorMarkByMarkId_1.configTreasureBoxDetectorMarkByMarkId.Init(),
			TreasureBoxMarkByMarkId_1.configTreasureBoxMarkByMarkId.Init(),
			TrialPhantomPropItemById_1.configTrialPhantomPropItemById.Init(),
			TrialRoleInfoAll_1.configTrialRoleInfoAll.Init(),
			TrialRoleInfoByGroupId_1.configTrialRoleInfoByGroupId.Init(),
			TrialRoleInfoById_1.configTrialRoleInfoById.Init(),
			TrialWeaponInfoById_1.configTrialWeaponInfoById.Init(),
			TurntableActivityByActivityId_1.configTurntableActivityByActivityId.Init(),
			TurntableAwardsByActivityId_1.configTurntableAwardsByActivityId.Init(),
			TurntableAwardsById_1.configTurntableAwardsById.Init(),
			TurntableInfoById_1.configTurntableInfoById.Init(),
			TypeInfoById_1.configTypeInfoById.Init(),
			UiCameraMappingAll_1.configUiCameraMappingAll.Init(),
			UiCameraMappingById_1.configUiCameraMappingById.Init(),
			UiCameraMappingByViewName_1.configUiCameraMappingByViewName.Init(),
			UiDynamicTabByChildViewName_1.configUiDynamicTabByChildViewName.Init(),
			UiDynamicTabById_1.configUiDynamicTabById.Init(),
			UiDynamicTabByParentViewName_1.configUiDynamicTabByParentViewName.Init(),
			UiFloatConfigByViewName_1.configUiFloatConfigByViewName.Init(),
			UiFloatConfigByViewNameIfNull_1.configUiFloatConfigByViewNameIfNull.Init(),
			UiNormalConfigByViewName_1.configUiNormalConfigByViewName.Init(),
			UiNormalConfigByViewNameIfNull_1.configUiNormalConfigByViewNameIfNull.Init(),
			UiPlayItemById_1.configUiPlayItemById.Init(),
			UiResourceById_1.configUiResourceById.Init(),
			UiShowByViewName_1.configUiShowByViewName.Init(),
			UiWeaponVisibleConfigById_1.configUiWeaponVisibleConfigById.Init(),
			UniversalActivityById_1.configUniversalActivityById.Init(),
			VideoCaptionByCgName_1.configVideoCaptionByCgName.Init(),
			VideoDataByCgNameAndGirlOrBoy_1.configVideoDataByCgNameAndGirlOrBoy.Init(),
			VideoSoundByCgNameAndGirlOrBoy_1.configVideoSoundByCgNameAndGirlOrBoy.Init(),
			WeaponBreachByBreachId_1.configWeaponBreachByBreachId.Init(),
			WeaponBreachByBreachIdAndLevel_1.configWeaponBreachByBreachIdAndLevel.Init(),
			WeaponConfByItemId_1.configWeaponConfByItemId.Init(),
			WeaponExpItemById_1.configWeaponExpItemById.Init(),
			WeaponHandBookAll_1.configWeaponHandBookAll.Init(),
			WeaponHandBookById_1.configWeaponHandBookById.Init(),
			WeaponHideConfigById_1.configWeaponHideConfigById.Init(),
			WeaponHideConfigByIdWithZero_1.configWeaponHideConfigByIdWithZero.Init(),
			WeaponLevelByLevelId_1.configWeaponLevelByLevelId.Init(),
			WeaponLevelByLevelIdAndLevel_1.configWeaponLevelByLevelIdAndLevel.Init();
		WeaponModelTransformById_1.configWeaponModelTransformById.Init(),
			WeaponPropertyGrowthByCurveIdLevelAndBreachLevel_1.configWeaponPropertyGrowthByCurveIdLevelAndBreachLevel.Init(),
			WeaponQualityInfoById_1.configWeaponQualityInfoById.Init(),
			WeaponResonByResonIdAndLevel_1.configWeaponResonByResonIdAndLevel.Init(),
			WeaponVisibleConfigById_1.configWeaponVisibleConfigById.Init(),
			WeaponVisibleConfigByIdWithZero_1.configWeaponVisibleConfigByIdWithZero.Init(),
			WeatherById_1.configWeatherById.Init(),
			WorldLevelById_1.configWorldLevelById.Init(),
			WorldNewJourneyAll_1.configWorldNewJourneyAll.Init(),
			WorldNewJourneyById_1.configWorldNewJourneyById.Init();
	}
}
exports.ConfigStatement = ConfigStatement;
//# sourceMappingURL=ConfigStatement.js.map
