"use strict";
Object.defineProperty(exports, "__esModule", { value: !0 }),
	(exports.COMPOSITE_FAIL_SEQUENCE_TIME_LENGTH =
		exports.COMPOSITE_WORKING_SEQUENCE_TIME_LENGTH =
		exports.COMPOSITE_ENTER_SEQUENCE_TIME_LENGTH =
		exports.COMPOSE_TYPE_TEXTURE_PATH_KEY =
			void 0),
	(exports.COMPOSE_TYPE_TEXTURE_PATH_KEY = "T_ComposeType"),
	(exports.COMPOSITE_ENTER_SEQUENCE_TIME_LENGTH = 3e3),
	(exports.COMPOSITE_WORKING_SEQUENCE_TIME_LENGTH = 2e3),
	(exports.COMPOSITE_FAIL_SEQUENCE_TIME_LENGTH = 2e3);
